C1 = "Codigo/014 - Clase 24-06/"
C2 = "Codigo/015 - Clase 29-07/"
JAVA = "src/main/java/edu/usal/basedatos/"

POM_MYSQL = lambda art: {
 "rol": "Archivo de configuración de Maven (POM) del proyecto. Declara las coordenadas del proyecto, la versión de Java y la dependencia del driver JDBC de MySQL.",
 "defensa": "Maven descarga solo el driver (<b>mysql-connector-j</b>) y lo agrega al classpath; sin él, <i>DriverManager</i> no puede hablar con MySQL. Es un driver <b>tipo 4</b>: está escrito 100% en Java y habla directo el protocolo de MySQL, sin librerías nativas (portable).",
 "bloques": [
  ("", "Cabecera XML del POM y versión del modelo (4.0.0)."),
  ("<groupId>edu.usal", f"Coordenadas del proyecto: grupo <b>edu.usal</b>, artefacto <b>{art}</b> y versión 1.0-SNAPSHOT (SNAPSHOT = en desarrollo)."),
  ("<properties>", "Propiedades: compila con Java 11 (source y target) y lee los fuentes en UTF-8 (para no romper tildes y eñes)."),
  ("<dependencies>", "Dependencia del driver <b>com.mysql:mysql-connector-j</b> versión 9.2.0. Maven la baja del repositorio central automáticamente."),
  ("</project>", "Cierre del POM."),
 ]}

CONECTOR = {
 "rol": "Clase que arma y devuelve una conexión (<i>Connection</i>) a la base MySQL <b>universidad</b>.",
 "defensa": "Centraliza en un único lugar los datos de conexión, para que el resto de las clases solo llamen a <i>getConnection()</i>. Es el antecedente del patrón Singleton / DAO que se ve en la clase siguiente. Mejoras que se pueden mencionar: no dejar la contraseña escrita en el código (usar un archivo .properties o variables de entorno), no devolver <i>null</i> ante un error (lanzar una excepción propia) y usar un pool de conexiones.",
 "bloques": [
  ("", "Declaración del paquete (<i>connection</i>): agrupa lo relativo a la conexión."),
  ("import java.sql.Connection", "@imports"),
  ("public class MySqlConector", "Declara la clase conectora."),
  ("public static Connection getConnection", "Método <b>estático</b>: se llama sin crear objetos (<i>MySqlConector.getConnection()</i>). Devuelve un objeto <b>Connection</b>, la sesión abierta con la base."),
  ("Class.forName", "Carga en memoria la clase del driver de MySQL (<i>com.mysql.cj.jdbc.Driver</i>). Con los drivers modernos es opcional (se autorregistran), pero es lo que se enseña como paso 1 de JDBC. Si el .jar no está, lanza <b>ClassNotFoundException</b>, que se captura y se informa."),
  ("String urlJdbc", "Datos de conexión. La URL JDBC tiene el formato <b>jdbc:mysql://servidor:puerto/base</b>: acá servidor local, puerto 3306 (el de MySQL) y base <i>universidad</i>. Luego usuario y contraseña, y la variable <i>connection</i> inicializada en null."),
  ("connection = DriverManager.getConnection", "Paso 2 de JDBC: <b>DriverManager</b> busca el driver adecuado según la URL y abre la conexión con usuario y contraseña. Si falla (base apagada, clave incorrecta) lanza <b>SQLException</b>."),
  ("} catch (SQLException e)", "Captura el error y muestra su mensaje por consola."),
  ("return connection", "Devuelve la conexión (o null si falló, algo que conviene evitar). Quien la recibe es responsable de cerrarla con <i>close()</i>."),
 ]}

TEMA = {
 "carpeta": "Tema 01 - JDBC (Statement, PreparedStatement y CallableStatement)",
 "titulo": "Tema 01 · JDBC: Statement, PreparedStatement y CallableStatement",
 "clases": "Clases 014 (24-06) y 015 (29-07) · Teoría: «Base de datos – Parte I, II y III»",
 "intro": [
  ("nota", "<b>Ubicación del tema:</b> estas dos clases cierran el primer tramo de la materia, pero JDBC es la base de todo lo que sigue y el parcial del 2.º cuatrimestre pide explícitamente «los tres métodos de JDBC (Statement, PreparedStatement y CallableStatement)». Por eso este tema es el primero de la carpeta."),
  ("h1", "1. Qué es JDBC"),
  ("p", "<b>JDBC (Java Database Connectivity)</b> es la API estándar de Java para hablar con bases de datos relacionales. Es un conjunto de interfaces del paquete <i>java.sql</i> (Connection, Statement, ResultSet…). Cada fabricante de base de datos (MySQL, SQL Server, PostgreSQL…) entrega un <b>driver</b> que implementa esas interfaces. Gracias a eso el código Java es casi el mismo para cualquier motor: lo único que cambia es el driver y la URL."),
  ("p", "Existen cuatro tipos de drivers. El <b>tipo 4</b> (el que usamos) es 100% Java y se comunica directamente con el protocolo de red de la base de datos: no necesita software nativo instalado y es portable. Es el estándar en arquitecturas de tres capas."),
  ("h1", "2. Los pasos de cualquier acceso a datos con JDBC"),
  ("tabla", [["Paso", "Qué se hace", "Clase o método"],
    ["1", "Cargar el driver (opcional en drivers modernos)", "Class.forName(\"com.mysql.cj.jdbc.Driver\")"],
    ["2", "Abrir la conexión", "DriverManager.getConnection(url, usuario, clave) → Connection"],
    ["3", "Crear la sentencia", "createStatement() / prepareStatement(sql) / prepareCall(\"{call sp(?)}\")"],
    ["4", "Ejecutar", "executeQuery() (SELECT → ResultSet), executeUpdate() (INSERT/UPDATE/DELETE → filas afectadas), execute()"],
    ["5", "Recorrer el resultado", "while (rs.next()) { rs.getString(\"col\") ... }"],
    ["6", "Cerrar los recursos", "rs.close(), st.close(), con.close() — siempre en este orden: primero lo más interno"]]),
  ("p", "<b>La URL JDBC</b> de MySQL tiene la forma <i>jdbc:mysql://host:puerto/nombre_base</i>. Una <b>SQLException</b> puede ocurrir en casi todos los pasos y es una excepción controlada (checked): hay que capturarla o declararla con <i>throws</i>."),
  ("h1", "3. Los tres tipos de sentencia"),
  ("tabla", [["", "Statement", "PreparedStatement", "CallableStatement"],
    ["Para qué sirve", "SQL fijo, sin parámetros", "SQL con parámetros <b>?</b>, precompilado", "Llamar a un <b>procedimiento almacenado</b> (SP)"],
    ["Cómo se crea", "con.createStatement()", "con.prepareStatement(sql)", "con.prepareCall(\"{call sp(?,?)}\")"],
    ["Cómo se ejecuta", "st.executeQuery(sql) — el SQL se pasa al ejecutar", "ps.executeQuery() — sin argumentos: el SQL ya se pasó al crearlo", "cs.execute()"],
    ["Parámetros", "No: se concatena el texto (peligroso)", "ps.setString(1, ...), setInt(2, ...)", "IN con setXxx, OUT con registerOutParameter + getXxx"],
    ["Seguridad", "<b>Vulnerable a inyección SQL</b>", "Protege contra inyección SQL", "Protege (parámetros) y centraliza lógica en la base"],
    ["Rendimiento", "Se compila en cada ejecución", "Se compila una vez y se reutiliza", "Altamente performante: el SP ya está en el servidor"],
    ["Cuándo usarlo", "Consultas fijas (ej. listar todo)", "Todo lo que recibe datos del usuario", "Lógica de negocio dentro de la base"]]),
  ("h2", "Métodos de ejecución"),
  ("li", "<b>executeQuery(sql)</b> → devuelve un <i>ResultSet</i>. Se usa para SELECT."),
  ("li", "<b>executeUpdate(sql)</b> → devuelve un <i>int</i> con la cantidad de filas afectadas. Se usa para INSERT, UPDATE y DELETE."),
  ("li", "<b>execute(sql)</b> → devuelve <i>true</i> si la sentencia generó un ResultSet (SELECT) y <i>false</i> si no (INSERT/UPDATE/DELETE). Es el método genérico; con CallableStatement es el que se usa."),
  ("h1", "4. La inyección SQL (SQL Injection)"),
  ("p", "Si el SQL se arma <b>concatenando</b> lo que escribió el usuario, el usuario puede meter código SQL. Ejemplo (el que muestra la clase en el método <i>sqlI</i>): el login arma <i>SELECT * FROM usuarios WHERE username = '</i>+user+<i>' AND password = '</i>+pass+<i>'</i>. Si en la contraseña se escribe <b>' OR '1' = '1</b> la consulta queda <i>… password = '' OR '1' = '1'</i>, que es siempre verdadera: el atacante entra sin saber la clave. Con <b>PreparedStatement</b> los valores viajan separados del SQL y siempre se tratan como datos, nunca como código, por eso es inmune."),
  ("h1", "5. El ResultSet"),
  ("li", "Es el resultado de un SELECT. Por defecto es <b>solo avance y solo lectura</b> (TYPE_FORWARD_ONLY + CONCUR_READ_ONLY)."),
  ("li", "El cursor arranca <b>antes de la primera fila</b>; <i>next()</i> lo mueve y devuelve <i>true</i> mientras haya una fila."),
  ("li", "Se leen las columnas con <i>getXxx(\"nombre\")</i> o <i>getXxx(posicion)</i>. <b>Las posiciones empiezan en 1</b>, no en 0."),
  ("li", "Métodos de posición: isFirst(), isBeforeFirst(), isLast(), isAfterLast(), getRow()."),
  ("li", "<b>ResultSetMetaData</b> (<i>rs.getMetaData()</i>) informa sobre las columnas: getColumnCount(), getColumnName(i), getColumnType(i), getColumnTypeName(i). Permite armar listados genéricos."),
  ("li", "Con <i>createStatement(tipo, concurrencia)</i> se cambia el comportamiento: TYPE_SCROLL_INSENSITIVE / TYPE_SCROLL_SENSITIVE (moverse en ambos sentidos) y CONCUR_UPDATABLE (modificar filas desde el ResultSet)."),
  ("li", "Si el mismo Statement ejecuta otra consulta, el ResultSet anterior se cierra solo. Para dos ResultSet a la vez se necesitan dos Statement."),
  ("h1", "6. Procedimientos almacenados y CallableStatement"),
  ("p", "Un <b>procedimiento almacenado (stored procedure, SP)</b> es un bloque de código SQL guardado dentro de la base de datos, con nombre y parámetros. Ventajas: rendimiento (ya está compilado en el servidor), seguridad y reutilización de la lógica. Sus parámetros pueden ser <b>IN</b> (entrada), <b>OUT</b> (salida) o <b>INOUT</b>."),
  ("p", "Desde Java se invoca con <b>CallableStatement</b>: <i>con.prepareCall(\"{ call nombre_sp(?, ?, ?) }\")</i>. Los parámetros de entrada se cargan con <i>setXxx(índice, valor)</i>; los de salida se <b>registran antes de ejecutar</b> con <i>registerOutParameter(índice, Types.XXX)</i>; se ejecuta con <i>execute()</i> y los valores de salida se leen con <i>getXxx(índice)</i>."),
  ("h1", "7. Cierre de recursos y transacciones (adelanto)"),
  ("p", "Statement y ResultSet los cierra el recolector de basura, pero <b>se deben cerrar explícitamente</b> con <i>close()</i> para liberar recursos. Orden: primero ResultSet y Statement, <b>luego</b> la Connection (cerrar la conexión primero provoca errores). Hoy se recomienda <b>try-with-resources</b>, que cierra solo y en el orden correcto. Las transacciones (<i>setAutoCommit(false)</i>, <i>commit()</i>, <i>rollback()</i>) se desarrollan en el Tema 02."),
 ],
 "clases_detalle": [
  {"titulo": "Clase 014 – 24-06: Statement vs. PreparedStatement",
   "resumen": [("p", "Se crea una base <b>universidad</b> con la tabla <i>estudiantes</i> y se programan: un alta y una búsqueda con <b>Statement</b> (concatenando texto), una demostración de inyección SQL y una actualización con <b>PreparedStatement</b>. La clase <i>Pruebas</i> es el <i>main</i> que las ejecuta.")],
   "archivos": {
    C1 + "pom.xml": POM_MYSQL("clase-24-06"),
    C1 + "src/main/resources/db.sql": {
     "rol": "Script SQL que crea la base <b>universidad</b>, la tabla <b>estudiantes</b> y la llena con 45 estudiantes de prueba.",
     "defensa": "Sin datos de prueba no se pueden mostrar las consultas. <i>DROP TABLE IF EXISTS</i> permite correr el script varias veces sin error. El <i>id</i> es AUTO_INCREMENT: lo genera la base y no se inserta a mano.",
     "bloques": [
      ("", "Crea la base si no existe y la selecciona con <b>USE</b>."),
      ("DROP TABLE", "Borra la tabla si existía, para empezar de cero."),
      ("CREATE TABLE estudiantes", "Crea la tabla: <b>id</b> entero autoincremental y clave primaria; <b>nombre</b> y <b>carrera</b> de texto (hasta 100), <b>edad</b> entera y <b>promedio</b> decimal, todos obligatorios (NOT NULL)."),
      ("INSERT INTO estudiantes", "Un único INSERT con muchas filas (una tupla por estudiante): nombre, edad, carrera y promedio. Sirve para tener datos sobre los que consultar y actualizar."),
     ]},
    C1 + JAVA + "connection/MySqlConector.java": CONECTOR,
    C1 + JAVA + "statement/StatementQuery.java": {
     "rol": "Muestra cómo usar <b>Statement</b>: un alta (INSERT), una búsqueda (SELECT) y una simulación de inyección SQL.",
     "defensa": "Sirve para mostrar <b>por qué no hay que usar Statement con datos del usuario</b>: el SQL se arma concatenando textos y es vulnerable. También ilustra el ciclo completo: conexión → sentencia → ejecución → resultado → cierre. Para el parcial: <b>Statement</b> se reserva para consultas fijas sin parámetros (por ejemplo listar todo).",
     "bloques": [
      ("", "Paquete <i>statement</i>."),
      ("import edu.usal", "@imports"),
      ("public class StatementQuery", "Clase con tres métodos de ejemplo."),
      ("public void addEstudiante", "Alta de un estudiante. Recibe los datos como parámetros del método y declara <b>throws SQLException</b> (no la captura: la propaga a quien llama)."),
      ("String strSQL = \"INSERT", "Arma el INSERT <b>concatenando</b> los valores dentro del texto SQL. Los textos van entre comillas simples (<i>'\" + nombre + \"'</i>) y los números sin comillas. Es la forma insegura: si <i>nombre</i> contiene una comilla o código SQL, rompe o altera la sentencia."),
      ("Connection connection = MySqlConector", "Pide una conexión y crea el objeto <b>Statement</b> con <i>createStatement()</i>."),
      ("int filasAfectadas", "<b>executeUpdate(sql)</b> envía el INSERT y devuelve cuántas filas se afectaron. Si fue 1 o más, informa el alta."),
      ("statement.close()", "Cierra primero el Statement y después la Connection (ese orden es obligatorio)."),
      ("public void buscarPorNombre", "Búsqueda por nombre. Arma el SELECT concatenando el nombre entre comillas simples."),
      ("ResultSet resultSet", "<b>executeQuery(sql)</b> ejecuta el SELECT y devuelve un <b>ResultSet</b>."),
      ("while(resultSet.next())", "Recorre el resultado: <i>next()</i> avanza el cursor y devuelve true mientras haya filas. Lee columnas por posición (<i>getInt(1)</i>, la primera columna es 1) o por nombre (<i>getString(\"nombre\")</i>, <i>getDouble</i>) y las imprime."),
      ("statement.close();\n        connection.close();\n    }\n\n    public void sqlI", "Cierre de recursos."),
      ("public void sqlI", "Demostración de <b>inyección SQL</b>: arma el texto de un login concatenando usuario y contraseña y lo imprime (no lo ejecuta). Con la contraseña <i>' OR '1' = '1</i> el SQL resultante es <i>… AND password = '' OR '1' = '1'</i>, que siempre es verdadero."),
     ]},
    C1 + JAVA + "statement/PreparedStatementQuery.java": {
     "rol": "Muestra cómo usar <b>PreparedStatement</b> con parámetros <b>?</b> para actualizar el promedio de un estudiante.",
     "defensa": "Es la forma correcta cuando hay datos del usuario: el SQL está escrito una sola vez con comodines <b>?</b> y los valores se cargan aparte con <i>setXxx</i>. No hay concatenación, así que <b>no hay inyección SQL</b>, se evitan errores de comillas y la base puede reutilizar la sentencia precompilada.",
     "bloques": [
      ("", "Paquete <i>statement</i>."),
      ("import edu.usal", "@imports"),
      ("public class PreparedStatementQuery", "Clase con un método de ejemplo."),
      ("public void actualizar", "Recibe el nuevo promedio y el nombre del estudiante."),
      ("String strSQL = \"UPDATE", "El SQL con dos comodines <b>?</b>: no llevan comillas aunque sean texto; JDBC se encarga."),
      ("PreparedStatement preparedStatement", "<b>prepareStatement(sql)</b> recibe el SQL ya al crear el objeto (a diferencia de Statement). Aquí se precompila."),
      ("preparedStatement.setDouble", "Asigna los valores: <i>setXxx(posición, valor)</i>. La posición del <b>?</b> empieza en 1: el 1 es el promedio y el 2 el nombre; el tipo del método (<i>setDouble</i>, <i>setString</i>) debe coincidir con el de la columna."),
      ("int filasAfectadas", "<b>executeUpdate()</b> va <b>sin argumentos</b> porque el SQL ya está en el objeto. Devuelve las filas modificadas; si es ≥ 1 informa el éxito."),
      ("preparedStatement.close()", "Cierra el PreparedStatement y la Connection."),
     ]},
    C1 + JAVA + "Pruebas.java": {
     "rol": "Clase con el <i>main</i> que prueba las clases anteriores.",
     "defensa": "Es el punto de entrada de la demostración. Las líneas comentadas son pruebas que se activan de a una.",
     "bloques": [
      ("", "Paquete base."),
      ("import edu.usal", "@imports"),
      ("public class Pruebas", "Clase de prueba."),
      ("public static void main", "Punto de entrada. Declara <i>throws SQLException</i> porque los métodos probados la propagan. Crea un <i>StatementQuery</i> y deja comentadas las pruebas de alta y búsqueda."),
      ("statementQuery.sqlI", "Ejecuta la demostración de inyección SQL con la contraseña maliciosa."),
      ("PreparedStatementQuery psQuery", "Crea el objeto de PreparedStatement (su prueba queda comentada)."),
     ]},
   }},
  {"titulo": "Clase 015 – 29-07: CallableStatement y procedimientos almacenados",
   "resumen": [("p", "Se crea un <b>procedimiento almacenado</b> en MySQL (<i>sp_procesar_beca</i>) que decide si a un estudiante se le otorga una beca según su promedio, y se lo llama desde Java con <b>CallableStatement</b>. El procedimiento usa dos parámetros de entrada (IN) y uno de salida (OUT).")],
   "archivos": {
    C2 + "pom.xml": POM_MYSQL("clase-29-07"),
    C2 + "src/main/resources/sp.sql": {
     "rol": "Define el procedimiento almacenado <b>sp_procesar_beca</b> en la base <i>universidad</i>.",
     "defensa": "La <b>regla de negocio</b> (promedio ≥ 8 para tener beca) vive <b>dentro de la base</b>, no en Java. Eso es lo que justifica usar un SP: lógica centralizada y rápida, reutilizable por cualquier aplicación. Observación para la defensa: el script quedó con un <i>DELIMITER ;</i> final sin su <i>DELIMITER $$</i> inicial; en el cliente de MySQL (Workbench/consola) hay que cambiar el delimitador antes de crear el procedimiento para que los <b>;</b> internos no corten la sentencia.",
     "bloques": [
      ("", "Encabezado del procedimiento: se llama <b>sp_procesar_beca</b> y tiene tres parámetros: <b>IN p_estudiante_id</b> (entero, qué estudiante), <b>IN p_monto_solicitado</b> (decimal, cuánto se pide) y <b>OUT p_resultado</b> (texto de hasta 100 caracteres con la respuesta, que el SP devuelve a quien lo llama)."),
      ("BEGIN", "Inicio del cuerpo. Declara la variable local <b>v_promedio</b> (DOUBLE)."),
      ("-- Obtener el promedio", "Consulta con <b>SELECT … INTO</b>: guarda el promedio del estudiante en la variable. Si no existe el estudiante, la variable queda en NULL."),
      ("-- Lógica de negocio", "Lógica con IF/ELSEIF/ELSE: si el promedio es NULL el estudiante no existe (resultado de error); si es ≥ 8.0 se aprueba la beca y el mensaje se arma con <b>CONCAT</b> incluyendo el monto; en otro caso se rechaza informando el promedio y el mínimo requerido. <b>SET p_resultado = …</b> asigna el parámetro de salida."),
      ("END", "Cierra el procedimiento."),
      ("DELIMITER ;", "Restaura el delimitador normal ( ; ). Ver la observación de la defensa."),
     ]},
    C2 + JAVA + "connection/MySqlConector.java": CONECTOR,
    C2 + JAVA + "callable/CallableSt.java": {
     "rol": "Llama al procedimiento almacenado <i>sp_procesar_beca</i> usando <b>CallableStatement</b> y devuelve el texto de resultado.",
     "defensa": "Es el modelo a seguir para el punto «uso de CallableStatement» del parcial. Pasos que hay que saber de memoria: <b>(1)</b> prepareCall con la sintaxis <i>{ call sp(?, ?, ?) }</i>; <b>(2)</b> setXxx para los IN; <b>(3)</b> <i>registerOutParameter</i> para los OUT <b>antes</b> de ejecutar; <b>(4)</b> <i>execute()</i>; <b>(5)</b> getXxx para leer los OUT; <b>(6)</b> cerrar.",
     "bloques": [
      ("", "Paquete <i>callable</i>."),
      ("import edu.usal", "@imports"),
      ("public class CallableSt", "Clase que encapsula la llamada al SP."),
      ("public String verificarBeca", "Recibe el id del estudiante y el monto y devuelve el mensaje de resultado. Propaga <i>SQLException</i>."),
      ("String strSP", "Sintaxis estándar JDBC para llamar a un SP: <b>{ call nombre(?, ?, ?) }</b>, un <b>?</b> por parámetro (los dos IN y el OUT)."),
      ("CallableStatement callableStatement", "<b>prepareCall</b> crea el CallableStatement a partir del texto del SP."),
      ("callableStatement.setInt", "Carga los parámetros de <b>entrada</b>: posición 1 = id, posición 2 = monto."),
      ("registerOutParameter", "Registra el tercer parámetro como <b>de salida</b> de tipo VARCHAR (<i>java.sql.Types</i>). Si no se registra antes de ejecutar, falla."),
      ("callableStatement.execute()", "Ejecuta el procedimiento en la base. Se usa <b>execute()</b>."),
      ("String resultado", "Lee el parámetro de salida con <i>getString(3)</i> (la posición del OUT)."),
      ("callableStatement.close()", "Cierra el CallableStatement y la conexión."),
      ("return resultado", "Devuelve el mensaje al que llamó."),
     ]},
    C2 + JAVA + "PruebaSP.java": {
     "rol": "<i>main</i> que prueba el procedimiento y deja, como comentario, un ejercicio de práctica sobre qué tipo de sentencia usar en cada caso.",
     "defensa": "El comentario es oro para el parcial: enseña a <b>elegir la sentencia correcta</b>. Listar todo (SELECT sin parámetros) → Statement o PreparedStatement con executeQuery. Buscar por parte del título (LIKE con parámetros) → PreparedStatement con executeQuery. Registrar un préstamo con un SP y obtener la respuesta → CallableStatement con execute.",
     "bloques": [
      ("", "Paquete base."),
      ("import edu.usal", "@imports"),
      ("public class PruebaSP", "Clase de prueba."),
      ("public static void main", "Crea el objeto, llama a <i>verificarBeca(47, 5000.0)</i> (estudiante 47, monto $5000) e imprime la respuesta del SP."),
      ("/*", "Comentario de bloque con el ejercicio: para cada punto se indica la sentencia y el método de ejecución correctos. Punto 1: listado general, no lleva parámetros. Punto 2: búsqueda con LIKE y parámetros, por lo que PreparedStatement. Punto 3: ejecutar un SP, por lo que CallableStatement con execute()."),
     ]},
   }},
 ],
 "cierre": [
  ("h1", "Resumen para estudiar"),
  ("li", "JDBC = API estándar (java.sql) + un driver por motor. Tipo 4 = todo Java."),
  ("li", "Pasos: driver → Connection → sentencia → ejecutar → ResultSet → cerrar (sentencia primero, conexión después)."),
  ("li", "<b>Statement</b>: SQL fijo; vulnerable si se concatena. <b>PreparedStatement</b>: parámetros ?, seguro y rápido. <b>CallableStatement</b>: SP con IN/OUT."),
  ("li", "executeQuery → ResultSet; executeUpdate → filas afectadas; execute → boolean."),
  ("li", "ResultSet: next(), getXxx desde la posición 1; ResultSetMetaData para describir columnas."),
  ("h1", "Mejoras del código de clase (para sumar puntos en la defensa)"),
  ("li", "Cerrar recursos con <b>try-with-resources</b> para que se cierren aunque ocurra una excepción (en las clases de ejemplo, si falla el SQL, la conexión queda abierta)."),
  ("li", "No hardcodear usuario y contraseña: usar un archivo .properties o variables de entorno."),
  ("li", "No devolver null ante un error de conexión: lanzar una excepción propia."),
  ("li", "En <i>buscarPorNombre</i> el mensaje imprime el parámetro <i>nombre</i> en lugar del <i>nombreBd</i> leído de la base (inofensivo acá porque son iguales, pero es una imprecisión)."),
  ("h1", "Preguntas típicas"),
  ("q", "¿Cuál es la diferencia entre Statement y PreparedStatement?"),
  ("p", "Statement se arma concatenando y se compila en cada ejecución; es vulnerable a inyección SQL. PreparedStatement usa parámetros ?, se precompila, es más rápido al repetirse y es seguro."),
  ("q", "¿Por qué se cierra la Statement antes que la Connection?"),
  ("p", "Porque la sentencia depende de la conexión: cerrar la conexión primero deja la sentencia inválida y provoca una excepción."),
  ("q", "¿Para qué sirve registerOutParameter?"),
  ("p", "Para avisarle a JDBC que un parámetro del SP es de salida y de qué tipo, antes de ejecutar; luego se lee con getXxx."),
 ],
}
