B = "Codigo/016 - Clase 05-08 Maven Parent/"
BD = B + "016 - Clase 05-08/src/main/java/edu/usal/basedatos/"
SI = B + "016 - Clase 05-08 single-maven/"

GET_SET = "Getters y setters: métodos públicos que leen (<i>get</i>) y modifican (<i>set</i>) los atributos privados. Es el <b>encapsulamiento</b>: nadie toca los datos directamente."

TEMA = {
 "carpeta": "Tema 02 - Singleton, DAO con transacciones y Maven multimodulo",
 "titulo": "Tema 02 · Singleton, DAO con transacciones y Maven multimódulo",
 "clases": "Clase 016 (05-08) · Teoría: «Base de datos – Parte III» y «Patrones de diseño»",
 "intro": [
  ("h1", "1. Patrones de diseño"),
  ("p", "Un <b>patrón de diseño</b> es el «esqueleto de la solución» a un problema que aparece una y otra vez en el desarrollo de software. Para ser un patrón debe haber demostrado su efectividad y poder reutilizarse. Se clasifican en:"),
  ("li", "<b>Creacionales</b>: controlan cómo se crean los objetos (Singleton, Factory, DAO en la clasificación de la cátedra)."),
  ("li", "<b>Estructurales</b>: cómo se agrupan clases y objetos en estructuras mayores, separando interfaz de implementación."),
  ("li", "<b>De comportamiento</b>: cómo se comunican los objetos entre sí."),
  ("h1", "2. Patrón Singleton"),
  ("p", "<b>Garantiza que una clase tenga una única instancia y proporciona un punto de acceso global a ella.</b> Se usa cuando un recurso debe gestionarse de forma centralizada: la configuración de la aplicación, el pool/conexión a la base de datos, un log. Las <b>tres reglas</b> que hay que saber:"),
  ("tabla", [["Regla", "Cómo se implementa"],
    ["1. Constructor privado", "Nadie fuera de la clase puede hacer <i>new</i>."],
    ["2. Atributo estático que guarda la instancia", "<i>private static Clase instancia;</i> — pertenece a la clase, no a un objeto."],
    ["3. Método público estático de acceso", "<i>getInstance()</i>: si <i>instancia</i> es null la crea; siempre devuelve la misma."]]),
  ("p", "<b>Hilos:</b> en una aplicación web varios hilos pueden llamar a getInstance() a la vez; si dos ven <i>instancia == null</i> al mismo tiempo se crearían dos objetos. Por eso se usa <i>synchronized</i> en el método (como en la clase) o una inicialización segura (holder idiom, enum). Prueba típica: pedir la instancia dos veces y comparar con <b>==</b>: son el mismo objeto."),
  ("h1", "3. Patrón DAO (Data Access Object)"),
  ("p", "Abstrae el acceso a datos para que la lógica de negocio no sepa <i>cómo</i> ni <i>dónde</i> se guardan los datos. Tiene tres piezas:"),
  ("tabla", [["Pieza", "Qué es", "En esta clase"],
    ["Entidad (POJO / DTO)", "Clase simple con atributos, constructores, getters y setters que representa un dato del negocio", "Cuenta, Moviento"],
    ["Interfaz DAO", "Contrato con las operaciones (CRUD: Create, Read, Update, Delete) sin mencionar la tecnología", "CuentaDAO, MovimientoDAO"],
    ["Implementación (DAOImpl)", "La lógica concreta (JDBC, memoria, archivos…)", "CuentaDAOImpl, MovimientoDAOImpl"]]),
  ("p", "Junto con el patrón <b>Factory</b> (una clase que decide qué implementación entregar) se puede cambiar de persistencia en memoria a JDBC sin tocar el código que usa el DAO. Además suele haber una <b>capa de servicio</b> (acá <i>TransferenciaService</i>) que coordina varios DAO para implementar un caso de uso."),
  ("h1", "4. Transacciones JDBC"),
  ("p", "Una <b>transacción</b> es un conjunto de operaciones que debe ejecutarse como una unidad <b>atómica</b>: o se hacen todas o no se hace ninguna. El ejemplo clásico es la <b>transferencia bancaria</b>: restar a la cuenta A y sumar a la cuenta B. Si se resta pero falla el sumar, el dinero desaparece. En JDBC:"),
  ("codigo", "con.setAutoCommit(false);   // desactiva el commit automático: empieza la transacción\ntry {\n    ... sentencias SQL ...\n    con.commit();           // todo salió bien: se confirman los cambios\n} catch (SQLException e) {\n    con.rollback();         // algo falló: se deshace todo\n} finally {\n    con.close();            // siempre se libera la conexión\n}"),
  ("p", "<b>Punto clave:</b> todas las sentencias de la transacción deben usar <b>la misma Connection</b>. Por eso, en el DAO, los métodos que forman parte de una transacción <b>reciben la conexión por parámetro</b> (descontarSaldo(connection, cuenta)) y es el <b>servicio</b> quien abre la conexión, controla commit y rollback y la cierra."),
  ("h1", "5. Maven: ciclo de vida y multimódulo"),
  ("p", "<b>Maven</b> automatiza la construcción del proyecto y la gestión de dependencias. Todo se declara en el <b>pom.xml</b> (Project Object Model). Las fases del ciclo de vida son secuenciales:"),
  ("tabla", [["Fase", "Qué hace"],
    ["clean", "Borra la carpeta target (compilaciones anteriores)"], ["compile", "Compila el código fuente a bytecode"],
    ["test", "Ejecuta las pruebas unitarias"], ["package", "Empaqueta en JAR o WAR"], ["install", "Publica el artefacto en el repositorio local (~/.m2) para usarlo desde otros proyectos"]]),
  ("p", "Un <b>Maven Parent</b> (packaging <i>pom</i>) agrupa varios <b>módulos</b>. Cada módulo hijo declara su <i>&lt;parent&gt;</i> y puede depender de otro módulo como si fuera una librería. Es exactamente la estructura que pide el parcial: un proyecto <b>DAO</b> (persistencia) y un proyecto <b>Web/MVC</b> (presentación) que depende del DAO."),
  ("h1", "6. Excepciones propias"),
  ("p", "<b>NegocioException</b> extiende de <b>RuntimeException</b> (no controlada): no obliga a declararla ni capturarla. Se usa para errores de regla de negocio (saldo insuficiente). Contraste: <b>SQLException</b> es <i>checked</i> (controlada) y obliga a tratarla. Elegir una u otra es una decisión de diseño que conviene poder justificar."),
 ],
 "clases_detalle": [
  {"titulo": "Clase 016 – 05-08: Singleton y transferencia bancaria con Maven multimódulo",
   "resumen": [("p", "La carpeta contiene un <b>Maven parent</b> con dos módulos: <i>016 - Clase 05-08</i> (la capa de datos: dominio, DAO, servicio de transferencia y excepción) y <i>016 - Clase 05-08 single-maven</i> (un ejemplo de Singleton que <b>depende</b> del primer módulo). El código de la transferencia es un <b>esqueleto de clase</b>: muestra la estructura y el flujo transaccional pero algunos pasos están marcados con TODO o vacíos. Más abajo se señalan esas partes.")],
   "archivos": {
    B + "pom.xml": {
     "rol": "POM <b>padre</b> (packaging <i>pom</i>): agrupa los dos módulos de la clase.",
     "defensa": "Con un padre se compilan todos los módulos con un solo comando (<i>mvn package</i> en la raíz) y se comparte la configuración (Java 11, UTF-8). Maven ordena solo la compilación según las dependencias entre módulos.",
     "bloques": [
      ("", "Cabecera del POM."),
      ("<groupId>edu.usal", "Coordenadas del padre y <b>&lt;packaging&gt;pom&lt;/packaging&gt;</b>: no genera jar ni war, solo agrupa."),
      ("<properties>", "Java 11 y UTF-8 para todos los módulos hijos (se heredan)."),
      ("<modules>", "Lista de <b>módulos</b> hijos: el de datos y el del Singleton."),
     ]},
    B + "016 - Clase 05-08/pom.xml": {
     "rol": "POM del módulo de datos (hijo del padre), con la dependencia del driver de MySQL.",
     "defensa": "Hereda las propiedades del padre mediante <i>&lt;parent&gt;</i>. Es el módulo que luego usa el otro como dependencia.",
     "bloques": [
      ("", "Cabecera."),
      ("<parent>", "Declara el <b>padre</b> (mismas coordenadas que el pom padre): de ahí hereda propiedades."),
      ("<artifactId>clase-05-08</artifactId>", "Coordenadas propias del módulo: <b>clase-05-08</b>."),
      ("<dependencies>", "Depende del driver JDBC de MySQL 9.2.0."),
      ("</project>", "Cierre."),
     ]},
    SI + "pom.xml": {
     "rol": "POM del módulo Singleton. <b>Depende del módulo clase-05-08</b>.",
     "defensa": "Demuestra la dependencia entre módulos: para usarlo, <i>clase-05-08</i> tiene que estar compilado o instalado (<i>mvn install</i>). Es el mismo mecanismo con el que el módulo Web del parcial usa al módulo DAO.",
     "bloques": [
      ("", "Cabecera."),
      ("<parent>", "Declara el mismo padre."),
      ("<artifactId>clase-05-08-single-maven", "Coordenadas del módulo."),
      ("<dependencies>", "Dependencia de <b>otro módulo del mismo proyecto</b> (clase-05-08), tratado igual que una librería externa."),
      ("</project>", "Cierre."),
     ]},
    SI + "src/main/java/edu/usal/singleton/ConfigSingleton.java": {
     "rol": "Implementación del patrón <b>Singleton</b>: una configuración global de la aplicación (idioma, versión, tema).",
     "defensa": "Cumple las reglas del patrón: atributo estático <i>instancia</i> y método estático <i>getInstance()</i>; <b>synchronized</b> evita que dos hilos creen dos instancias. <b>Observación honesta:</b> el constructor está declarado <i>public</i>; para ser un Singleton estricto debería ser <b>private</b> (regla 1 del propio comentario de la clase), porque con constructor público cualquiera puede hacer <i>new ConfigSingleton()</i> y romper la unicidad.",
     "bloques": [
      ("", "Paquete <i>singleton</i>."),
      ("import java.util.HashMap", "@imports"),
      ("/*", "Comentario de la clase: define el patrón y sus <b>tres reglas</b>: constructor privado, atributo de clase estático y método público estático <i>getInstance()</i>."),
      ("public class ConfigSingleton", "Declara la clase."),
      ("private static ConfigSingleton instancia", "Atributo <b>estático</b>: guarda la única instancia (vale null hasta que se pide la primera vez). Además un <i>flag</i> y un <b>Map</b> de propiedades clave → valor."),
      ("public ConfigSingleton()", "Constructor: crea el mapa y carga tres propiedades por defecto (idioma ES, versión 1.0.0, tema Oscuro). Debería ser privado."),
      ("public static synchronized ConfigSingleton getInstance", "Método de acceso global. <b>static</b>: se llama sobre la clase. <b>synchronized</b>: un hilo a la vez, así no se crean dos instancias. Si <i>instancia</i> es null (primer uso) la crea (<b>inicialización perezosa</b>, lazy) y siempre devuelve la misma."),
      ("/*public Map", "Getter del mapa comentado: se evita exponer la colección interna (encapsulamiento)."),
      ("public void setPropiedades", "Reemplaza todas las propiedades."),
      ("public String getPropiedad", "Lee una propiedad por su clave."),
      ("public void setPropiedad", "Agrega o modifica una propiedad."),
     ]},
    SI + "src/main/java/edu/usal/singleton/PruebaSingleton.java": {
     "rol": "<i>main</i> que demuestra que el Singleton devuelve siempre el mismo objeto.",
     "defensa": "La prueba clásica: pedir la instancia dos veces y comparar referencias con <b>==</b> (no con equals). Si son iguales, es una única instancia.",
     "bloques": [
      ("", "Paquete."),
      ("public class PruebaSingleton", "Clase de prueba."),
      ("public static void main", "Pide la instancia dos veces con <i>ConfigSingleton.getInstance()</i> (nunca con <i>new</i>)."),
      ("if(config1 == config2)", "Compara las <b>referencias</b>: si apuntan al mismo objeto imprime «Instancias Iguales» (con su representación) y si no, «Instancias distintas»."),
     ]},
    BD + "util/MySqlConector.java": {
     "rol": "Fábrica de conexiones a MySQL (igual a la del Tema 01 pero en el paquete <i>util</i>).",
     "defensa": "Ver el Tema 01. Acá la usan los DAO y el servicio. Es el candidato natural a convertirse en <b>Singleton de conexión</b> (la <i>ConexionBD</i> de la guía de estudio): constructor privado, instancia estática y getInstance().",
     "bloques": [
      ("", "Paquete <i>util</i>."),
      ("import java.sql.Connection", "@imports"),
      ("public class MySqlConector", "Clase conectora."),
      ("public static Connection getConnection", "Devuelve una <b>Connection</b> nueva."),
      ("Class.forName", "Carga el driver de MySQL."),
      ("String urlJdbc", "URL, usuario y contraseña de la base."),
      ("connection = DriverManager.getConnection", "Abre la conexión."),
      ("} catch (SQLException e)", "Informa el error."),
      ("return connection", "Devuelve la conexión."),
     ]},
    BD + "domain/Cuenta.java": {
     "rol": "Entidad (POJO) de una <b>cuenta bancaria</b>: número, saldo y cliente.",
     "defensa": "Primera pieza del patrón DAO: una clase de datos sin lógica. Atributos <b>privados</b> con getters/setters (encapsulamiento) y constructor vacío (necesario para crear el objeto y completarlo con setters). Usa los wrappers <i>Integer</i> y <i>Double</i> que admiten null (el id no existe antes de guardarse).",
     "bloques": [
      ("", "Paquete <i>domain</i> (dominio)."),
      ("public class Cuenta", "Atributos privados: número de cuenta, saldo e id del cliente."),
      ("public Cuenta()", "Constructor vacío."),
      ("public Double getSaldo", GET_SET),
     ]},
    BD + "domain/Moviento.java": {
     "rol": "Entidad que registra un <b>movimiento</b> (una transferencia): cuenta origen, cuenta destino y fecha-hora.",
     "defensa": "Sirve de comprobante de cada transferencia. Usa <b>LocalDateTime</b> (API java.time moderna) en lugar de Date. El nombre de la clase tiene un error de tipeo («Moviento»); conviene mencionarlo si se pregunta, se corrige renombrando a Movimiento.",
     "bloques": [
      ("", "Paquete <i>domain</i>."),
      ("import java.time.LocalDateTime", "@imports"),
      ("public class Moviento", "Atributos privados: cuentaOrigen, cuentaDestino (texto) y fechaHora (<b>LocalDateTime</b>)."),
      ("public Moviento()", "Constructor vacío."),
      ("public String getCuentaOrigen", GET_SET),
     ]},
    BD + "exception/NegocioException.java": {
     "rol": "Excepción propia para errores de <b>reglas de negocio</b> (por ejemplo, saldo insuficiente).",
     "defensa": "Extiende <b>RuntimeException</b>: es <i>no controlada</i>, no obliga a usar throws/try. Separa los errores de negocio de los técnicos (SQLException). Está vacía: faltaría agregar un constructor con mensaje (<i>super(mensaje)</i>) para informar la causa.",
     "bloques": [
      ("", "Paquete <i>exception</i>."),
      ("public class NegocioException", "Excepción propia heredando de RuntimeException (sin cuerpo)."),
     ]},
    BD + "dao/CuentaDAO.java": {
     "rol": "<b>Interfaz DAO</b> de las cuentas: el contrato de las operaciones.",
     "defensa": "El contrato no menciona tecnologías (JDBC). Decisión de diseño importante, que se explica en el comentario del código: los métodos que forman parte de una <b>transacción</b> reciben la <i>Connection</i> por parámetro para que todos trabajen sobre la misma; <i>validarSaldo</i> es solo una consulta y no la necesita.",
     "bloques": [
      ("", "Paquete <i>dao</i>."),
      ("import edu.usal", "@imports"),
      ("public interface CuentaDAO", "Interfaz: solo declara métodos, sin código."),
      ("//Connection no se notifica", "Comentario del autor: la conexión no se declara en el contrato <i>funcional</i> pero aquí se pasa como parámetro para compartir la transacción."),
      ("void descontarSaldo", "Resta saldo de una cuenta, usando la conexión recibida (<b>throws SQLException</b>)."),
      ("void incrementarSaldo", "Suma saldo a una cuenta."),
      ("double validarSaldo", "Consulta el saldo de una cuenta; puede lanzar <b>NegocioException</b>."),
     ]},
    BD + "dao/MovimientoDAO.java": {
     "rol": "Interfaz DAO de los movimientos.",
     "defensa": "Un único método que también recibe la conexión: el registro del movimiento forma parte de la misma transacción de la transferencia.",
     "bloques": [
      ("", "Paquete <i>dao</i>."),
      ("import edu.usal", "@imports"),
      ("public interface MovimientoDAO", "Interfaz con el método <b>registrarMovimiento(connection, movimiento)</b>."),
     ]},
    BD + "dao/CuentaDAOImpl.java": {
     "rol": "Implementación <b>JDBC</b> de CuentaDAO con <b>PreparedStatement</b>.",
     "defensa": "Aplica lo aprendido: SQL con <b>?</b>, setXxx y executeUpdate. Los UPDATE usan <b>saldo = saldo ± ?</b>: la suma/resta la hace la base en una sola operación (más seguro que leer, calcular en Java y escribir). <b>Observaciones de mejora que conviene conocer:</b> (1) los métodos no cierran el PreparedStatement; (2) quedan los TODO para validar las filas afectadas; (3) <i>validarSaldo</i> llama a <i>getDouble</i> sin <i>resultSet.next()</i> antes, lo que lanzaría una SQLException (el cursor está antes de la primera fila), y abre su propia conexión sin cerrarla.",
     "bloques": [
      ("", "Paquete <i>dao</i>."),
      ("import edu.usal", "@imports"),
      ("public class CuentaDAOImpl implements CuentaDAO", "Implementa la interfaz. Guarda la conexión y el PreparedStatement como atributos."),
      ("@Override\n    public void descontarSaldo", "<b>@Override</b> indica que se implementa un método de la interfaz."),
      ("public void descontarSaldo", "Resta saldo. Usa la <b>conexión recibida</b> (la de la transacción)."),
      ("String strSQL = \"UPDATE cuentas set saldo = saldo - ?", "SQL con dos comodines: monto y número de cuenta. La resta se hace dentro de la base."),
      ("this.connection = connection", "Guarda la conexión y crea el <b>PreparedStatement</b> a partir del SQL."),
      ("this.pStatement.setDouble(1, cuenta.getSaldo())", "Asigna el monto (en este diseño la «cuenta» lleva el monto a descontar en su saldo) y el número de cuenta."),
      ("int filasAfectadas = this.pStatement.executeUpdate()", "Ejecuta el UPDATE y guarda las filas afectadas; el <b>TODO</b> recuerda que falta validar que haya sido 1 (si la cuenta no existe, no se modifica nada y no se avisa)."),
      ("public void incrementarSaldo", "Igual que el anterior pero <b>suma</b> el monto a la cuenta destino."),
      ("public double validarSaldo", "Consulta el saldo de una cuenta. Esta vez <b>abre su propia conexión</b> (es solo lectura y no forma parte de la transacción)."),
      ("this.pStatement = this.connection.prepareStatement", "Prepara el SELECT, asigna el número de cuenta y ejecuta con <b>executeQuery()</b>."),
      ("return resultSet.getDouble", "Lee el saldo. Falta <i>resultSet.next()</i> antes de leer."),
      ("} catch (SQLException e)", "Convierte la SQLException en una <b>RuntimeException</b> (se «envuelve» para no obligar a capturarla)."),
     ]},
    BD + "dao/MovimientoDAOImpl.java": {
     "rol": "Implementación (vacía) de MovimientoDAO.",
     "defensa": "Quedó como esqueleto: muestra dónde iría el INSERT del movimiento usando la conexión recibida (para que forme parte de la transacción).",
     "bloques": [
      ("", "Paquete <i>dao</i>."),
      ("import edu.usal", "@imports"),
      ("public class MovimientoDAOImpl", "Implementa la interfaz."),
      ("@Override", "Método <b>registrarMovimiento</b> con el cuerpo vacío: pendiente de implementar (INSERT con PreparedStatement sobre la conexión recibida)."),
     ]},
    BD + "services/TransferenciaService.java": {
     "rol": "<b>Capa de servicio</b>: orquesta los DAO y controla la <b>transacción</b> de una transferencia bancaria.",
     "defensa": "Es la clase más importante de la clase: muestra el patrón completo <b>setAutoCommit(false) → operaciones → commit / rollback → close</b>. El servicio abre la conexión y la pasa a cada DAO para que todos trabajen en la misma transacción. Si falla cualquier paso, <i>rollback()</i> deshace todo. <b>Observaciones:</b> es un esqueleto (<i>transferir()</i> sin parámetros, objetos vacíos); el rollback está en el <i>catch</i> pero el cierre de la conexión debería ir en un <b>finally</b>; y la <i>NegocioException</i> se atrapa sin hacer nada (en una versión real habría que abortar la transferencia).",
     "bloques": [
      ("", "Paquete <i>services</i> (servicios)."),
      ("import edu.usal", "@imports"),
      ("public class TransferenciaService", "Atributos: los dos DAO, declarados con el tipo <b>interfaz</b> (se programa contra la interfaz)."),
      ("public TransferenciaService()", "Constructor: crea las implementaciones concretas. Aquí es donde un <b>Factory</b> podría decidir qué implementación entregar."),
      ("public void transferir()", "Método principal. Abre una conexión nueva."),
      ("connection.setAutoCommit(false)", "<b>Inicia la transacción</b>: a partir de acá nada se confirma hasta el commit."),
      ("//1er Paso", "Paso 1: valida el saldo de la cuenta origen (consulta). Si hay <b>NegocioException</b> se capturaría para manejar el error (vacío en el esqueleto)."),
      ("//2do Paso", "Pasos 2, 3 y 4 dentro de un mismo <i>try</i>: descontar a origen, incrementar a destino y registrar el movimiento, todos con <b>la misma conexión</b>. Si todo sale bien, <b>commit()</b> confirma los cambios."),
      ("} catch (SQLException e){", "Si alguno de los pasos falla, <b>rollback()</b> deshace todo lo hecho en la transacción: ninguna cuenta queda modificada."),
      ("connection.close()", "Cierra la conexión (debería estar en un <i>finally</i>)."),
     ]},
   }},
 ],
 "cierre": [
  ("h1", "Resumen para estudiar"),
  ("li", "<b>Singleton</b>: constructor privado + atributo estático + getInstance() (synchronized para hilos). Se verifica con ==."),
  ("li", "<b>DAO</b>: entidad + interfaz + implementación. Factory elige la implementación. El <b>servicio</b> coordina varios DAO."),
  ("li", "<b>Transacción</b>: setAutoCommit(false) → commit() / rollback() → close(); todas las sentencias en la <b>misma Connection</b>."),
  ("li", "<b>Maven</b>: pom padre (packaging pom) + módulos hijos con &lt;parent&gt;; un módulo puede depender de otro."),
  ("li", "<b>NegocioException</b> = RuntimeException (no controlada); SQLException = controlada."),
  ("h1", "Cómo se aplica en el parcial de logística"),
  ("li", "ConexionDB es el Singleton de conexión; DAOFactory/JdbcDAOFactory es el Factory; las interfaces ChoferDAO, CamionDAO, ViajeDAO son los DAO; el proyecto <i>logistica-dao</i> y el proyecto <i>logistica-web</i> son los dos módulos Maven."),
  ("li", "La transacción de alta de viaje y de alta de chofer sigue exactamente este esquema (con rollback y cierre en finally)."),
  ("h1", "Preguntas típicas"),
  ("q", "¿Por qué el constructor del Singleton es privado?"),
  ("p", "Para que nadie pueda crear instancias con <i>new</i>; la única forma de obtener el objeto es getInstance(), que garantiza una sola instancia."),
  ("q", "¿Para qué se pasa la Connection por parámetro a los métodos del DAO?"),
  ("p", "Para que todos los pasos de la transacción usen la misma conexión; si cada método abriera la suya, el commit/rollback no los abarcaría."),
  ("q", "¿Qué pasa si falla el paso 3 de la transferencia?"),
  ("p", "Se lanza una SQLException, se ejecuta rollback() y se deshace el descuento del paso 2: el sistema queda como antes de empezar (atomicidad)."),
 ],
}
