B = "Codigo/017 - Clase 12-08/"

TEMA = {
 "carpeta": "Tema 03 - HTML5 (estructura, formularios y tablas)",
 "titulo": "Tema 03 · HTML5: estructura, formularios y tablas",
 "clases": "Clase 017 (12-08) · Teoría: «HTML» (Clase018-Web.pdf)",
 "intro": [
  ("h1", "1. Qué es HTML"),
  ("p", "<b>HTML (HyperText Markup Language)</b> es un lenguaje de <b>marcas o etiquetas</b> que sirve para <b>estructurar</b> el contenido de una página web (títulos, párrafos, listas, tablas, formularios, imágenes, enlaces). No es un lenguaje de programación (no tiene instrucciones ni lógica): describe qué es cada parte del contenido. Es el <b>navegador</b> (browser) el que lo interpreta y lo dibuja, y el que resuelve los hipervínculos."),
  ("p", "El documento se guarda con extensión <b>.html</b>. Para ver el HTML de cualquier página: botón derecho → «Ver código fuente»."),
  ("h1", "2. Etiquetas, elementos y atributos"),
  ("li", "<b>Etiqueta (tag)</b>: una palabra clave entre &lt; &gt;. Suelen ir de a pares: apertura <i>&lt;p&gt;</i> y cierre <i>&lt;/p&gt;</i>. Algunas no tienen cierre (<i>&lt;br&gt;</i>, <i>&lt;hr&gt;</i>, <i>&lt;img&gt;</i>, <i>&lt;input&gt;</i>)."),
  ("li", "<b>Elemento</b>: el par completo apertura + contenido + cierre."),
  ("li", "<b>Atributo</b>: información adicional dentro de la etiqueta de apertura, con la forma clave=«valor». Ejemplo: <i>&lt;html lang=\"es\"&gt;</i>."),
  ("li", "Las etiquetas pueden <b>anidarse</b> (un elemento dentro de otro) y no distinguen mayúsculas de minúsculas."),
  ("h1", "3. Estructura de un documento HTML5"),
  ("codigo", "<!DOCTYPE html>          <- declara que es HTML5\n<html lang=\"es\">          <- raíz del documento\n  <head>                   <- cabecera: no se ve, es información de la página\n    <meta charset=\"UTF-8\"> <- codificación (tildes y eñes)\n    <title>Mi página</title> <- título de la pestaña\n  </head>\n  <body>                   <- cuerpo: lo que se ve en pantalla\n    <p>Hola</p>\n  </body>\n</html>"),
  ("p", "En el <b>head</b> van <i>title, meta, link</i> (CSS), <i>script</i>. En el <b>body</b> va todo el contenido visible."),
  ("h1", "4. Etiquetas semánticas de HTML5"),
  ("p", "HTML5 agregó etiquetas que <b>dan significado</b> a cada zona de la página (mejoran la accesibilidad y el orden del código):"),
  ("tabla", [["Etiqueta", "Significado"],
    ["&lt;header&gt;", "Cabecera de la página o de una sección (títulos, logo)"], ["&lt;nav&gt;", "Barra de navegación (menú)"],
    ["&lt;main&gt;", "Contenido principal (uno por página)"], ["&lt;section&gt;", "Sección temática dentro del contenido"],
    ["&lt;aside&gt;", "Barra lateral o contenido complementario"], ["&lt;footer&gt;", "Pie de página (derechos, contacto)"]]),
  ("h1", "5. Etiquetas más usadas"),
  ("tabla", [["Para qué", "Etiquetas"],
    ["Títulos y texto", "&lt;h1&gt;…&lt;h6&gt; (títulos), &lt;p&gt; (párrafo), &lt;br&gt; (salto de línea), &lt;hr&gt; (línea horizontal), &lt;b&gt;/&lt;strong&gt; (negrita), &lt;i&gt;/&lt;em&gt; (cursiva)"],
    ["Contenedores", "&lt;div&gt; (bloque) y &lt;span&gt; (en línea)"],
    ["Enlaces e imágenes", "&lt;a href=\"url\"&gt;texto&lt;/a&gt; ; &lt;img src=\"foto.jpg\" alt=\"descripción\"&gt;"],
    ["Listas", "&lt;ul&gt; (desordenada, viñetas), &lt;ol&gt; (ordenada, números), &lt;li&gt; (cada ítem), &lt;dl&gt;/&lt;dt&gt;/&lt;dd&gt; (definiciones)"],
    ["Tablas", "&lt;table&gt;, &lt;thead&gt; (encabezado), &lt;tbody&gt; (cuerpo), &lt;tr&gt; (fila), &lt;th&gt; (celda de título), &lt;td&gt; (celda de datos); colspan junta columnas"],
    ["Formularios", "&lt;form&gt;, &lt;input&gt;, &lt;select&gt;/&lt;option&gt;, &lt;textarea&gt;, &lt;button&gt;, &lt;label&gt;"]]),
  ("h1", "6. Formularios"),
  ("p", "Un <b>formulario</b> (&lt;form&gt;) agrupa campos para que el usuario ingrese datos y los envíe a un programa en el servidor (un servlet o JSP). Atributos del form: <b>action</b> (a qué URL se envía) y <b>method</b> (<b>GET</b> o <b>POST</b>). Cada campo queda asociado a una variable mediante su atributo <b>name</b> (lo que luego se lee con <i>request.getParameter(\"name\")</i>)."),
  ("h2", "Tipos de &lt;input&gt;"),
  ("tabla", [["type", "Qué muestra"],
    ["text", "Texto de una línea"], ["password", "Texto oculto (puntos)"], ["email", "Texto validado como email (HTML5)"],
    ["number", "Número (con flechas, min, max, step) (HTML5)"], ["date", "Selector de fecha (HTML5)"],
    ["radio", "Opción única dentro de un grupo (todos comparten el mismo name)"], ["checkbox", "Casilla de tildar (varias a la vez)"],
    ["submit", "Botón que envía el formulario"], ["reset", "Botón que limpia el formulario"], ["button", "Botón genérico (se programa con JavaScript)"]]),
  ("h2", "Validaciones de HTML5"),
  ("li", "<b>required</b>: el formulario no se envía si el campo está vacío."),
  ("li", "<b>placeholder</b>: texto de ayuda gris dentro del campo."),
  ("li", "<b>pattern</b>: expresión regular que el valor debe cumplir."),
  ("li", "<b>min / max / step</b>: rango y salto de los números."),
  ("li", "Todo formulario HTML5 se valida solo, salvo que se agregue <i>novalidate</i> al form (o <i>formnovalidate</i> al botón)."),
  ("nota", "<b>Importante para el parcial:</b> las validaciones del navegador (HTML y JavaScript) son una <b>ayuda al usuario</b>, no seguridad: cualquiera puede saltearlas. Siempre se debe validar también en el <b>servidor</b> (Servlet/DAO)."),
  ("p", "<b>label for / input id:</b> el atributo <i>for</i> de una etiqueta &lt;label&gt; debe coincidir con el <i>id</i> del campo: al hacer clic en el texto se activa el campo (accesibilidad)."),
 ],
 "clases_detalle": [
  {"titulo": "Clase 017 – 12-08: HTML5 de un sistema de gestión bancaria",
   "resumen": [("p", "Se construye una página HTML5 con estructura semántica que contiene un <b>formulario de alta de clientes</b> (con distintos tipos de campos) y una <b>tabla de clientes</b>. No hay JavaScript ni servidor: se abre directamente en el navegador. El proyecto Maven (<i>pom.xml</i>) es solo un contenedor básico.")],
   "archivos": {
    B + "pom.xml": {
     "rol": "POM mínimo de Maven: solo coordenadas del proyecto y versión de Java.",
     "defensa": "Esta clase es solo HTML, no necesita dependencias. Sirve para que el IDE trate la carpeta como proyecto Maven (los archivos web van en <i>src/main/resources</i>).",
     "bloques": [
      ("", "Cabecera del POM."),
      ("<groupId>edu.usal", "Coordenadas: grupo <b>edu.usal</b>, artefacto <b>clase-12-08</b>, versión 1.0-SNAPSHOT."),
      ("<properties>", "Java 11 y codificación UTF-8."),
      ("</project>", "Cierre."),
     ]},
    B + "src/main/resources/index.html": {
     "rol": "Página HTML5 del módulo «Sistema de Gestión Bancaria»: encabezado, menú, formulario de registro de clientes y tabla de listado.",
     "defensa": "Es un ejemplo completo de <b>etiquetas semánticas</b> (header, nav, main, section, footer), <b>formulario con todos los tipos de campo</b> y <b>tabla con thead/tbody</b>. Si en el parcial hay que armar un formulario, esta página es el modelo. Se pueden señalar mejoras: asociar cada <i>&lt;label&gt;</i> con su <i>id</i> (solo el primero lo hace), agregar <i>name</i> a los campos (sin <i>name</i> no se envían al servidor) y un <i>action</i>/<i>method</i> al form.",
     "bloques": [
      ("", "<b>&lt;!DOCTYPE html&gt;</b> declara HTML5; la raíz <b>&lt;html lang=\"en\"&gt;</b> indica el idioma (conviene «es»)."),
      ("<head>", "Cabecera: <b>meta charset UTF-8</b> (tildes y eñes) y <b>title</b> (texto de la pestaña del navegador)."),
      ("<body>", "Inicio del cuerpo, la parte visible."),
      ("<!--Etiqueta HTML5", "Comentario HTML (no se muestra). Luego <b>&lt;header&gt;</b>: cabecera con el título <b>h1</b> (el principal) y un párrafo <b>p</b> descriptivo."),
      ("<nav>", "<b>&lt;nav&gt;</b> con una <b>lista desordenada &lt;ul&gt;</b> de ítems <b>&lt;li&gt;</b>: es el menú (Inicio, Clientes, Cuentas). Se verá con viñetas."),
      ("<main>", "<b>&lt;main&gt;</b>: contenido principal. Dentro, una <b>&lt;section&gt;</b> con el título de nivel 2 «Registro de nuevos clientes»."),
      ("<form>", "Abre el <b>formulario</b>. Cada pregunta está en un <b>&lt;div&gt;</b> (contenedor de bloque) con su <b>&lt;label&gt;</b> (texto descriptivo)."),
      ("<label for=\"nombre\">", "Campo <b>Nombre</b>: <i>label for=\"nombre\"</i> está asociado al input con <i>id=\"nombre\"</i> (al hacer clic en el texto se activa el campo). <i>type=\"text\"</i>, <i>placeholder</i> con un ejemplo y <b>required</b> (obligatorio)."),
      ("<label>Email", "Campo <b>email</b>: <i>type=\"email\"</i> hace que el navegador verifique el formato (debe tener @) al enviar."),
      ("<label>Password", "Campo <b>password</b>: lo escrito se oculta con puntos."),
      ("<label>Numero Tel", "Campo <b>number</b>: solo admite números."),
      ("<label>Fecha Nacimiento", "Campo <b>date</b>: muestra un calendario."),
      ("<label>Tipo de cuenta", "Lista desplegable <b>&lt;select&gt;</b> con opciones <b>&lt;option&gt;</b>; el atributo <i>value</i> es lo que se envía, y el texto interno lo que se ve."),
      ("<label>Estado civil", "Botones de opción <b>radio</b>: comparten el mismo <i>name=\"estadoCivil\"</i>, por eso solo se puede elegir uno."),
      ("<input type=\"checkbox\">", "Casilla <b>checkbox</b> «Acepto términos y condiciones»."),
      ("<button type=\"submit\">", "Botón <b>submit</b> (envía el formulario) y botón <b>reset</b> (borra todos los campos)."),
      ("</form>", "Cierra el formulario y la sección. <b>&lt;hr&gt;</b> dibuja una línea horizontal separadora."),
      ("<h2>Listado de clientes", "Segunda <b>&lt;section&gt;</b>: título y comentario HTML."),
      ("<table border=\"1\">", "<b>&lt;table&gt;</b> con borde. <b>&lt;thead&gt;</b> es el encabezado: una fila <b>&lt;tr&gt;</b> con celdas de título <b>&lt;th&gt;</b> (ID y Cliente)."),
      ("<tbody>", "<b>&lt;tbody&gt;</b>: el cuerpo con dos filas <b>&lt;tr&gt;</b> de celdas de datos <b>&lt;td&gt;</b> (101 María Gómez, 102 Carlos Rodríguez)."),
      ("<footer>", "<b>&lt;footer&gt;</b>: pie de página con el símbolo © escrito con la <b>entidad HTML &amp;copy;</b>. Cierra body y html."),
     ]},
   }},
 ],
 "cierre": [
  ("h1", "Resumen para estudiar"),
  ("li", "HTML estructura el contenido con etiquetas (par apertura/cierre) y atributos clave=valor."),
  ("li", "Documento: DOCTYPE → html → head (title, meta) + body."),
  ("li", "Semánticas HTML5: header, nav, main, section, aside, footer."),
  ("li", "Formularios: form (action, method) + inputs con <b>name</b>; tipos text, password, email, number, date, radio, checkbox, submit, reset; select/option; textarea."),
  ("li", "Validación HTML5: required, placeholder, pattern, min/max. Siempre validar también en el servidor."),
  ("li", "Tablas: table → thead/tbody → tr → th/td."),
  ("h1", "Preguntas típicas"),
  ("q", "¿Qué diferencia hay entre método GET y POST en un formulario?"),
  ("p", "GET manda los datos en la URL (visibles, para consultas); POST los manda en el cuerpo de la petición (para formularios que modifican datos, como altas o login)."),
  ("q", "¿Para qué sirve el atributo name de un input?"),
  ("p", "Es el nombre de la variable con que viaja el dato al servidor; sin name el campo no se envía. En el servidor se lee con request.getParameter(\"name\")."),
  ("q", "¿Para qué sirven las etiquetas semánticas?"),
  ("p", "Dan significado a cada zona de la página: ordenan el código, mejoran la accesibilidad y el posicionamiento en buscadores."),
 ],
}
