B = "Codigo/018 - Clase 19-08/"
R = B + "src/main/resources/"

TEMA = {
 "carpeta": "Tema 04 - JavaScript y manejo del DOM",
 "titulo": "Tema 04 · JavaScript y manejo del DOM",
 "clases": "Clase 018 (19-08) · Teoría: «JavaScript» (Clase019-JS-WebServer.pdf)",
 "intro": [
  ("h1", "1. Qué es JavaScript"),
  ("p", "<b>JavaScript (JS)</b> es un lenguaje de programación <b>interpretado</b> que se ejecuta <b>en el navegador del cliente</b> (no en el servidor). Se usa para validar datos, reaccionar a acciones del usuario (clics, escritura) y modificar la página sin recargarla. Es <b>débilmente tipado</b> (las variables no declaran tipo) y, pese al nombre, es distinto de Java aunque la sintaxis se parezca. Es independiente de la plataforma."),
  ("p", "<b>Cómo se integra con HTML</b>: (a) como archivo externo <i>&lt;script src=\"logica.js\"&gt;&lt;/script&gt;</i> (recomendado), o (b) código dentro de la etiqueta <i>&lt;script&gt;…&lt;/script&gt;</i>. Se suele poner al final del body para que el HTML ya exista cuando el script lo busque."),
  ("h1", "2. Lo básico del lenguaje"),
  ("tabla", [["Tema", "Detalle"],
    ["Variables", "<b>var</b> (antigua, alcance de función), <b>let</b> (alcance de bloque, se puede reasignar), <b>const</b> (constante, no se reasigna). Hoy se usan let y const."],
    ["Tipos", "number, string, boolean, null, undefined, object, function; arrays; conversión automática."],
    ["Operadores", "Aritméticos + - * / %, comparación <b>==</b> (compara valor) y <b>===</b> (compara valor y tipo, preferido), lógicos &amp;&amp; || !"],
    ["Condicionales y ciclos", "if/else, switch, ternario (cond ? a : b), for, while, do…while, for…in, break/continue"],
    ["Funciones", "<i>function nombre(a, b) { return a + b; }</i> — sin declarar tipos; también funciones anónimas y <b>flecha</b> <i>(x) =&gt; x * 2</i>"],
    ["Mensajes", "<b>alert(\"texto\")</b> (ventana), <b>confirm()</b> (aceptar/cancelar), <b>prompt()</b> (pide un dato), <b>console.log()</b> (consola del navegador, F12)"],
    ["Arrays", "<i>let a = [1, 'x', true]</i>; a.length, push, map, join, sort, reverse…"]]),
  ("h1", "3. Eventos"),
  ("p", "JavaScript funciona por <b>eventos</b> (igual que Swing en Java): una <i>fuente</i> (botón, campo) genera un evento (click, submit, change…) y un <i>escuchador</i> (listener) lo atiende. Dos formas:"),
  ("li", "En el HTML: <i>&lt;button onclick=\"hacerClic()\"&gt;</i> (simple, pero mezcla HTML con JS)."),
  ("li", "En el JS: <i>elemento.addEventListener(\"click\", function() { ... })</i> (separa responsabilidades, es la forma moderna)."),
  ("p", "Eventos frecuentes: <b>click</b>, <b>submit</b> (al enviar un formulario), <b>change</b>, <b>focus/blur</b>, <b>load</b> (al cargar la página), <b>keyup/keydown</b>."),
  ("h1", "4. El DOM (Document Object Model)"),
  ("p", "Cuando el navegador carga el HTML construye un <b>árbol de objetos</b> llamado <b>DOM</b>: cada etiqueta es un nodo. JavaScript puede leer y modificar ese árbol. Los objetos principales son <b>window</b> (la ventana, raíz de todo), <b>document</b> (la página), <b>location</b> (la URL) e <b>history</b>. Operaciones habituales:"),
  ("tabla", [["Qué quiero hacer", "Cómo"],
    ["Buscar un elemento por su id", "<i>document.getElementById(\"campoNombre\")</i>"],
    ["Leer lo que escribió el usuario", "<i>input.value</i>"],
    ["Cambiar el texto de un elemento", "<i>elemento.textContent = \"Hola\"</i> (seguro) o <i>innerHTML</i> (interpreta HTML: cuidado con XSS)"],
    ["Cambiar estilos", "<i>elemento.style.color = \"red\"</i>"],
    ["Vaciar un campo", "<i>input.value = \"\"</i>"],
    ["Evitar el comportamiento por defecto", "<i>event.preventDefault()</i> (por ejemplo, impedir que el formulario se envíe)"]]),
  ("h1", "5. Validación en el cliente"),
  ("p", "JavaScript permite validar un formulario <b>antes de enviarlo</b>: se escucha el evento <b>submit</b>, se revisan los campos y, si hay errores, se llama a <i>event.preventDefault()</i> y se muestran los mensajes. Da una respuesta inmediata al usuario y ahorra viajes al servidor."),
  ("nota", "<b>Recordar:</b> la validación en el navegador <b>no reemplaza</b> a la del servidor, porque el usuario puede desactivar JS o enviar peticiones manuales. Es solo mejora de experiencia (UX)."),
  ("h1", "6. Bootstrap"),
  ("p", "<b>Bootstrap</b> es un framework de CSS/JS que da estilos listos (botones, formularios, tablas, grillas, tarjetas) y diseño <b>responsive</b> (se adapta a celular y escritorio). Se incluye con una etiqueta &lt;link&gt; a un CDN en el head. Clases usadas en esta clase: <i>container</i> (centra el contenido), <i>mb-3</i> (margen abajo), <i>form-label</i>, <i>form-control</i> (campos de texto), <i>form-select</i> (listas), <i>btn btn-primary</i> (botón azul), <i>text-center</i>."),
 ],
 "clases_detalle": [
  {"titulo": "Clase 018 – 19-08: JavaScript, DOM y validación de un formulario de transferencia",
   "resumen": [("p", "Hay dos prácticas: (1) <b>index.html + logica.js</b>: variables, botón con <i>onclick</i> y manejo del DOM (saludar al usuario); (2) <b>transferencia.html + transferencia-logica.js</b>: formulario de transferencia bancaria con <b>Bootstrap</b> y <b>validación del lado del cliente</b> que muestra los errores en pantalla.")],
   "archivos": {
    B + "pom.xml": {
     "rol": "POM mínimo del proyecto (sin dependencias).",
     "defensa": "La clase es solo HTML y JavaScript: los archivos van en <i>src/main/resources</i>.",
     "bloques": [
      ("", "Cabecera."),
      ("<groupId>edu.usal", "Coordenadas: <b>clase-19-08</b>."),
      ("<properties>", "Java 11 y UTF-8."),
      ("</project>", "Cierre."),
     ]},
    R + "index.html": {
     "rol": "Página de práctica del DOM: un botón con evento <i>onclick</i> y un campo para escribir el nombre y recibir un saludo.",
     "defensa": "Muestra las <b>dos formas de asociar eventos</b>: atributo <i>onclick</i> en el HTML (botón «Hacer Clic») y listener en el archivo JS (botón «Saludar», identificado con un <i>id</i>). Los <i>id</i> son los «ganchos» con los que el JS encuentra los elementos. El script va al final del body para que los elementos ya existan.",
     "bloques": [
      ("", "DOCTYPE HTML5, raíz html, head con charset y title."),
      ("<body>", "Inicio del cuerpo. Un comentario HTML y la cabecera <b>&lt;header&gt;</b> con el título."),
      ("<main>", "Contenido principal. El primer botón tiene <b>onclick=\"hacerClic()\"</b>: al hacer clic ejecuta la función JS <i>hacerClic</i>. <i>&lt;br&gt;</i> hace un salto de línea y luego un título «Manejo del DOM con JS»."),
      ("<div>", "Bloque con el <b>label</b> (observar la errata <i>for=\"campoNombre\"l</i>: hay una «l» de más), el <b>input de texto</b> con <i>id=\"campoNombre\"</i> y el botón <i>id=\"btnSaludar\"</i>. Esos <b>id</b> los usa el JS."),
      ("<hr>", "Línea separadora y un párrafo vacío <b>&lt;p id=\"msjSaludo\"&gt;</b>: es el lugar donde JS escribirá el saludo."),
      ("<script src=\"logica.js\">", "Carga el archivo JavaScript externo <b>logica.js</b>, al final para que el DOM ya esté construido. Cierra main, body y html."),
     ]},
    R + "logica.js": {
     "rol": "Lógica JavaScript de la página: declaración de variables, función de un botón y manejo del DOM con un <i>listener</i>.",
     "defensa": "Los pasos del manejo del DOM que hay que saber: <b>(1)</b> obtener los elementos con <i>getElementById</i>; <b>(2)</b> registrar un listener con <i>addEventListener</i>; <b>(3)</b> leer <i>value</i>; <b>(4)</b> validar; <b>(5)</b> modificar el DOM con <i>textContent</i> y <i>style</i>. Se usa <b>textContent</b> y no innerHTML para escribir el nombre: así lo que escriba el usuario nunca se interpreta como HTML (evita XSS).",
     "bloques": [
      ("", "<b>alert()</b> muestra una ventana emergente al cargar el archivo y <b>console.log()</b> escribe en la consola del navegador (F12)."),
      ("var identificarVar", "Tres formas de declarar variables: <b>var</b> (antigua), <b>let</b> (variable de bloque reasignable) y <b>const</b> (constante, por convención en MAYÚSCULAS). No se declara el tipo."),
      ("/*", "Código comentado: un array con tipos mezclados (texto, número, booleano, null, undefined) y un <i>for</i> para recorrerlo. Tiene un error: la condición del for es <i>arreglo.length</i> en lugar de <i>i &lt; arreglo.length</i>."),
      ("function hacerClic", "Función invocada desde el atributo <i>onclick</i> del primer botón: muestra una alerta."),
      ("const inputNombre", "<b>Selecciona elementos del DOM</b> por su id y los guarda en constantes: el campo de nombre, el botón y el párrafo del saludo."),
      ("buttonSaludar.addEventListener", "Registra un <b>escuchador del evento click</b> en el botón Saludar: la función anónima se ejecuta cada vez que se hace clic."),
      ("let nombreIngresado", "Lee el texto del campo con <i>.value</i>."),
      ("if(nombreIngresado.trim()", "<b>Validación</b>: <i>trim()</i> quita espacios; si queda vacío muestra una alerta pidiendo el nombre."),
      ("} else {", "Si hay nombre: escribe el saludo en el párrafo con <b>textContent</b>, le pone color rojo con <b>style.color</b> y <b>limpia</b> el campo (<i>value = ''</i>)."),
     ]},
    R + "transferencia.html": {
     "rol": "Formulario de «Nueva transferencia» con estilos de <b>Bootstrap</b>.",
     "defensa": "Combina HTML + Bootstrap + JS: el diseño lo da Bootstrap (clases) y el comportamiento lo da <i>transferencia-logica.js</i>. Faltan <i>action</i>/<i>method</i> y <i>name</i> en los campos: es un ejemplo para practicar validación del lado del cliente, no un envío real al servidor. El <b>div#msjErrores</b> está vacío a propósito: el JS lo completa.",
     "bloques": [
      ("", "DOCTYPE y head: <b>meta charset</b>."),
      ("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap", "Carga la hoja de estilos de <b>Bootstrap 5.3.8</b> desde un CDN (red de distribución). El atributo <i>integrity</i> verifica que el archivo no fue alterado y <i>crossorigin</i> habilita esa verificación."),
      ("<title>", "Título de la pestaña."),
      ("<body>", "Inicio del cuerpo."),
      ("<div class=\"container\">", "<b>container</b>: contenedor centrado de Bootstrap. Título <b>h1</b> con <i>mb-3</i> (margen inferior) y <i>text-center</i>."),
      ("<form id=\"formTransferencia\">", "Formulario con <b>id</b> para que el JS lo encuentre."),
      ("<label class=\"form-label\" for=\"cbuDestino\">", "Campo <b>CBU destino</b>: texto con <i>form-control</i> (estilo Bootstrap). Cada bloque está en un <i>div class=\"mb-3\"</i>."),
      ("<label class=\"form-label\">Monto", "Campo <b>monto</b>: <i>type=\"number\"</i>, <i>step=\"0.01\"</i> permite centavos, con <i>placeholder</i>."),
      ("<label class=\"form-label\">Motivo", "<b>Lista desplegable</b> (<i>form-select</i>) con una opción inicial «Seleccione Motivo» de valor «-» (la que el JS toma como «no eligió»)."),
      ("<button type=\"submit\"", "Botón <b>submit</b> azul (<i>btn btn-primary</i>) que dispara el evento <b>submit</b> del formulario."),
      ("<div id=\"msjErrores\">", "Div vacío donde el JS mostrará los errores."),
      ("<script src=\"transferencia-logica.js\">", "Carga el archivo de lógica al final del body."),
     ]},
    R + "transferencia-logica.js": {
     "rol": "Validación del formulario de transferencia del lado del cliente.",
     "defensa": "Patrón clásico de validación: <b>acumular errores en un arreglo</b>; si hay errores, <b>preventDefault()</b> cancela el envío y se los muestra; si no, se limpia el mensaje y el formulario se envía. <b>Para el parcial:</b> esta validación mejora la experiencia, pero el servidor debe repetirla. Nota de seguridad: aquí los mensajes son fijos y se arman con <i>innerHTML</i>; si incluyeran texto del usuario habría que usar <i>textContent</i> para evitar XSS.",
     "bloques": [
      ("", "Obtiene el <b>div de errores</b> y el <b>formulario</b> del DOM por su id."),
      ("formulario.addEventListener", "<b>Listener del evento submit</b>: se ejecuta cuando el usuario intenta enviar el formulario. El parámetro <i>event</i> permite cancelarlo. Crea el arreglo vacío <b>errores</b>."),
      ("let inputCbu", "Lee los tres campos: el CBU (texto sin espacios con <i>trim()</i>), el monto (convertido a número con <b>parseFloat</b>) y el valor elegido en el combo."),
      ("if(inputCbu === \"\")", "<b>Validación del CBU</b>: si está vacío agrega «obligatorio»; si no, con <b>isNaN</b> comprueba que sean números; los mensajes se agregan con <b>push</b>."),
      ("if(isNaN(inputMonto)", "<b>Validación del monto</b>: debe ser un número mayor que 0 (si el campo está vacío <i>parseFloat</i> devuelve NaN)."),
      ("if(comboMotivo === \"-\")", "<b>Validación del motivo</b>: no se puede dejar la opción inicial."),
      ("if(errores.length > 0)", "Si hay errores: <b>event.preventDefault()</b> <b>cancela el envío</b> y muestra una lista &lt;ul&gt; con un &lt;li&gt; por error (con <b>map</b> se transforma cada texto en un li y con <b>join('')</b> se unen). Usa <i>template literals</i> (comillas invertidas) para insertar <i>${err}</i>."),
      ("} else {", "Si no hay errores, vacía el div y deja que el formulario se envíe."),
     ]},
   }},
 ],
 "cierre": [
  ("h1", "Resumen para estudiar"),
  ("li", "JS corre en el <b>cliente</b>; manipula el <b>DOM</b> y reacciona a <b>eventos</b>."),
  ("li", "Declarar con let/const; comparar con ===; funciones con function o flecha."),
  ("li", "Recetas: <i>getElementById</i> → <i>addEventListener</i> → <i>.value</i> → validar → <i>textContent</i>/<i>style</i>."),
  ("li", "Validar un formulario: escuchar <b>submit</b>, acumular errores, <b>preventDefault()</b> si hay errores."),
  ("li", "Bootstrap: link CDN + clases (container, form-control, btn btn-primary, mb-3)."),
  ("h1", "Preguntas típicas"),
  ("q", "¿Qué diferencia hay entre var, let y const?"),
  ("p", "var tiene alcance de función y es antigua; let tiene alcance de bloque y se puede reasignar; const no se puede reasignar."),
  ("q", "¿Para qué sirve event.preventDefault()?"),
  ("p", "Cancela la acción por defecto del evento; en un submit impide que el formulario se envíe al servidor, permitiendo mostrar los errores primero."),
  ("q", "¿Es suficiente validar con JavaScript?"),
  ("p", "No. Es una mejora de experiencia; la validación obligatoria se hace en el servidor porque el cliente puede ser manipulado."),
 ],
}
