from comunes import pom_war, webxml

B = "Codigo/019 - Clase 26-08/"
W = B + "src/main/webapp/"

TEMA = {
 "carpeta": "Tema 05 - Servidor web y JSP basico (scriptlets y formularios)",
 "titulo": "Tema 05 · Servidor web y JSP básico (scriptlets y formularios)",
 "clases": "Clase 019 (26-08) · Teoría: «Web Server» (Clase019-JS-WebServer.pdf) y «JSP» (Clase020_jsp.pdf)",
 "intro": [
  ("h1", "1. El servidor web y el protocolo HTTP"),
  ("p", "Un <b>servidor web</b> es un programa que implementa el protocolo <b>HTTP</b> (HyperText Transfer Protocol) y está siempre escuchando peticiones de los clientes (navegadores). El navegador pide un recurso, el servidor responde con el contenido (HTML, imagen, JSON…). La palabra «servidor» designa tanto al programa como a la máquina donde corre. Ejemplos: Apache HTTP, Nginx, IIS y, para Java, <b>Apache Tomcat</b> (un <i>contenedor web</i> de Servlets/JSP)."),
  ("h2", "Mensajes HTTP"),
  ("tabla", [["Mensaje", "Partes"],
    ["<b>Petición (request)</b>", "1) línea inicial con el <b>método</b> (GET, POST…) y la URL; 2) cabeceras (pares clave/valor); 3) cuerpo (parámetros o archivos que se envían)"],
    ["<b>Respuesta (response)</b>", "1) línea inicial con el <b>código de estado</b>; 2) cabeceras (Content-Type, Set-Cookie…); 3) cuerpo (el HTML u otro contenido)"]]),
  ("h2", "Métodos HTTP"),
  ("tabla", [["Método", "Para qué", "Notas"],
    ["<b>GET</b>", "Leer un recurso", "Solo consulta; los parámetros viajan en la URL; se puede repetir sin efectos"],
    ["<b>POST</b>", "Enviar datos que crean o modifican algo", "Los datos viajan en el cuerpo; típico de formularios, altas y login"],
    ["PUT", "Actualizar (o crear) un recurso", "No se usa desde formularios HTML"],
    ["DELETE", "Eliminar un recurso", "Idem"]]),
  ("h2", "Códigos de estado"),
  ("tabla", [["Rango", "Significado", "Ejemplos"],
    ["1xx", "Informativo", "100 Continue"], ["2xx", "Éxito", "<b>200 OK</b>, 201 Created"],
    ["3xx", "Redirección", "<b>302 Found</b> (sendRedirect)"], ["4xx", "Error del cliente", "400 Bad Request, 403 Forbidden, <b>404 Not Found</b>"],
    ["5xx", "Error del servidor", "<b>500 Internal Server Error</b>"]]),
  ("h1", "2. JSP: Java Server Pages"),
  ("p", "<b>JSP</b> es una tecnología <b>del lado del servidor</b> para generar páginas web dinámicas. Un archivo <i>.jsp</i> es HTML con código Java embebido. Cuando el usuario lo pide, el servidor <b>ejecuta el Java</b> y devuelve al navegador solo el <b>HTML resultante</b> (el cliente nunca ve el código Java). Los .jsp se ubican en la raíz del proyecto web, al mismo nivel que la carpeta <b>WEB-INF</b> (lo que está dentro de WEB-INF no es accesible directamente desde el navegador)."),
  ("p", "<b>Cómo funciona por dentro:</b> la primera vez que se pide, Tomcat <b>traduce</b> el JSP a una clase Servlet Java, la compila y la ejecuta; las siguientes veces reutiliza la clase compilada. Es decir: <b>un JSP es un servlet disfrazado</b>."),
  ("h2", "Los tres tipos de código JSP"),
  ("tabla", [["Tipo", "Sintaxis", "Para qué"],
    ["<b>Expresión</b>", "&lt;%= expresión %&gt;", "Una sola expresión Java cuyo resultado se <b>imprime</b> en la página"],
    ["<b>Scriptlet</b>", "&lt;% varias líneas de Java %&gt;", "Bloques de código: variables, if, for…"],
    ["<b>Declaración</b>", "&lt;%! declaración %&gt;", "Declarar variables o métodos de la clase generada"],
    ["Directiva", "&lt;%@ page … %&gt;", "Configuración de la página: import, contentType (codificación), etc."],
    ["Comentario JSP", "&lt;%-- … --%&gt;", "No llega al navegador (a diferencia del comentario HTML &lt;!-- --&gt;, que sí se envía)"]]),
  ("nota", "<b>Buena práctica:</b> poner mucho código Java dentro del JSP es una mala práctica (mezcla presentación con lógica). Por eso más adelante se reemplazan los scriptlets por <b>JSTL</b> y la lógica se lleva a clases Java (servlets, DAO) — Temas 07 y 08. El parcial <b>pide JSTL</b>."),
  ("h2", "Objetos implícitos"),
  ("p", "En un JSP existen variables ya creadas por el contenedor, que se usan sin declararlas:"),
  ("tabla", [["Objeto", "Corresponde a", "Uso típico"],
    ["<b>request</b>", "HttpServletRequest", "Leer los datos del formulario: <i>request.getParameter(\"nombre\")</i>"],
    ["<b>response</b>", "HttpServletResponse", "Enviar cookies, redirigir: <i>response.sendRedirect(\"x.jsp\")</i>"],
    ["<b>out</b>", "PrintWriter (JspWriter)", "Escribir en la respuesta: <i>out.println(\"…\")</i>"],
    ["<b>session</b>", "HttpSession", "Guardar datos del usuario entre pantallas (Tema 06)"],
    ["application", "ServletContext", "Datos compartidos por toda la aplicación"],
    ["config / pageContext", "ServletConfig / PageContext", "Configuración y acceso a los demás objetos"]]),
  ("h1", "3. Formularios: del HTML al JSP"),
  ("p", "El flujo básico de la web dinámica: el usuario completa un formulario HTML (<i>formulario.html</i>) → al enviar, el navegador manda una petición POST a la URL de <i>action</i> (<i>procesar-form.jsp</i>) con cada campo identificado por su <b>name</b> → el JSP lee los valores con <b>request.getParameter(\"name\")</b> (que siempre devuelve <b>String</b>; hay que convertirlo con <i>Integer.parseInt</i> si es un número) → genera la respuesta HTML."),
  ("h1", "4. Maven y despliegue"),
  ("p", "El proyecto es de tipo <b>war</b> (Web ARchive). Se construye con <i>mvn package</i> y el archivo .war se copia a la carpeta <i>webapps</i> de Tomcat (o se ejecuta desde el IDE). Estructura estándar: <i>src/main/java</i> (clases Java), <i>src/main/webapp</i> (JSP, HTML, CSS, JS) y <i>src/main/webapp/WEB-INF</i> (web.xml, JSP privados). La URL queda <i>http://localhost:8080/NOMBRE_DEL_WAR/pagina.jsp</i>."),
 ],
 "clases_detalle": [
  {"titulo": "Clase 019 – 26-08: primer JSP con scriptlets y procesamiento de un formulario",
   "resumen": [("p", "Se crea una aplicación web Maven (<b>war</b>) con tres páginas: <b>index.jsp</b> (saludo según la hora del servidor, con scriptlets y expresiones), <b>formulario.html</b> (formulario estático de nombre y edad) y <b>procesar-form.jsp</b> (lee los datos del formulario y dice si es mayor de edad).")],
   "archivos": {
    B + "pom.xml": pom_war("clase-26-08"),
    W + "WEB-INF/web.xml": webxml(),
    W + "index.jsp": {
     "rol": "Página JSP que muestra un saludo («Buenos días / tardes / noches») y la hora del servidor, con un color distinto según el momento del día.",
     "defensa": "Demuestra los elementos de JSP: <b>directivas</b> (<i>page import</i>), <b>scriptlet</b> con lógica, <b>expresiones</b> para imprimir variables y los dos <b>comentarios</b> (JSP vs HTML). Importante: la hora que se muestra es la <b>del servidor</b>, calculada cada vez que se pide la página. Para el parcial hay que decir que esta mezcla de Java y HTML es lo que luego se evita con JSTL.",
     "bloques": [
      ("", "<b>Directivas page import</b>: importan <i>LocalTime</i> y <i>DateTimeFormatter</i> para poder usarlas en el código Java de la página (es el equivalente a los import de una clase)."),
      ("<html>", "HTML de la cabecera: etiqueta html, head con el <b>link a Bootstrap</b> (CDN) y apertura del body."),
      ("<%", "<b>Scriptlet</b> (&lt;% … %&gt;): código Java que se ejecuta en el servidor. Obtiene la hora actual con <i>LocalTime.now()</i> y su hora (0-23). Declara las variables <i>msjSaludo</i> (texto) y <i>classColor</i> (clase CSS de Bootstrap)."),
      ("if(hora >= 6", "Lógica de decisión: de 6 a 11 «Buenos días» con estilo amarillo (<i>alert-warning</i>); de 12 a 19 «Buenas tardes» con azul (<i>alert-info</i>); el resto «Buenas noches» con gris oscuro (<i>alert-dark</i>). El <b>%&gt;</b> cierra el scriptlet."),
      ("<div class=\"container\">", "Contenedor de Bootstrap. Dos comentarios: <b>&lt;%-- --%&gt;</b> (JSP: no llega al navegador) y <b>&lt;!-- --&gt;</b> (HTML: sí se envía, se ve en «ver código fuente»). Título h2."),
      ("<div class=\"alert <%= classColor %>\">", "<b>Expresión</b> (&lt;%= … %&gt;): imprime el valor de <i>classColor</i> dentro del atributo class, y en la línea siguiente imprime el saludo. Así el HTML final queda, por ejemplo, <i>class=\"alert alert-info\"</i>."),
      ("<p>", "Muestra la hora del servidor formateada con <b>DateTimeFormatter.ofPattern(\"HH:mm:ss\")</b>, mediante otra expresión. Cierra el contenedor, body y html."),
     ]},
    W + "formulario.html": {
     "rol": "Formulario HTML estático (página 1) que pide nombre y edad y los envía por POST a <i>procesar-form.jsp</i>.",
     "defensa": "Muestra la conexión entre HTML y JSP: <b>method=\"post\"</b> + <b>action=\"procesar-form.jsp\"</b> y los atributos <b>name</b> (<i>txtNombre</i>, <i>txtEdad</i>), que son exactamente las claves que el JSP leerá con <i>getParameter</i>. Sin name los datos no viajan.",
     "bloques": [
      ("", "DOCTYPE, html, <b>head</b> con charset UTF-8, título y link a Bootstrap."),
      ("<body>", "Cuerpo: título «Página 1: Formulario HTML» y contenedor Bootstrap."),
      ("<form method=\"post\"", "<b>form</b>: el método POST y la <b>action</b> con la página que procesa los datos."),
      ("<label class=\"form-label\"", "Campo de <b>nombre</b>: <i>id=\"inNombre\"</i> (lo usa el label) y <b>name=\"txtNombre\"</b> (el nombre del parámetro que viaja al servidor)."),
      ("<label class=\"form-label\"\n                        for=\"inEdad\">", "Campo de <b>edad</b> de <i>type=\"number\"</i> con <b>name=\"txtEdad\"</b>."),
      ("<button type=\"submit\"", "Botón que envía el formulario."),
     ]},
    W + "procesar-form.jsp": {
     "rol": "Página JSP (página 2) que <b>recibe y procesa</b> los datos del formulario y muestra si la persona es mayor o menor de edad.",
     "defensa": "Es el ejemplo de cómo un JSP lee un formulario: <b>request.getParameter</b>, convierte con <b>parseInt</b>, decide con un <b>if</b> y escribe con <b>out.println</b> y con una expresión. <b>Errores que conviene reconocer:</b> (1) la condición <i>txtEdad != null || !txtEdad.isEmpty()</i> debería usar <b>&amp;&amp;</b>: con || si el valor es null se produce un NullPointerException al evaluar el segundo término, y si llega vacío (\"\") igual se intenta <i>parseInt</i> y falla con NumberFormatException; (2) mostrar <i>txtNombre</i> sin escapar permite inyección de HTML/JS (XSS). Con JSTL se usa <i>&lt;c:out&gt;</i> para escapar.",
     "bloques": [
      ("", "Comentario JSP generado por el IDE (autor y fecha); no se envía al navegador."),
      ("<%@ page contentType", "<b>Directiva page</b>: <i>contentType=\"text/html;charset=UTF-8\"</i> define el tipo MIME y la codificación de la respuesta (tildes correctas); <i>language=\"java\"</i> indica el lenguaje de los scriptlets."),
      ("<html>", "Apertura de html y head con título y Bootstrap. Título «Página 2: Procesado de formulario por JSP»."),
      ("<%\n        String txtNombre", "<b>Scriptlet</b>: lee los datos del formulario con el objeto implícito <b>request</b>."),
      ("String txtNombre", "<b>request.getParameter(\"txtNombre\")</b> y <i>\"txtEdad\"</i>: siempre devuelven <b>String</b> (o null si el parámetro no vino). El nombre del parámetro es el <b>name</b> del input del formulario."),
      ("int edad = 0;", "Variable entera con valor inicial 0 y conversión del texto a número con <b>Integer.parseInt</b> (ver observación en la defensa)."),
      ("<h2>¡Hola,", "Imprime con una expresión el nombre recibido. Debajo hay un comentario JSP con una línea inválida (<i>out.print</i> dentro de una expresión no compila)."),
      ("if(edad >= 18)", "Otro scriptlet: decide si es mayor de edad y escribe el párrafo con <b>out.println</b> (escribe directamente en la respuesta)."),
      ("<a href=\"formulario.html\"", "Enlace (estilo botón) para volver al formulario. Cierra body y html."),
     ]},
   }},
 ],
 "cierre": [
  ("h1", "Resumen para estudiar"),
  ("li", "HTTP: petición (método + cabeceras + cuerpo) y respuesta (estado + cabeceras + cuerpo). GET consulta, POST modifica. 200 OK, 302 redirección, 404 no encontrado, 500 error del servidor."),
  ("li", "JSP = HTML + Java en el servidor; el cliente solo recibe HTML. Internamente se convierte en un servlet."),
  ("li", "Código JSP: expresión &lt;%= %&gt;, scriptlet &lt;% %&gt;, declaración &lt;%! %&gt;, directiva &lt;%@ %&gt;, comentario &lt;%-- --%&gt;."),
  ("li", "Objetos implícitos: request, response, out, session, application, config, pageContext."),
  ("li", "Formulario → <i>name</i> del input = parámetro leído con <i>request.getParameter(\"name\")</i> (devuelve String)."),
  ("li", "Proyecto war: src/main/webapp (JSP/HTML) + WEB-INF/web.xml; las APIs de servlet/JSP son <i>provided</i>."),
  ("h1", "Preguntas típicas"),
  ("q", "¿Qué diferencia hay entre un scriptlet y una expresión?"),
  ("p", "El scriptlet (&lt;% %&gt;) ejecuta varias líneas de Java sin imprimir nada por sí mismo; la expresión (&lt;%= %&gt;) evalúa una sola expresión e imprime su valor en la página."),
  ("q", "¿Por qué se dice que un JSP es un servlet?"),
  ("p", "Porque el contenedor lo traduce a una clase que extiende HttpServlet, la compila y la ejecuta; el HTML se escribe con out.println en el método de servicio."),
  ("q", "¿Qué devuelve request.getParameter si el campo no existe?"),
  ("p", "Devuelve null; si existe pero está vacío devuelve una cadena vacía. Por eso hay que validar antes de convertir a número."),
 ],
}
