from comunes import pom_war, webxml

B = "Codigo/021 - Clase 09-09/"
W = B + "src/main/webapp/"

COMENT = ("", "Comentario JSP generado por el IDE (autor y fecha); no llega al navegador.")

TEMA = {
 "carpeta": "Tema 07 - JSTL y Cookies",
 "titulo": "Tema 07 · JSTL y Cookies",
 "clases": "Clase 021 (09-09) · Teoría: «JSP» (Clase020_jsp.pdf): cookies y JSP Tags",
 "intro": [
  ("h1", "1. Cookies"),
  ("p", "Una <b>cookie</b> es un pequeño dato de texto (clave = valor) que el <b>servidor envía al navegador</b> y que el navegador <b>guarda y devuelve</b> en cada petición posterior. A diferencia de la Session (datos en el servidor), la cookie guarda el dato <b>en el cliente</b>. Usos: recordar la última búsqueda, el idioma, presentar el sitio como el usuario lo dejó, y <b>recordar al visitante sin que vuelva a loguearse</b> (el requisito de «sesión recordada» del parcial)."),
  ("tabla", [["Acción", "Código Java (Servlet o JSP)"],
    ["Crear una cookie", "<i>Cookie c = new Cookie(\"ultimoDestino\", valor);</i>"],
    ["Definir su vida (segundos)", "<i>c.setMaxAge(60*60*24*7);</i> → 7 días. Sin setMaxAge dura solo hasta cerrar el navegador. <b>0</b> = borrarla"],
    ["Enviarla al navegador", "<i>response.addCookie(c);</i>"],
    ["Leer las cookies que llegan", "<i>Cookie[] cookies = request.getCookies();</i> (puede ser <b>null</b> si no hay ninguna) y recorrerlas con for, comparando <i>getName()</i> y leyendo <i>getValue()</i>"],
    ["Borrar una cookie", "Crear una con el mismo nombre, <b>setMaxAge(0)</b> y enviarla con addCookie"]]),
  ("p", "<b>Seguridad:</b> los valores de las cookies no admiten ciertos caracteres (espacios, tildes, punto y coma), por eso se codifican con <i>URLEncoder.encode(valor, \"UTF-8\")</i> al guardar (y se decodifican con <i>URLDecoder.decode</i> al leer). Nunca se guarda una contraseña en una cookie; para recordar al usuario se guarda un <b>token aleatorio</b>. Atributos importantes: <b>HttpOnly</b> (JavaScript no puede leerla), <b>Secure</b> (solo por HTTPS) y <b>SameSite</b>."),
  ("tabla", [["", "Session", "Cookie"],
    ["Dónde se guardan los datos", "En el servidor", "En el navegador (cliente)"],
    ["Qué viaja", "Solo el id (JSESSIONID, que es una cookie)", "El dato completo, en cada petición"],
    ["Duración", "Hasta invalidate() o timeout", "Hasta la fecha de vencimiento (maxAge)"],
    ["Seguridad", "Mayor (el dato no sale del servidor)", "Menor (el usuario puede verla y modificarla)"]]),
  ("h1", "2. JSTL: la librería de etiquetas estándar"),
  ("p", "<b>JSTL (JSP Standard Tag Library)</b> es una librería de etiquetas con forma de XML que <b>reemplaza a los scriptlets</b>. Ventajas: el JSP queda más limpio y legible, se separa la presentación de la lógica (código Java fuera de la vista) y se mantiene más fácil. Se compone de: <b>Core</b> (lógica: if, forEach, choose, set, out, redirect), <b>Formatting</b> (formato de números, fechas y mensajes), SQL, XML y <b>Functions</b> (funciones de texto como <i>fn:escapeXml</i>)."),
  ("p", "<b>Cómo se usa:</b> (1) agregar las dependencias al pom (jstl y standard); (2) declarar la librería en cada JSP con la directiva <b>taglib</b> y un prefijo:"),
  ("codigo", "<%@ taglib prefix=\"c\"   uri=\"http://java.sun.com/jsp/jstl/core\" %>\n<%@ taglib prefix=\"fmt\" uri=\"http://java.sun.com/jsp/jstl/fmt\"  %>"),
  ("tabla", [["Etiqueta", "Equivale a", "Ejemplo"],
    ["<b>&lt;c:if&gt;</b>", "if (sin else)", "<i>&lt;c:if test=\"${not empty lista}\"&gt; … &lt;/c:if&gt;</i>"],
    ["<b>&lt;c:forEach&gt;</b>", "for / for-each", "<i>&lt;c:forEach var=\"p\" items=\"${productos}\"&gt; … &lt;/c:forEach&gt;</i>"],
    ["<b>&lt;c:choose&gt; / &lt;c:when&gt; / &lt;c:otherwise&gt;</b>", "if / else if / else (switch)", "<i>&lt;c:when test=\"${p.enStock}\"&gt;</i>"],
    ["&lt;c:set&gt; / &lt;c:out&gt;", "asignar variable / imprimir (escapando HTML)", "<i>&lt;c:out value=\"${nombre}\"/&gt;</i>"],
    ["&lt;fmt:formatNumber&gt;", "formatear un número", "<i>&lt;fmt:formatNumber value=\"${p.precio}\" type=\"currency\" currencySymbol=\"$\"/&gt;</i>"]]),
  ("h2", "Expression Language (EL): ${ }"),
  ("p", "JSTL se usa junto con el <b>EL</b>, una sintaxis corta para leer datos: <b>${producto.nombre}</b> equivale a <i>producto.getNombre()</i> (llama al getter; por eso las clases deben seguir la convención JavaBean: getXxx/isXxx). Para los booleanos el getter es <b>isEnStock()</b> y en EL se escribe <b>${producto.enStock}</b>. EL busca la variable en los alcances page → request → session → application. Operadores útiles: <b>empty</b> (null o vacío), <b>not</b>, and, or, ==."),
  ("nota", "<b>Muy importante para el parcial:</b> en el código de clase (Tomcat 9, <i>javax.servlet</i>) el URI de JSTL es <i>http://java.sun.com/jsp/jstl/core</i>. En Tomcat 10 en adelante (Jakarta EE) cambia a <b>jakarta.tags.core</b>, y las dependencias también. La solución del parcial incluida en este repositorio usa Jakarta; si el profesor usa Tomcat 9 hay que adaptar esos nombres (ver advertencia en el README)."),
  ("h1", "3. Scriptlets vs. JSTL (comparación)"),
  ("p", "La clase muestra la <b>misma tabla de productos hecha de dos maneras</b>: con scriptlets (<i>for</i> de Java y <i>out.println</i> para escribir cada fila: código difícil de leer, mezcla HTML con Java) y con JSTL (<i>c:forEach</i> y <i>c:choose</i> dentro del HTML: legible y fácil de mantener). Esta comparación es exactamente la justificación del punto «Uso de JSP y tags JSP (JSTL)» del parcial."),
 ],
 "clases_detalle": [
  {"titulo": "Clase 021 – 09-09: cookies (último destino buscado) y tabla de productos con scriptlets y con JSTL",
   "resumen": [("p", "Tres ejercicios: (1) <b>destinos.jsp</b>, <b>procesamiento.jsp</b> y <b>eliminar.jsp</b> guardan, leen y borran en una <b>cookie</b> el último destino elegido; (2) <b>tabla_scriptlets.jsp</b> arma una tabla de productos con Java; (3) <b>tabla_jstl.jsp</b> hace la misma tabla con <b>JSTL</b>. La clase <b>Producto</b> es el modelo.")],
   "archivos": {
    B + "pom.xml": pom_war("clase-09-09", jstl=True),
    W + "WEB-INF/web.xml": webxml(v4=True),
    B + "src/main/java/edu/usal/model/Producto.java": {
     "rol": "Clase de <b>modelo</b> (JavaBean) que representa un producto: nombre, precio y si hay stock.",
     "defensa": "Sigue la <b>convención JavaBean</b>: atributos privados + getters/setters públicos. Esto es lo que permite a EL leer <i>${producto.nombre}</i>: EL llama a <i>getNombre()</i>. Para el booleano el getter se llama <b>isEnStock()</b> (convención de boolean) y en EL se usa <i>${producto.enStock}</i>.",
     "bloques": [
      ("", "Paquete <b>edu.usal.model</b>: el modelo de datos."),
      ("public class Producto", "Tres atributos <b>privados</b> (encapsulamiento): nombre (String), precio (double) y enStock (boolean)."),
      ("public Producto(String nombre", "Constructor con todos los datos: asigna cada parámetro al atributo con <b>this</b>."),
      ("public String getNombre", "Getter y setter del nombre."),
      ("public double getPrecio", "Getter y setter del precio."),
      ("public boolean isEnStock", "Para los <b>boolean</b> el getter se llama <b>is</b>Xxx (JavaBean) y el setter, setEnStock."),
     ]},
    W + "destinos.jsp": {
     "rol": "Página que <b>lee la cookie</b> «ultimoDestino» y la muestra; contiene el formulario para elegir un destino y el botón para eliminar el guardado.",
     "defensa": "Muestra la lectura de cookies: <b>getCookies()</b> puede ser null (primera visita), se recorre el arreglo buscando por nombre y se sale con break al encontrarla. Queda comentada la alternativa con <b>Session</b>: así se aprecia la diferencia entre ambas. <b>Observaciones:</b> el valor se guardó codificado con URLEncoder, así que al leerlo conviene decodificarlo con <i>URLDecoder.decode</i> (con «cancún» se vería «canc%C3%BAn»); el <i>select</i> tiene una errata en el atributo (<i>id=selectDestino\"</i>, falta la comilla de apertura); y la página no incluye el CSS de Bootstrap, por lo que las clases no tienen efecto.",
     "bloques": [
      COMENT,
      ("<%@ page contentType", "Directiva page: tipo de contenido y codificación UTF-8."),
      ("<html>", "Apertura de html y head (charset y título)."),
      ("<%", "Scriptlet: la primera línea comentada obtenía el destino de la Session. Se declara <b>ultimoDestino</b> vacío y se piden las cookies con <b>request.getCookies()</b>."),
      ("if(cookies != null)", "Si hay cookies (si no, el arreglo es <b>null</b>), las recorre con for-each; si el nombre es «ultimoDestino» guarda su valor con <b>getValue()</b> y corta con <b>break</b>. Se escribe <i>\"ultimoDestino\".equals(…)</i> para evitar NullPointerException."),
      ("<body>", "Cuerpo: un aviso informativo que imprime con una <b>expresión</b> el último destino guardado (vacío si no hay)."),
      ("<form action=\"procesamiento.jsp\"", "<b>Formulario POST</b> a <i>procesamiento.jsp</i> con una lista desplegable (<i>name=\"selectDestino\"</i>) con tres destinos y el botón «Buscar»."),
      ("<form method=\"post\" action=\"eliminar.jsp\">", "Segundo formulario POST, con el botón «Eliminar destino guardado» que llama a <i>eliminar.jsp</i>."),
     ]},
    W + "procesamiento.jsp": {
     "rol": "JSP <b>sin interfaz</b> que recibe el destino elegido, lo <b>guarda en una cookie</b> y vuelve a destinos.jsp.",
     "defensa": "Es el ejemplo de <b>crear una cookie</b>: <i>new Cookie</i>, <i>setMaxAge</i>, <i>response.addCookie</i>. El valor se codifica con <b>URLEncoder</b> porque las cookies no admiten ciertos caracteres. Termina con <b>sendRedirect</b>: es el patrón Post/Redirect/Get (después de procesar se redirige para que al refrescar no se reenvíe el formulario).",
     "bloques": [
      ("", "Directivas <b>page import</b>: <i>Locale</i> (sin usar) y <b>URLEncoder</b>."),
      ("<%@ page contentType", "Directiva page (UTF-8). Luego html, head y título."),
      ("<%", "Scriptlet principal. Lee el parámetro <b>selectDestino</b> con getParameter."),
      ("if(selectDestino != null", "Si el destino no es null ni vacío (<b>trim()</b> quita espacios) lo procesa: <b>URLEncoder.encode(…, \"UTF-8\")</b> lo «sanitiza» (codifica tildes, espacios y símbolos)."),
      ("//Crear la cookie", "Crea la cookie <b>ultimoDestino</b> con el valor codificado y define que vive <b>7 días</b> (60 s × 60 min × 24 h × 7), y la agrega a la respuesta con <b>response.addCookie</b>."),
      ("//session.setAttribute", "Línea comentada con la alternativa por Session. Luego <b>response.sendRedirect(\"destinos.jsp\")</b>: indica al navegador que pida esa página (respuesta 302)."),
      ("<body>", "Body vacío: esta página nunca se ve, solo procesa y redirige."),
     ]},
    W + "eliminar.jsp": {
     "rol": "JSP sin interfaz que <b>borra la cookie</b> del último destino y vuelve a destinos.jsp.",
     "defensa": "Una cookie no se «borra» directamente: se envía una cookie del <b>mismo nombre</b> con <b>maxAge 0</b> y el navegador la descarta. Las líneas comentadas muestran las opciones equivalentes para la Session (<i>setAttribute null</i>, <i>invalidate</i>, <i>removeAttribute</i>). Este es el mismo mecanismo que usa el cierre de sesión del parcial para limpiar las cookies.",
     "bloques": [
      COMENT,
      ("<%@ page contentType", "Directiva page (UTF-8), html, head y título."),
      ("<%", "Scriptlet. Las tres primeras líneas (comentadas) son las formas de olvidar el dato si estuviera en la <b>Session</b>."),
      ("Cookie cookie = new Cookie", "Crea una cookie con el <b>mismo nombre</b> y valor vacío; <b>setMaxAge(0)</b> le indica al navegador que la elimine ya; <b>addCookie</b> la envía en la respuesta."),
      ("response.sendRedirect", "Redirige a destinos.jsp, que ahora mostrará el destino vacío."),
      ("<body>", "Body vacío."),
     ]},
    W + "tabla_scriptlets.jsp": {
     "rol": "Tabla de productos armada <b>con scriptlets</b>: la forma «a la antigua».",
     "defensa": "Sirve de contraste con la versión JSTL: acá hay que usar <b>out.println</b> para escribir cada etiqueta HTML desde Java: el código es largo, difícil de leer y mezcla lógica con presentación. Además la lista se crea dentro del propio JSP (en una aplicación real vendría de un DAO a través del servlet).",
     "bloques": [
      ("", "Directivas <b>page import</b> de <i>List</i>, <i>ArrayList</i> y de la clase <b>Producto</b> del modelo."),
      ("<%@ page contentType", "Directiva page (UTF-8). Luego el comentario del IDE, html, head y título."),
      ("<%\n    List<Producto> productos", "<b>Scriptlet</b>: crea una lista de productos y agrega tres productos de ejemplo."),
      ("List<Producto> productos", "Se declara <b>List&lt;Producto&gt;</b> con <b>ArrayList</b> y se agregan con <i>add(new Producto(…))</i>."),
      ("<body>", "Cuerpo: contenedor, título y apertura de la tabla con su encabezado (<b>thead</b> con las columnas Producto, Precio y Estado)."),
      ("<tbody>", "Cuerpo de la tabla."),
      ("for(Producto producto : productos)", "<b>for-each</b> de Java dentro de un scriptlet: por cada producto escribe con <b>out.println</b> cada etiqueta (<i>tr</i>, <i>td</i>, el dato, <i>/td</i>…): nombre, precio y si está en stock (se verá true o false)."),
      ("</tbody>", "Cierra la tabla, el contenedor, body y html."),
     ]},
    W + "tabla_jstl.jsp": {
     "rol": "La <b>misma tabla de productos</b> pero con <b>JSTL</b> y <b>EL</b>: la forma recomendada.",
     "defensa": "Es el modelo de vista que pide el parcial. Puntos para defender: <b>(1)</b> la directiva <b>taglib</b> con prefijo <i>c</i> y <i>fmt</i>; <b>(2)</b> <i>pageContext.setAttribute</i> hace visible la lista para EL (EL solo ve atributos de page/request/session/application, no variables locales del scriptlet); <b>(3)</b> <i>c:if</i> con <i>empty</i> para el mensaje de lista vacía; <b>(4)</b> <i>c:forEach</i> para recorrer; <b>(5)</b> <i>fmt:formatNumber</i> para mostrar precios como moneda; <b>(6)</b> <i>c:choose</i> para el estado con colores. El scriptlet que arma la lista está sólo para la demostración: en una aplicación real el <b>servlet</b> deja la lista en el request y la JSP no tiene nada de Java (Tema 08).",
     "bloques": [
      ("", "<b>Directivas page import</b> (List, ArrayList y Producto)."),
      ("<%@ taglib prefix=\"c\"", "<b>Directivas taglib</b>: declaran las librerías <b>core</b> (prefijo <i>c</i>) y <b>fmt</b> (prefijo <i>fmt</i>) de JSTL, mediante su URI."),
      ("<%@ page contentType", "Directiva page (UTF-8) y apertura de html, head y título."),
      ("<%\n    List<Producto> listaProductos", "<b>Scriptlet</b> (solo para armar los datos de la demo): crea la lista con tres productos (uno sin stock)."),
      ("pageContext.setAttribute(\"productos\"", "<b>Publica la lista</b> con el nombre «productos» en el alcance de la página: así la etiqueta forEach y EL pueden usarla."),
      ("<body>", "Cuerpo: contenedor y título."),
      ("<c:if test=\"${empty productos}\">", "<b>c:if</b> con el operador <b>empty</b>: si la lista está vacía o es null, muestra un aviso."),
      ("<c:if test=\"${not empty productos}\">", "Si NO está vacía, dibuja la tabla (encabezado con las tres columnas)."),
      ("<c:forEach var=\"producto\"", "<b>c:forEach</b>: recorre la lista; en cada vuelta la variable <i>producto</i> es el elemento actual. <b>${producto.nombre}</b> imprime el nombre (llama a getNombre())."),
      ("<fmt:formatNumber", "<b>fmt:formatNumber</b>: formatea el precio como <b>moneda</b> con símbolo «$»."),
      ("<c:choose>", "<b>c:choose / c:when / c:otherwise</b> (if-else): si <b>${producto.enStock}</b> es verdadero muestra un distintivo verde «Disponible»; en otro caso, uno rojo «No disponible»."),
      ("</c:forEach>", "Cierra el bucle, la tabla y el c:if; cierra el contenedor, body y html."),
     ]},
   }},
 ],
 "cierre": [
  ("h1", "Resumen para estudiar"),
  ("li", "<b>Cookie</b>: dato en el navegador. <i>new Cookie</i> → <i>setMaxAge</i> → <i>response.addCookie</i>; leer con <i>request.getCookies()</i> (puede ser null); borrar con maxAge 0."),
  ("li", "Valores de cookie: codificar con URLEncoder. Nunca guardar contraseñas."),
  ("li", "<b>JSTL</b>: reemplaza scriptlets. Directiva <i>taglib</i> + prefijo. Core: if, forEach, choose/when/otherwise, set, out. fmt: formatNumber. EL: <i>${objeto.propiedad}</i> llama al getter."),
  ("li", "EL solo ve atributos de page, request, session y application (no variables locales de scriptlet)."),
  ("li", "En el parcial: el servlet deja los datos en el request y la JSP los muestra solo con JSTL/EL."),
  ("h1", "Preguntas típicas"),
  ("q", "¿Cuál es la diferencia entre Session y Cookie?"),
  ("p", "La Session guarda los datos en el servidor y al cliente solo le envía un id; la cookie guarda el dato en el navegador. La session es más segura; la cookie puede durar días aunque se cierre el navegador."),
  ("q", "¿Cómo se borra una cookie?"),
  ("p", "Se envía una cookie con el mismo nombre y setMaxAge(0)."),
  ("q", "¿Por qué usar JSTL y no scriptlets?"),
  ("p", "Porque separa la presentación de la lógica, el código queda más limpio y legible, es más fácil de mantener, y evita mezclar Java con HTML en la vista."),
 ],
}
