from comunes import pom_war, webxml

B = "Codigo/022 - Clase 16-09/"
J = B + "src/main/java/edu/usal/"
W = B + "src/main/webapp/"

COMENT = ("", "Comentario JSP generado por el IDE (autor y fecha); no llega al navegador.")

TEMA = {
 "carpeta": "Tema 08 - Servlets (web.xml, anotaciones, forward)",
 "titulo": "Tema 08 · Servlets: web.xml, anotaciones, forward y MVC",
 "clases": "Clase 022 (16-09) · Teoría: «Servlets» (Clase023_Applet_Servlet.pdf)",
 "intro": [
  ("h1", "1. Qué es un Servlet"),
  ("p", "Un <b>Servlet</b> es una clase Java que se ejecuta <b>en el servidor</b> y atiende peticiones HTTP: recibe la petición del cliente y devuelve una respuesta (normalmente HTML, pero puede ser JSON, un PDF, una imagen…, cualquier <b>tipo MIME</b>). Vive dentro de un <b>contenedor web</b> (Tomcat), que se encarga de recibir las peticiones, crear los objetos y manejar los hilos. Para programarlos se usa el paquete <i>javax.servlet.http</i> (Tomcat 9) o <i>jakarta.servlet.http</i> (Tomcat 10+)."),
  ("p", "Se crean <b>extendiendo HttpServlet</b> y sobrescribiendo <b>doGet</b> (peticiones GET) y/o <b>doPost</b> (peticiones POST). Ambos reciben dos objetos:"),
  ("tabla", [["Objeto", "Para qué sirve", "Métodos usuales"],
    ["<b>HttpServletRequest</b> (req)", "La petición: todo lo que envía el cliente", "<i>getParameter(\"x\")</i> (datos del formulario o de la URL), <i>getParameterValues</i>, <i>getSession()</i>, <i>getCookies()</i>, <i>getMethod()</i>, <i>getQueryString()</i>, <i>getRemoteAddr()</i>, <i>setAttribute / getAttribute</i>, <i>getRequestDispatcher()</i>"],
    ["<b>HttpServletResponse</b> (resp)", "La respuesta: lo que se devuelve", "<i>setContentType(\"text/html\")</i>, <i>getWriter()</i> (PrintWriter para escribir), <i>setStatus(int)</i>, <i>sendRedirect(url)</i>, <i>addCookie()</i>, <i>sendError()</i>"]]),
  ("h1", "2. Ciclo de vida"),
  ("tabla", [["Fase", "Método", "Cuándo ocurre y para qué"],
    ["Inicialización", "<b>init()</b>", "<b>Una sola vez</b>, cuando el contenedor crea la instancia (en la primera petición o al arrancar). Se usa para cargar configuración, crear DAO, abrir recursos."],
    ["Servicio", "<b>service()</b> → doGet / doPost / doPut / doDelete", "<b>En cada petición</b>. service() mira el método HTTP y llama al doXxx correspondiente."],
    ["Destrucción", "<b>destroy()</b>", "<b>Una sola vez</b>, antes de descargar el servlet. Se usa para cerrar conexiones, guardar datos, liberar recursos."]]),
  ("p", "<b>Multihilo:</b> el contenedor crea <b>una única instancia</b> de cada servlet y, por cada petición, un <b>hilo</b> que ejecuta service(). Es decir: N peticiones simultáneas = N hilos sobre el mismo objeto. Consecuencia: <b>no se deben guardar datos específicos de una petición o de un usuario en atributos de la clase del servlet</b> (los compartirían todos los hilos); esos datos van en variables locales, en el request o en la session. Los atributos de instancia son seguros solo si son de sólo lectura o están sincronizados (como el DAO inicializado en init())."),
  ("h1", "3. Declaración y mapeo: web.xml vs. anotaciones"),
  ("p", "Hay que decirle al contenedor <b>qué clase es un servlet y en qué URL responde</b>. Dos formas (el parcial pide conocer ambas):"),
  ("tabla", [["", "web.xml (descriptor)", "Anotación @WebServlet"],
    ["Cómo", "Dos bloques: <i>&lt;servlet&gt;</i> (nombre + clase) y <i>&lt;servlet-mapping&gt;</i> (mismo nombre + url-pattern)", "Una anotación sobre la clase: <i>@WebServlet(\"/productos\")</i> o <i>@WebServlet(name=\"x\", urlPatterns=\"/x\")</i>"],
    ["Ventajas", "Configuración centralizada, se cambia sin recompilar", "Más corto; la URL está junto al código (se mantiene mejor)"],
    ["Requisito", "—", "Servlet 3.0+ (en web.xml usar version 3.0 o superior)"]]),
  ("codigo", "<!-- web.xml -->\n<servlet>\n   <servlet-name>HolaMundoServlet</servlet-name>\n   <servlet-class>edu.usal.servlet.PrimerServlet</servlet-class>\n</servlet>\n<servlet-mapping>\n   <servlet-name>HolaMundoServlet</servlet-name>\n   <url-pattern>/hola-mundo</url-pattern>\n</servlet-mapping>\n\n// Equivalente con anotación\n@WebServlet(name = \"HolaMundoServlet\", urlPatterns = \"/hola-mundo\")\npublic class PrimerServlet extends HttpServlet { ... }"),
  ("p", "La URL final es <b>http://host:puerto/CONTEXTO/url-pattern</b>. El contexto es el nombre del WAR (<i>clase-16-09</i>), por eso el servlet queda en <i>http://localhost:8080/clase-16-09/hola-mundo</i>."),
  ("h1", "4. Respuestas: tipo MIME, estado y redirección"),
  ("li", "<b>Tipo MIME</b> (<i>setContentType</i>) le dice al navegador cómo interpretar la respuesta: <i>text/html</i>, <i>text/plain</i>, <i>application/json</i>, <i>application/pdf</i>, <i>application/zip</i>, <i>image/jpeg</i>. Con texto en español hay que indicar la codificación: <i>\"text/html;charset=UTF-8\"</i>."),
  ("li", "<b>Código de estado</b> (<i>setStatus</i>, <i>sendError</i>): 200 OK, 302 redirección, 400 solicitud incorrecta, 403 prohibido, 404 no encontrado, 405 método no permitido, 500 error del servidor."),
  ("li", "Si no se sobrescribe <b>doPost</b> y se recibe un POST, el comportamiento por defecto de HttpServlet es responder un <b>error (405, método no permitido)</b>: por eso llamar a <i>super.doPost()</i> en un servlet «vacío» equivale a no aceptar POST."),
  ("h1", "5. forward vs. sendRedirect"),
  ("tabla", [["", "RequestDispatcher.forward(req, resp)", "response.sendRedirect(url)"],
    ["Dónde ocurre", "<b>Dentro del servidor</b>: se transfiere el control a otro recurso (un JSP)", "El servidor responde <b>302</b> y el <b>navegador</b> hace una nueva petición a esa URL"],
    ["URL del navegador", "No cambia (el cliente no se entera)", "Cambia a la nueva URL"],
    ["Datos del request", "<b>Se conservan</b>: se pueden pasar objetos con setAttribute", "Se pierden (es otra petición)"],
    ["Eficiencia", "Más eficiente (una sola petición)", "Dos viajes de red"],
    ["Uso típico", "Servlet que prepara datos y los muestra en un JSP (<b>MVC</b>)", "Después de un POST (patrón Post/Redirect/Get) o para ir a otro sitio"],
    ["Alcance", "Solo recursos de la misma aplicación", "Cualquier URL"]]),
  ("h1", "6. Servlets + JSP = MVC"),
  ("p", "La arquitectura <b>MVC (Modelo-Vista-Controlador)</b> separa la aplicación en tres partes: el <b>Modelo</b> (datos y reglas: clases de dominio y DAO), la <b>Vista</b> (lo que se muestra: JSP + JSTL) y el <b>Controlador</b> (el servlet, que recibe la petición, pide datos al modelo y elige la vista). Flujo de esta clase:"),
  ("codigo", "Navegador --GET /productos--> ProductosServlet (Controlador)\n    1. productosDAO.getAll()                  <- Modelo\n    2. req.setAttribute(\"listado\", productos) <- deja los datos en el request\n    3. forward a /WEB-INF/productos/lista-productos.jsp  <- Vista\nlista-productos.jsp recorre ${requestScope.listado} con JSTL y devuelve el HTML"),
  ("p", "Las vistas se ponen dentro de <b>WEB-INF</b>: esa carpeta <b>no es accesible directamente</b> desde el navegador, así que la única forma de ver la JSP es pasando por el servlet (que garantiza que los datos estén cargados). Es la práctica que usa la solución del parcial."),
  ("nota", "<b>Applets:</b> la teoría de esta misma clase (Clase023_Applet_Servlet.pdf) trata también los applets (programas Java dentro de una página web: init, start, stop, destroy, paint). Es una tecnología obsoleta (los navegadores ya no la soportan) y no se utiliza en el parcial; por eso este tema se centra en los servlets."),
 ],
 "clases_detalle": [
  {"titulo": "Clase 022 – 16-09: primer servlet (web.xml), servlet con anotaciones y listado de productos con forward",
   "resumen": [("p", "Tres servlets: <b>PrimerServlet</b> (declarado en web.xml, escribe HTML directamente), <b>SegundoServlet</b> (declarado con anotación) y <b>ProductosServlet</b> (patrón MVC: usa un DAO en memoria y hace <i>forward</i> a una JSP con JSTL). URLs: <i>/hola-mundo</i>, <i>/segundo-servlet</i> y <i>/productos</i>.")],
   "archivos": {
    B + "pom.xml": pom_war("clase-16-09", jstl=True),
    W + "WEB-INF/web.xml": webxml(v4=True, extra=[
      ("<!-- 1 - Declarar el Servlet -->", "<b>Paso 1 – declarar el servlet</b>: <b>servlet-name</b> es un nombre interno (el que se usa para vincularlo con su mapeo) y <b>servlet-class</b> es la clase completa (<i>edu.usal.servlet.PrimerServlet</i>)."),
      ("<!-- 2 - Mapeo de la URL de acceso -->", "<b>Paso 2 – mapear la URL</b>: <b>servlet-mapping</b> vincula el mismo <i>servlet-name</i> con el <b>url-pattern</b> <i>/hola-mundo</i>: la dirección en la que responde."),
    ]),
    J + "model/Productos.java": {
     "rol": "Clase de modelo (JavaBean): un producto con id, nombre y precio.",
     "defensa": "Entidad (POJO) del patrón DAO: atributos privados, constructor vacío y con parámetros, getters y setters. Los getters son los que EL usa en la JSP (<i>${produ.nombre}</i>).",
     "bloques": [
      ("", "Paquete del modelo."),
      ("public class Productos", "Atributos privados: id, nombre y precio."),
      ("public Productos()", "Constructor vacío (útil para frameworks y para crear el objeto y completar con setters)."),
      ("public Productos(int id", "Constructor con todos los datos."),
      ("public int getId", "Getters y setters de cada atributo (encapsulamiento)."),
     ]},
    J + "model/ProductosDAO.java": {
     "rol": "DAO de productos con una <b>lista en memoria</b> (simula la base de datos).",
     "defensa": "Es la implementación inicial «mock»: permite desarrollar el servlet y la vista antes de conectar una base real. Cuando se agregue JDBC, solo cambia esta clase (o se crea otra implementación elegida por una Factory) y el servlet no se modifica. Mejora posible: que sea una interfaz con implementaciones.",
     "bloques": [
      ("", "Paquete del modelo."),
      ("import java.util.ArrayList", "@imports"),
      ("public class ProductosDAO", "Atributo privado: la lista de productos."),
      ("public ProductosDAO()", "Constructor: crea la lista y la <b>carga con tres productos de ejemplo</b> (placa de video, procesador y memoria RAM)."),
      ("public List<Productos> getAll", "Devuelve todos los productos (equivale a un <i>SELECT *</i>)."),
     ]},
    J + "servlet/PrimerServlet.java": {
     "rol": "Primer servlet: responde un «Hola Mundo» escribiendo el HTML con <b>PrintWriter</b>. Se declara en <b>web.xml</b>.",
     "defensa": "Muestra lo esencial: extender <b>HttpServlet</b>, sobrescribir <b>doGet</b>, fijar el <b>tipo MIME</b> y escribir con <b>getWriter()</b>. Escribir HTML con println desde Java es lo que luego se evita delegando la presentación a las JSP (MVC). Dos importaciones (HttpSession y HttpJspPage) no se usan. Como <i>doPost</i> llama a <i>super.doPost</i>, un POST recibe el error por defecto (método no permitido).",
     "bloques": [
      ("", "Paquete de los servlets."),
      ("import javax.servlet.ServletException", "@imports"),
      ("public class PrimerServlet extends HttpServlet", "La clase <b>extiende HttpServlet</b>: así se convierte en un servlet."),
      ("@Override", "<b>@Override</b> + <b>doGet</b>: se ejecuta cuando llega una petición GET (escribir la URL en el navegador es un GET). Recibe <i>req</i> (petición) y <i>resp</i> (respuesta) y declara <i>ServletException</i> e <i>IOException</i>."),
      ("resp.setContentType", "Define el <b>tipo MIME</b> de la respuesta: <i>text/html</i> con codificación UTF-8 (tildes correctas)."),
      ("PrintWriter out", "Obtiene el <b>PrintWriter</b> para escribir el cuerpo de la respuesta."),
      ("out.println(\"<html>\")", "Escribe línea por línea el documento HTML: html, head con título, body con un h1 «Hola Mundo desde el Servlet!». Lo que se escribe es lo que recibe el navegador."),
      ("protected void doPost", "<b>doPost</b> (peticiones POST): se limita a llamar al método de la clase padre, que responde con un error de método no permitido. O sea: este servlet solo acepta GET."),
     ]},
    J + "servlet/SegundoServlet.java": {
     "rol": "Servlet equivalente al anterior pero declarado con la <b>anotación @WebServlet</b> (sin tocar web.xml).",
     "defensa": "Demuestra la configuración por anotaciones: <b>name</b> es el nombre del servlet y <b>urlPatterns</b> la URL (<i>/segundo-servlet</i>). Ventaja sobre web.xml: la URL está junto al código y no hay que editar otro archivo. Responde directamente con <i>resp.getWriter().println</i> (sin setContentType, usa el tipo por defecto).",
     "bloques": [
      ("", "Paquete de los servlets."),
      ("import javax.servlet.ServletException", "@imports"),
      ("@WebServlet(", "<b>Anotación @WebServlet</b>: registra el servlet sin web.xml, con nombre «servlet-anotaciones» y la URL <b>/segundo-servlet</b>."),
      ("public class SegundoServlet", "Extiende HttpServlet."),
      ("protected void doGet", "<b>doGet</b>: escribe directamente un texto en la respuesta con <i>getWriter().println</i>."),
      ("protected void doPost", "<b>doPost</b>: delega en el padre (error por defecto)."),
     ]},
    J + "servlet/ProductosServlet.java": {
     "rol": "<b>Controlador</b> del patrón MVC: obtiene los productos del DAO y los muestra en una JSP mediante <b>forward</b>.",
     "defensa": "Es el modelo más cercano a lo que se pide en el parcial. Puntos: <b>init()</b> crea el DAO <b>una sola vez</b> (ciclo de vida; como el DAO no tiene estado por usuario, es seguro compartirlo entre hilos); <b>doGet</b> consulta, <b>setAttribute</b> deja los datos en el request y <b>forward</b> transfiere a la vista dentro de WEB-INF (el usuario no puede abrirla directo). La línea comentada con <b>sendRedirect</b> no funcionaría: la JSP está en WEB-INF y además un redirect perdería el atributo del request.",
     "bloques": [
      ("", "Paquete de los servlets."),
      ("import edu.usal", "@imports"),
      ("@WebServlet(urlPatterns", "Registra el servlet en la URL <b>/productos</b> con la anotación."),
      ("public class ProductosServlet", "Extiende HttpServlet. Atributo privado: el <b>DAO</b> (el «modelo»)."),
      ("public void init()", "<b>init()</b>: método del ciclo de vida que se ejecuta una vez al crear el servlet; aquí instancia el DAO."),
      ("protected void doPost", "doPost delega en el padre (este servlet solo atiende GET)."),
      ("protected void doGet", "<b>doGet</b>: pide la lista de productos al DAO (<i>getAll()</i>)."),
      ("req.setAttribute", "<b>request.setAttribute(\"listado\", productos)</b>: guarda la lista en el request con el nombre «listado»; la JSP la leerá con <i>${requestScope.listado}</i>."),
      ("RequestDispatcher dispatcher", "Obtiene el <b>RequestDispatcher</b> de la vista y hace <b>forward(req, resp)</b>: el control pasa a la JSP con el mismo request. La carpeta <i>WEB-INF</i> protege la vista de accesos directos. La línea comentada con sendRedirect es la alternativa (incorrecta aquí)."),
     ]},
    W + "index.jsp": {
     "rol": "Página de inicio mínima de la aplicación (título «JSP Clase 16-09»).",
     "defensa": "Es la <i>welcome page</i>: lo que se ve al abrir <i>http://localhost:8080/clase-16-09/</i>. No tiene lógica.",
     "bloques": [
      COMENT,
      ("<%@ page contentType", "Directiva page (UTF-8)."),
      ("<html>", "HTML básico: head con el título y body con un título h1."),
     ]},
    W + "WEB-INF/productos/lista-productos.jsp": {
     "rol": "<b>Vista</b> del patrón MVC: muestra la tabla de productos que dejó el servlet en el request, usando JSTL.",
     "defensa": "Es una vista limpia: <b>cero código Java</b>, solo JSTL y EL. Lee la lista con <i>${requestScope.listado}</i> (alcance explícito de request) y contempla el caso de lista vacía con <b>c:choose</b>. Está dentro de <b>WEB-INF</b>, por lo que solo se llega a ella a través del servlet. Detalle: usa clases de Bootstrap sin cargar la hoja de estilos (no se ven los estilos).",
     "bloques": [
      COMENT,
      ("<%@ page contentType", "Directiva page (UTF-8)."),
      ("<%@ taglib prefix=\"c\"", "Directiva <b>taglib</b>: habilita la librería <b>core</b> de JSTL con el prefijo <i>c</i>."),
      ("<html>", "html, head con título y body con el título «Listado de productos»."),
      ("<c:choose>", "<b>c:choose</b>: estructura if / else. <b>c:when</b> con <i>${empty requestScope.listado}</i>: si el atributo «listado» no existe o está vacío, muestra el aviso «No existe productos cargados»."),
      ("<c:otherwise>", "<b>c:otherwise</b> (else): si hay datos, arma la tabla con su encabezado (ID, Nombre y Precio)."),
      ("<c:forEach var=\"produ\"", "<b>c:forEach</b>: recorre <i>${requestScope.listado}</i>; en cada vuelta <b>produ</b> es un producto y <b>${produ.id}</b>, <b>${produ.nombre}</b> y <b>${produ.precio}</b> llaman a sus getters. Una fila por producto."),
      ("</c:forEach>", "Cierra el bucle, la tabla y el choose; cierra body y html."),
     ]},
   }},
 ],
 "cierre": [
  ("h1", "Resumen para estudiar"),
  ("li", "Servlet = clase que extiende <b>HttpServlet</b> y sobrescribe doGet/doPost. Recibe <b>request</b> y <b>response</b>."),
  ("li", "Ciclo de vida: <b>init()</b> (una vez) → <b>service()</b> → doGet/doPost (cada petición) → <b>destroy()</b> (una vez)."),
  ("li", "Una instancia por servlet, un hilo por petición: no guardar datos de usuario en atributos del servlet."),
  ("li", "Mapeo: <b>web.xml</b> (servlet + servlet-mapping) o <b>@WebServlet</b>."),
  ("li", "<b>forward</b>: interno, conserva el request, la URL no cambia. <b>sendRedirect</b>: 302, el navegador hace otra petición, se pierde el request."),
  ("li", "MVC: Servlet (controlador) + DAO (modelo) + JSP/JSTL (vista en WEB-INF). Datos al JSP con <b>request.setAttribute</b>."),
  ("li", "Tipo MIME con setContentType; códigos 200/302/400/403/404/500."),
  ("h1", "Cómo se aplica en el parcial de logística"),
  ("li", "Los servlets <b>LoginServlet</b> y <b>LogoutServlet</b> están en web.xml; <b>CamionServlet</b>, <b>ChoferServlet</b>, <b>ViajeServlet</b>, <b>MisViajesServlet</b> e <b>InicioServlet</b> usan @WebServlet: se cumple el punto «Servlets por anotaciones y web.xml»."),
  ("li", "Todos siguen el patrón de <i>ProductosServlet</i>: consulta al DAO → <i>setAttribute</i> → <i>forward</i> a una JSP de WEB-INF; y tras un POST se usa <i>sendRedirect</i> (Post/Redirect/Get)."),
  ("h1", "Preguntas típicas"),
  ("q", "¿Cuántas instancias de un servlet hay?"),
  ("p", "Una sola; cada petición se atiende en un hilo distinto sobre esa instancia. Por eso no se guardan datos del usuario en atributos del servlet."),
  ("q", "¿Cuándo uso forward y cuándo sendRedirect?"),
  ("p", "forward para mostrar una vista con los datos que preparó el servlet; sendRedirect después de un POST (o para ir a otra URL) para que al refrescar no se repita la operación."),
  ("q", "¿Por qué las JSP van en WEB-INF?"),
  ("p", "Porque WEB-INF no es accesible desde el navegador: la única forma de verlas es pasando por un servlet, que garantiza que los datos estén cargados y que se aplique la seguridad."),
 ],
}
