# Capitulos de texto del PDF (introduccion, arquitectura, defensa oral)
CAPITULOS_INICIALES = [
 ("titulo", "Explicación y defensa del código"),
 ("p", "<b>Programación Avanzada – Parcial 2do Cuatrimestre – Octubre 2025</b><br/>Profesor: Macrino Matias · Universidad del Salvador – Sede Pilar"),
 ("p", "Aplicación web para una empresa de logística: ABM de camiones y choferes, carga de viajes con cálculo de tiempo y tanques, y un perfil de chofer que inicia y finaliza sus viajes. Este documento explica <b>cada línea</b> del código entregado y <b>defiende</b> las decisiones de diseño, organizado para responder las preguntas de una defensa oral."),
 ("h2", "Contenido"),
 ("li", "<b>Parte I</b> – Visión general: qué se pidió, arquitectura, modelo de datos y cómo se cumple cada punto de evaluación."),
 ("li", "<b>Parte II</b> – Flujos principales de la aplicación, paso a paso."),
 ("li", "<b>Parte III</b> – Todo el código fuente explicado línea por línea y defendido."),
 ("li", "<b>Parte IV</b> – Preguntas frecuentes de defensa, supuestos y limitaciones reconocidas."),
 ("salto", ""),
 ("h1", "Parte I – Visión general"),
 ("h2", "1. Qué pide el enunciado y dónde está resuelto"),
 ("tabla", [
  ["Requisito del enunciado", "Dónde está resuelto"],
  ["Choferes con nombre, apellido, DNI, fecha de nacimiento, categoría y solo celular; autorizados a uno o más camiones", "Tabla <i>chofer</i> + <i>chofer_camion</i>; clases Persona y Chofer; ChoferServlet"],
  ["Camiones con marca, modelo, dominio, toneladas máximas, litros del tanque y litros por km; manejados por uno o más choferes", "Tabla <i>camion</i>; clase Camion; CamionServlet"],
  ["Destinos únicamente: CABA, Córdoba, Corrientes, Neuquén, Formosa, La Rioja, Mendoza y La Plata", "Enum Destino y tabla <i>destino</i> (con FK desde distancia y viaje)"],
  ["Pantalla principal de inicio de sesión con usuario y contraseña", "LoginServlet (web.xml) + login.jsp"],
  ["Recordar al usuario sin volver a iniciar sesión", "Cookie RECORDARME con token aleatorio guardado en <i>sesion_recordada</i>; AutenticacionFilter la restaura"],
  ["Dos perfiles: administración y chofer", "Enum Rol; AutenticacionFilter restringe /admin/* y /chofer/*"],
  ["Administrador: cargar viajes, designar chofer, ABM de camiones y choferes", "ViajeServlet, CamionServlet, ChoferServlet"],
  ["Chofer: ver solo sus viajes, marcar inicio y marcar realizado", "MisViajesServlet; procedure <i>sp_finalizar_viaje</i>"],
  ["Buscar chofer por DNI; si no existe, informar en pantalla", "ChoferDAO.buscarPorDni lanza ChoferNoEncontradoException; ViajeServlet la muestra con SweetAlert"],
  ["Mostrar camiones que el chofer puede manejar y que no estén en viaje", "Procedure <i>sp_camiones_disponibles</i> (CallableStatement)"],
  ["Elegir origen y destino; calcular tiempo de viaje (200 km/día) y cantidad de tanques", "Tabla <i>distancia</i> + CalculadoraViaje"],
  ["Iniciar desde el path root con contexto (http://host:port/contexto/)", "WAR llamado <i>logistica</i> y welcome-file index.jsp"],
  ["Session y cookie; al cerrar sesión limpiar ambas", "SesionUtil + LogoutServlet (invalida Session, expira cookies, borra token)"],
  ["Entregables: código Maven con proyectos DAO y MVC, y script DDL", "logistica-dao, logistica-web, db/01_ddl_logistica.sql"],
 ]),
 ("h2", "2. Arquitectura"),
 ("p", "El proyecto es un <b>Maven multi-módulo</b> con el POM padre y dos proyectos, tal como pide el profesor («separación de proyectos DAO y MVC»):"),
 ("tabla", [
  ["Módulo", "Contiene", "Depende de"],
  ["<b>logistica-dao</b> (jar)", "Dominio (modelo), excepciones, utilidades, interfaces DAO, DAOFactory, implementaciones JDBC, Singleton de conexión y tests", "Solo el driver de MySQL y JUnit. No sabe nada de la web."],
  ["<b>logistica-web</b> (war)", "Controladores (Servlets), filtros, vistas JSP + JSTL, CSS y JS", "logistica-dao + APIs de Servlet/JSP (las provee Tomcat)"],
 ]),
 ("p", "<b>Flujo de una petición (MVC):</b> el navegador llama a una URL → el <i>AutenticacionFilter</i> controla sesión y perfil → el <b>Controlador</b> (servlet) lee los parámetros, pide datos a los <b>DAO</b> (obtenidos de la <i>DAOFactory</i>) que consultan MySQL por JDBC y devuelven objetos del <b>Modelo</b> → el controlador deja esos objetos en la request y hace <i>forward</i> a una <b>Vista</b> (JSP) que los muestra con JSTL. Después de un POST siempre se redirige (Post/Redirect/Get)."),
 ("p", "<b>Capas y responsabilidades:</b> el <i>modelo</i> contiene las reglas (validaciones, cálculo de viaje, qué camión puede manejar un chofer); el <i>DAO</i> solo traduce entre objetos y SQL; el <i>controlador</i> solo coordina; la <i>vista</i> solo muestra. Ninguna capa salta a otra."),
 ("h2", "3. Modelo de datos"),
 ("tabla", [
  ["Tabla", "Descripción", "Relaciones"],
  ["categoria", "Categorías A–D con toneladas máximas", "1 categoría → N choferes"],
  ["destino", "Las 8 ciudades permitidas", "Referenciada por distancia y viaje"],
  ["distancia", "Km entre cada par de ciudades (56 filas)", "FK origen y destino → destino"],
  ["camion", "Datos del camión (dominio único)", "N a N con chofer vía chofer_camion"],
  ["chofer", "Datos del chofer (DNI único)", "FK categoría; N a N con camión"],
  ["chofer_camion", "Autorizaciones (clave compuesta)", "FK chofer y camión con ON DELETE CASCADE"],
  ["usuario", "Acceso al sistema; rol ADMIN o CHOFER", "0..1 chofer (UNIQUE)"],
  ["sesion_recordada", "Tokens de la cookie «recordarme»", "FK usuario con cascade"],
  ["viaje", "Viaje con cálculo guardado y estado", "FK chofer, camión, origen y destino"],
 ]),
 ("p", "Además hay dos <b>stored procedures</b>: <i>sp_camiones_disponibles</i> y <i>sp_finalizar_viaje</i>, invocados con CallableStatement."),
 ("h2", "4. Cómo se cumple cada punto de evaluación"),
 ("tabla", [
  ["Punto", "Cómo se cumple", "Dónde verlo"],
  ["01 – Patrones de diseño (DAO, Factory, MVC, Singleton)", "<b>DAO</b>: interfaces + implementaciones JDBC. <b>Factory</b>: DAOFactory/JdbcDAOFactory. <b>MVC</b>: servlets (C), JSP (V), clases del dominio (M). <b>Singleton</b>: ConexionDB (holder idiom).", "dao/*, dao/jdbc/*, controlador/*, WEB-INF/jsp"],
  ["02 – Buenas prácticas de POO", "Abstracción y herencia (Persona → Chofer, BaseServlet → servlets), encapsulamiento (atributos privados, lista de solo lectura), polimorfismo (validar() redefinido), clases inmutables (record, Usuario), enums con comportamiento, constantes sin números mágicos, composición, comentarios y nombres claros.", "modelo/*, BaseServlet"],
  ["03 – Uso correcto de excepciones", "Jerarquía propia (LogisticaException → DAOException, ValidacionException, ChoferNoEncontradoException). Se encadena la causa, nunca se traga un error, los recursos se cierran con try-with-resources/finally, y cada tipo recibe un tratamiento distinto en la capa web.", "excepcion/*, JdbcUtil, servlets"],
  ["04 – Dominio coherente y estructura de BD", "Tablas normalizadas con PK, FK, UNIQUE y CHECK; relación N a N explícita; las reglas críticas están también en la base.", "01_ddl_logistica.sql"],
  ["05 – Transacciones JDBC", "Alta/modificación de chofer (3 tablas), alta de viaje (bloqueo FOR UPDATE + verificación + insert), iniciar viaje y guardar token: setAutoCommit(false), commit y rollback.", "ChoferDAOJdbc, ViajeDAOJdbc, UsuarioDAOJdbc"],
  ["06 – Statement, PreparedStatement y CallableStatement", "<b>Statement</b>: listados fijos. <b>PreparedStatement</b>: todo lo que recibe datos. <b>CallableStatement</b>: camiones disponibles (procedure) y finalizar viaje (procedure con OUT).", "CamionDAOJdbc, ChoferDAOJdbc, ViajeDAOJdbc, DistanciaDAOJdbc"],
  ["07 – HTML, JS, Bootstrap y Sweetalert", "Bootstrap 5 para diseño responsive, JS propio (app.js) y SweetAlert2 para avisos y confirmaciones, con degradación si no cargan.", "encabezado.jspf, pie.jspf, js/app.js"],
  ["08 – Servlets por anotaciones y web.xml", "Login y Logout y el filtro de autenticación en web.xml; Inicio, Choferes, Camiones, Viajes, MisViajes y EncodingFilter con @WebServlet/@WebFilter.", "web.xml, controlador/*"],
  ["09 – JSP y tags JSP (JSTL)", "Todas las vistas son JSP con c:, fmt: y fn:. Los scriptlets están prohibidos por configuración (scripting-invalid).", "WEB-INF/jsp/*, web.xml"],
  ["10 – Métodos HTTP", "GET para consultar (listas, formularios, búsqueda y cálculo); POST para modificar (guardar, eliminar, iniciar, finalizar, login, logout); PRG tras cada POST; 400 ante acciones desconocidas; 403 por perfil.", "Todos los servlets"],
 ]),
 ("salto", ""),
 ("h1", "Parte II – Flujos principales"),
 ("h2", "Inicio de sesión y «recordarme»"),
 ("li", "El usuario abre <i>/logistica/</i>: index.jsp redirige a /inicio; el filtro no ve sesión ni cookie y lo manda a /login."),
 ("li", "POST /login: se busca el usuario, se verifica la contraseña contra el hash PBKDF2, se cambia el id de sesión y se guarda el usuario en la Session."),
 ("li", "Si tildó «Recordarme»: se genera un token aleatorio, se guarda en la tabla <i>sesion_recordada</i> con vencimiento a 30 días y se envía en la cookie RECORDARME (HttpOnly, SameSite=Lax)."),
 ("li", "Si luego se pierde la Session (cierra el navegador, expira), el filtro lee la cookie, valida el token en la base y reconstruye la Session: no pide la contraseña."),
 ("h2", "Cierre de sesión"),
 ("li", "POST /logout: elimina el token de la base, invalida la Session, expira la cookie RECORDARME y JSESSIONID y redirige al login. El botón «Atrás» no muestra páginas privadas (Cache-Control: no-store)."),
 ("h2", "Carga de un viaje (administrador)"),
 ("li", "GET /admin/viajes?accion=nuevo: se ingresa el DNI. Si no existe: aviso «No existe ningún chofer con DNI …»."),
 ("li", "Si existe: se muestran los camiones que tiene autorizados, que entran en su categoría y que no están en un viaje ASIGNADO o EN_CURSO (procedure)."),
 ("li", "Se eligen camión, origen y destino. «Calcular» (GET) muestra distancia, días (km/200, hacia arriba), litros y tanques (litros/capacidad, hacia arriba)."),
 ("li", "«Confirmar» (POST): el servidor vuelve a buscar el chofer, verifica la disponibilidad del camión, recalcula y guarda en una transacción con el camión bloqueado. Se redirige al listado."),
 ("h2", "Trabajo del chofer"),
 ("li", "GET /chofer/viajes: lista solo sus viajes. «Iniciar viaje» (POST) pasa ASIGNADO → EN_CURSO (solo si no tiene otro en curso). «Marcar como realizado» (POST) pasa EN_CURSO → FINALIZADO y el camión queda libre."),
]

CAPITULOS_FINALES = [
 ("h1", "Parte IV – Defensa oral: preguntas frecuentes"),
 ("q", "¿Por qué separar en dos proyectos (DAO y MVC)?"),
 ("p", "Es lo que pide el enunciado y además baja el acoplamiento: el proyecto DAO no conoce servlets ni JSP, se puede probar solo (tiene tests unitarios) y se podría reutilizar con otra interfaz. La dependencia va en un solo sentido: web → dao."),
 ("q", "¿Por qué una interfaz DAO y una Factory si solo hay una implementación?"),
 ("p", "Porque los controladores dependen de una abstracción. Si se cambia JDBC por otra tecnología (JPA, otra base) se crea otra fábrica y los controladores no cambian. También permite reemplazar el DAO por un falso en pruebas."),
 ("q", "¿Por qué el Singleton usa una clase interna (holder)?"),
 ("p", "Porque es la forma más simple de tener inicialización perezosa y segura entre hilos sin synchronized: la JVM garantiza que la clase Holder se carga una sola vez, cuando se usa por primera vez. Un servidor web atiende muchos hilos a la vez, así que la seguridad entre hilos es importante."),
 ("q", "¿Por qué el Singleton entrega conexiones nuevas en lugar de compartir una?"),
 ("p", "Una Connection JDBC no está pensada para usarse desde varios hilos a la vez, y compartirla mezclaría transacciones de distintos usuarios. Se abre una por operación y se cierra con try-with-resources. En producción se usaría un pool de conexiones (por ejemplo un DataSource de Tomcat) sin cambiar los DAO: es una mejora conocida."),
 ("q", "¿Cuándo usaste Statement, PreparedStatement y CallableStatement y por qué?"),
 ("p", "<b>Statement</b> solo en consultas fijas sin datos del usuario (listar camiones, choferes y distancias). <b>PreparedStatement</b> en todo lo que recibe valores (alta, baja, modificación, login, búsquedas), porque los parámetros ? evitan la <b>inyección SQL</b>. <b>CallableStatement</b> para invocar los stored procedures <i>sp_camiones_disponibles</i> (regla de disponibilidad en un único lugar) y <i>sp_finalizar_viaje</i> (con parámetro OUT que informa cuántas filas cambió)."),
 ("q", "¿Qué transacciones hay y por qué?"),
 ("p", "<b>Alta de chofer</b>: inserta en chofer, chofer_camion y usuario; si falla cualquiera, rollback y no queda un chofer sin usuario. <b>Modificación de chofer</b>: actualiza, borra y reinserta autorizaciones. <b>Alta de viaje</b>: bloquea el camión con SELECT FOR UPDATE, verifica que siga libre e inserta; así dos administradores no pueden asignar el mismo camión a la vez. <b>Iniciar viaje</b>: verifica que no haya otro en curso y actualiza. <b>Guardar token</b>: limpia vencidos e inserta. El patrón es siempre setAutoCommit(false), commit al final, rollback en el catch, y volver a autocommit y cerrar en el finally."),
 ("q", "¿Cómo se calcula el tiempo y la cantidad de tanques?"),
 ("p", "Tiempo = techo(km / 200). Ejemplo: CABA–Córdoba = 646 km → 3,23 → <b>4 días</b>. Tanques = techo((km × litros por km) / capacidad del tanque). Ejemplo: con un camión de 0,4 l/km y tanque de 600 l, 646 km consumen 258,4 l → 0,43 → <b>1 tanque</b>. Se redondea hacia arriba porque un viaje no termina a mitad de día y hay que cargar el último tanque aunque se use parcialmente. El cálculo está en CalculadoraViaje, tiene tests, y se hace en el servidor."),
 ("q", "¿Cómo se sabe qué camiones puede manejar un chofer y cuáles están disponibles?"),
 ("p", "El procedure <i>sp_camiones_disponibles</i> une chofer_camion (autorización), categoría (las toneladas del camión no superan las de la categoría) y descarta con NOT EXISTS los camiones que tengan un viaje ASIGNADO o EN_CURSO. Además Chofer.puedeManejar() valida lo mismo en el modelo, y la base bloquea la doble asignación con la transacción."),
 ("q", "¿Cómo funciona la sesión recordada y qué seguridad tiene?"),
 ("p", "La cookie no guarda la contraseña sino un token aleatorio de 256 bits que está registrado en la base con vencimiento. Es HttpOnly (JavaScript no la lee), SameSite=Lax y Secure en HTTPS. Al cerrar sesión se borra el token de la base, se invalida la Session y se expiran ambas cookies; aunque alguien copiara el token, ya no sirve."),
 ("q", "¿Cómo se guardan las contraseñas?"),
 ("p", "Nunca en texto plano: PBKDF2-HMAC-SHA256 con sal aleatoria por usuario y 65.536 iteraciones; se guarda «iteraciones$sal$hash». La comparación es en tiempo constante. El login responde con el mismo mensaje si falla usuario o contraseña."),
 ("q", "¿Por qué la baja es un POST y no un DELETE?"),
 ("p", "Los formularios HTML solo envían GET o POST. Se usa POST con accion=eliminar y, como toda modificación, va seguido de un redirect (PRG). Las consultas son GET porque son seguras e idempotentes: se pueden recargar, guardar en favoritos y no cambian datos."),
 ("q", "¿Qué es el patrón Post/Redirect/Get y por qué lo usan?"),
 ("p", "Después de un POST exitoso el servidor responde con un redirect y el navegador hace un GET. Si el usuario recarga (F5), repite el GET y no el POST: no se duplican altas ni viajes."),
 ("q", "¿Por qué los servlets Login/Logout están en web.xml y los demás con anotaciones?"),
 ("p", "El enunciado pide usar ambas formas. Login, Logout y el filtro de seguridad son infraestructura y quedan visibles en un solo archivo; los controladores de negocio usan @WebServlet, que deja la URL junto al código. web.xml además define sesión, páginas de error, welcome-file y prohíbe scriptlets."),
 ("q", "¿Cómo evitás XSS e inyección SQL?"),
 ("p", "SQL: PreparedStatement con parámetros. XSS: toda salida de datos va con c:out o fn:escapeXml, y el mensaje del servidor se pasa al JavaScript como atributo data- escapado (no se concatena HTML)."),
 ("q", "¿Qué pasa si un chofer intenta entrar a /admin o tocar un viaje ajeno?"),
 ("p", "El filtro devuelve 403 para /admin si no es ADMIN. Para viajes, el id del chofer sale de la Session y el UPDATE incluye «AND chofer_id = ?»: si el viaje es ajeno no se modifica ninguna fila y se informa el error."),
 ("q", "¿Cómo están organizados los comentarios y la legibilidad (lo que evalúa el profesor)?"),
 ("p", "Cada clase tiene su Javadoc con el propósito, los métodos de negocio están comentados con la regla que implementan, los nombres son descriptivos en español del dominio, no hay números mágicos (constantes), cada método hace una sola cosa y no hay duplicación importante (BaseServlet, Mapeadores, JdbcUtil)."),
 ("h1", "Supuestos y limitaciones (dicho con honestidad)"),
 ("li", "<b>Toneladas por categoría</b> (A=10, B=20, C=30, D=40): el enunciado no las define; son un supuesto, fácil de cambiar en el enum Categoria y en la tabla categoria."),
 ("li", "<b>Tiempo de viaje</b> se expresa en días de 200 km, tal como indica el enunciado; no se modelan horas de descanso ni feriados."),
 ("li", "<b>Usuario de chofer = DNI</b>; la contraseña inicial la define el administrador. No hay pantalla de cambio de contraseña."),
 ("li", "<b>Sin protección CSRF</b> con token: se mitiga con cookies SameSite=Lax y porque las acciones que modifican son POST, pero un sistema real debería agregar un token CSRF en cada formulario."),
 ("li", "<b>Sin pool de conexiones</b>: se abre una conexión por operación. Para producción convendría un DataSource con pool."),
 ("li", "<b>Bootstrap y SweetAlert se cargan desde CDN</b>: requieren Internet; sin ellos la aplicación funciona igual, con estilos y avisos más simples."),
 ("li", "<b>Base probada</b>: el script está escrito para MySQL 8. En el entorno donde se desarrolló no había un servidor MySQL, por lo que todas las pruebas manuales se hicieron contra MariaDB 10.11 (compatible) con el mismo driver de MySQL. Se recomienda ejecutar el script en MySQL 8 antes de entregar."),
 ("li", "Se probaron manualmente con un Tomcat embebido: login correcto e incorrecto, sesión recordada, logout, ABM de camiones y choferes (incluyendo duplicados, categoría insuficiente y rollback), carga de viaje completa, camión ocupado, iniciar y finalizar, acceso de chofer a /admin (403) y chofer intentando tocar un viaje ajeno. No se verificó visualmente el aspecto en un navegador."),
 ("h1", "Cómo ejecutar el proyecto"),
 ("li", "Ejecutar <b>db/01_ddl_logistica.sql</b> y luego <b>db/02_datos_iniciales.sql</b> en MySQL 8."),
 ("li", "Ajustar usuario y clave de la base en <b>logistica-dao/src/main/resources/db.properties</b> (o variables DB_USER y DB_PASSWORD)."),
 ("li", "<b>mvn clean package</b> en la raíz: genera <b>logistica-web/target/logistica.war</b>."),
 ("li", "Copiar el WAR a la carpeta webapps de <b>Tomcat 10.1</b> y abrir <b>http://localhost:8080/logistica/</b>."),
 ("li", "Usuarios de prueba: admin / admin123; 30111222 / chofer123; 28555666 / chofer123."),
]
