# Explicaciones: implementaciones JDBC
J = "logistica-dao/src/main/java/ar/edu/usal/logistica/dao/jdbc/"
EXPLICACIONES = {
J + "ConexionDB.java": {
 "rol": "Entrega conexiones a MySQL y guarda la configuración.",
 "defensa": "Patrón <b>Singleton</b> (punto 01): existe una única instancia, que lee db.properties una sola vez. Uso el <i>holder idiom</i> (clase interna estática) porque es seguro entre hilos sin necesidad de synchronized y carga la instancia recién cuando se usa. Cada DAO pide una conexión nueva y la cierra con try-with-resources: en una aplicación web varios hilos atienden a la vez y una conexión compartida sería insegura. En producción se reemplazaría por un pool de conexiones (DataSource), sin cambiar a los DAO.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación del patrón Singleton."),
  ("public final class ConexionDB", "Clase final. La clase interna <b>Holder</b> crea la única instancia de forma perezosa y thread-safe. Atributos: url, usuario y clave."),
  ("private ConexionDB()", "Constructor <b>privado</b>: nadie más puede crear instancias. Carga db.properties desde el classpath; si falta, falla con un mensaje claro. Class.forName carga el driver."),
  ("// Las variables de entorno", "Si existen las variables DB_URL, DB_USER o DB_PASSWORD, tienen prioridad sobre el archivo."),
  ("public static ConexionDB getInstance", "Punto de acceso global a la única instancia."),
  ("/** Abre una conexion", "getConexion(): pide una conexión nueva a DriverManager; si falla, lanza DAOException (error técnico encapsulado). Quien la pide debe cerrarla."),
  ("private static String valor", "Auxiliar: devuelve la variable de entorno si existe y no está vacía; si no, el valor por defecto."),
 ]},
J + "JdbcDAOFactory.java": {
 "rol": "Fábrica concreta que entrega los DAO JDBC.",
 "defensa": "Implementa el patrón Factory. Es <b>final</b> y singleton (la fábrica no tiene estado); los DAO son clases de paquete (no públicas): desde afuera solo se accede por las interfaces, lo que refuerza el encapsulamiento.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Fabrica concreta", "Clase final con su única instancia y constructor privado."),
  ("@Override", "Cada método getXxxDAO() devuelve una implementación nueva. Los DAO no guardan estado (abren y cierran su conexión en cada operación), por eso crear uno nuevo es barato y seguro."),
 ]},
J + "JdbcUtil.java": {
 "rol": "Utilidades compartidas por los DAO: códigos de error y cierre seguro de transacciones.",
 "defensa": "Evita repetir código (DRY). Traducir los códigos de error de MySQL (1062 duplicado, 1451/1452 clave foránea) permite dar mensajes de negocio claros («ya existe un chofer con ese DNI») en lugar de errores técnicos. Dejar que la base detecte el duplicado es más seguro que preguntar antes (evita condiciones de carrera entre dos usuarios).",
 "bloques": [
  ("", "Paquete."),
  ("import java.sql", "@imports"),
  ("/** Utilidades", "Clase de utilidades con los códigos de error de MySQL que nos interesan y constructor privado."),
  ("static boolean esDuplicado", "Predicados que reconocen un valor duplicado y una violación de clave foránea."),
  ("/** Deshace la transaccion", "rollbackSilencioso: intenta deshacer la transacción; si el rollback también falla, el error se agrega como <i>suppressed</i> de la causa original, sin ocultarla."),
  ("/** Devuelve la conexion", "cerrar: devuelve la conexión a autocommit y la cierra. Se usa en <b>finally</b> para garantizar que nunca quede una conexión abierta."),
 ]},
J + "Mapeadores.java": {
 "rol": "Convierte filas del ResultSet en objetos Camion y Chofer.",
 "defensa": "Un solo lugar para el mapeo objeto-relacional manual. El parámetro <i>prefijo</i> permite leer columnas con alias cuando una consulta une tablas (ch_nombre, c_marca).",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación."),
  ("static Camion camion", "Crea un Camion leyendo las siete columnas (con el prefijo indicado)."),
  ("static Chofer chofer", "Crea un Chofer: la fecha SQL se convierte a LocalDate y el texto de la categoría al enum con Categoria.valueOf."),
 ]},
J + "CamionDAOJdbc.java": {
 "rol": "Implementación JDBC del DAO de camiones.",
 "defensa": "Usa los <b>tres</b> mecanismos JDBC pedidos (punto 06): <b>Statement</b> en listarTodos (consulta fija, sin parámetros), <b>PreparedStatement</b> en alta, baja, modificación y búsqueda (parámetros con ? que evitan la inyección SQL y se compilan una vez) y <b>CallableStatement</b> en listarDisponiblesParaChofer (llama al stored procedure). Todos los recursos se cierran solos con try-with-resources (punto 02/05).",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Implementacion JDBC", "Clase de paquete (no pública) y las sentencias SQL como constantes: INSERT, UPDATE, DELETE y SELECT por id con parámetros <b>?</b> y un SELECT fijo para el listado."),
  ("public void insertar", "<b>PreparedStatement</b> para el alta. Primero valida el camión. RETURN_GENERATED_KEYS pide el id autoincremental que generó MySQL y se lo asigna al objeto."),
  ("throw traducir(e, camion, \"No se pudo guardar", "Si la base rechaza la operación, traducir() decide: dominio duplicado → mensaje de negocio."),
  ("public void actualizar", "UPDATE por id. Si no modificó ninguna fila, el camión no existe y se informa."),
  ("public void eliminar", "DELETE por id. Si el camión tiene viajes, la clave foránea de la base lo impide y se traduce a «tiene viajes registrados»."),
  ("public Camion buscarPorId", "SELECT por id: devuelve el camión o null."),
  ("public List<Camion> listarTodos", "Acá se usa <b>Statement</b>: la consulta es fija y no recibe datos del usuario, por eso no hay riesgo de inyección."),
  ("public List<Camion> listarDisponiblesParaChofer", "Usa <b>CallableStatement</b> con la sintaxis <i>{call sp_camiones_disponibles(?)}</i>. La regla de disponibilidad queda en la base, en un solo lugar."),
  ("private DAOException traducir", "Traduce el error de duplicado en ValidacionException; cualquier otro error pasa a DAOException."),
 ]},
J + "UsuarioDAOJdbc.java": {
 "rol": "Implementación JDBC de usuarios y tokens de sesión recordada.",
 "defensa": "guardarToken usa una transacción porque son dos sentencias que deben ir juntas (limpiar tokens vencidos + insertar el nuevo). Las fechas se comparan con la hora de Java para no depender de la hora del servidor de base.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Implementacion JDBC", "Consultas: usuario por nombre y usuario por token vigente (JOIN con sesion_recordada y expira &gt; ahora)."),
  ("public Usuario buscarPorUsername", "PreparedStatement: busca por username; devuelve null si no existe."),
  ("public void guardarToken", "Transacción: desactiva autocommit, borra los tokens vencidos, inserta el nuevo y confirma con commit; ante error hace rollback."),
  ("public Usuario buscarPorToken", "Devuelve el usuario dueño de un token que todavía no venció."),
  ("public void eliminarToken", "Borra el token (logout): ya no se puede reutilizar aunque alguien lo copie."),
  ("private Usuario mapear", "Convierte la fila en Usuario. chofer_id puede ser NULL (administrador): se usa wasNull() para distinguir null de 0."),
 ]},
J + "DistanciaDAOJdbc.java": {
 "rol": "Consulta de la tabla de distancias.",
 "defensa": "Si no hay distancia (o origen = destino) se informa con una ValidacionException clara; nunca se asume un valor por defecto que generaría cálculos erróneos.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Implementacion JDBC", "Clase de paquete."),
  ("public int obtenerKm", "Valida que haya origen y destino distintos. PreparedStatement con dos parámetros; si hay fila devuelve los km."),
  ("throw new ValidacionException(\"No hay distancia", "Si la consulta no devolvió fila, avisa que no hay distancia cargada."),
  ("public Map<Destino", "Devuelve la tabla completa como Map de Map con EnumMap (eficiente para enums). Usa <b>Statement</b> porque la consulta es fija."),
 ]},
J + "ChoferDAOJdbc.java": {
 "rol": "Implementación JDBC del DAO de choferes, con transacciones.",
 "defensa": "Punto 05 (transacciones JDBC): dar de alta un chofer toca tres tablas (chofer, chofer_camion y usuario). Con <b>setAutoCommit(false)</b> + commit/rollback, o se guarda todo o no se guarda nada: nunca queda un chofer sin usuario ni autorizaciones a medias. La consulta de lectura usa LEFT JOIN y agrupa las filas en Java: una sola consulta en vez de una por chofer (evita el problema N+1).",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Implementacion JDBC", "Consulta base con LEFT JOIN: chofer + camiones autorizados (alias ch_ y c_). LEFT JOIN para que también aparezcan los choferes sin camiones. Siguen los INSERT/UPDATE de cada tabla."),
  ("public void insertar", "Valida el chofer y que la contraseña inicial tenga al menos 6 caracteres. Abre la conexión y <b>empieza la transacción</b>."),
  ("try (PreparedStatement ps = con.prepareStatement(INSERT_CHOFER", "Paso 1: inserta el chofer y recupera su id generado."),
  ("guardarAutorizaciones(con, chofer);", "Paso 2: inserta las autorizaciones."),
  ("// El usuario del chofer se llama", "Paso 3: crea el usuario con username = DNI y la contraseña <b>hasheada</b>."),
  ("con.commit();", "Si los tres pasos salieron bien, <b>confirma</b> (commit). Las líneas del <i>catch</i> que siguen hacen rollback si algo falló."),
  ("chofer.setId(null);", "Si algo falló, <b>deshace todo</b> (rollback), limpia el id y traduce el error. El finally siempre cierra la conexión."),
  ("public void actualizar", "También transaccional: actualiza el chofer, borra sus autorizaciones anteriores, inserta las nuevas y sincroniza el username con el DNI. Si no existe, lanza ValidacionException y hace rollback."),
  ("public void eliminar", "Un solo DELETE: las claves foráneas con ON DELETE CASCADE eliminan usuario y autorizaciones. Si hay viajes, la base lo impide y se informa con un mensaje claro."),
  ("public Chofer buscarPorId", "Búsqueda por id usando la consulta base."),
  ("public Chofer buscarPorDni", "Búsqueda por DNI; si no hay resultado lanza <b>ChoferNoEncontradoException</b> (requisito del enunciado)."),
  ("public List<Chofer> listarTodos", "Listado con <b>Statement</b> (consulta fija)."),
  ("private List<Chofer> leer", "Agrupa las filas del LEFT JOIN: varias filas del mismo chofer son varios camiones. Un LinkedHashMap conserva el orden y evita duplicar choferes. Si c_id es NULL, el chofer no tiene camiones."),
  ("private void cargarDatos", "Carga los seis parámetros comunes de INSERT y UPDATE (evita repetirlos)."),
  ("private void guardarAutorizaciones", "Inserta todas las autorizaciones con un <b>batch</b> (una sola ida a la base)."),
  ("private DAOException traducir", "Traduce DNI duplicado y camión inexistente a mensajes de negocio."),
 ]},
J + "ViajeDAOJdbc.java": {
 "rol": "Implementación JDBC del DAO de viajes.",
 "defensa": "Es el DAO con más reglas de concurrencia. <b>insertar</b> bloquea la fila del camión con <i>SELECT … FOR UPDATE</i>: si dos administradores asignan el mismo camión a la vez, el segundo espera y luego ve que ya está ocupado (no hay doble asignación). <b>iniciar</b> usa transacción para verificar que el chofer no tenga otro viaje en curso. <b>finalizar</b> usa un stored procedure con parámetro OUT (CallableStatement). Todas las actualizaciones incluyen chofer_id en el WHERE: un chofer no puede modificar viajes ajenos.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Implementacion JDBC", "Consulta base con JOIN de viaje, chofer y camión (alias ch_ y c_), orden por fecha descendente y el INSERT del viaje."),
  ("public void insertar", "Valida el viaje (regla de dominio) y abre la transacción."),
  ("// Se bloquea la fila del camion", "Bloquea la fila del camión (FOR UPDATE) y verifica que exista."),
  ("// Con el camion bloqueado", "Con el camión bloqueado, cuenta los viajes ASIGNADO/EN_CURSO: si hay alguno, lanza ValidacionException."),
  ("try (PreparedStatement ps = con.prepareStatement(INSERT, ", "Inserta el viaje con los resultados del cálculo y recupera su id."),
  ("con.commit();", "Confirma la transacción (commit). Si alguna línea anterior falló, el catch de abajo hace rollback."),
  ("throw new DAOException(\"No se pudo guardar el viaje.\"", "Ante error técnico o de negocio hace rollback y propaga la excepción adecuada; finally cierra la conexión."),
  ("public List<Viaje> listarTodos", "Lista todos los viajes (vista del administrador) con PreparedStatement."),
  ("public List<Viaje> listarPorChofer", "Lista solo los viajes del chofer indicado (vista del chofer)."),
  ("public void iniciar", "Transacción para iniciar un viaje."),
  ("// Un chofer no puede tener", "Regla: un chofer no puede tener dos viajes en curso."),
  ("\"UPDATE viaje SET estado = 'EN_CURSO'", "El UPDATE solo afecta un viaje del chofer y en estado ASIGNADO; si no modificó ninguna fila, informa el motivo."),
  ("public void finalizar", "<b>CallableStatement</b>: llama a sp_finalizar_viaje con dos parámetros de entrada y registra el tercero como <b>OUT</b> (entero). Si el procedimiento modificó 0 filas, el viaje no correspondía."),
  ("private List<Viaje> leer", "Convierte cada fila en un Viaje completo: estimación, chofer, camión, enums y fechas."),
  ("private LocalDateTime aFecha", "Convierte Timestamp a LocalDateTime cuidando el null (fechas de inicio/fin aún vacías)."),
 ]},
}
