# Explicaciones: vistas JSP/JSTL, JS y CSS
V = "logistica-web/src/main/webapp/"
J = V + "WEB-INF/jsp/"
EXPLICACIONES = {
V + "index.jsp": {
 "rol": "Página de bienvenida (welcome-file de web.xml).",
 "defensa": "Permite entrar con http://host:puerto/logistica/ (path root con contexto). Redirige a /inicio; el filtro manda al login si no hay sesión.",
 "bloques": [
  ("", "Importa JSTL core."),
  ("<%-- Pagina de bienvenida", "Comentario JSP (no llega al navegador) y <b>c:redirect</b> a /inicio."),
 ]},
J + "comun/taglibs.jspf": {
 "rol": "Declaración única de las tres librerías JSTL, incluida al comienzo de cada JSP.",
 "defensa": "Evita repetir las directivas en cada página y respeta que el taglib se declare antes de usarse. JSTL (punto 09) reemplaza a los scriptlets, que además están prohibidos en web.xml.",
 "bloques": [
  ("", "Comentario."),
  ("prefix=\"c\"", "<b>c</b>: core (if, choose, forEach, set, out, redirect)."),
  ("prefix=\"fmt\"", "<b>fmt</b>: formato de números y locale."),
  ("prefix=\"fn\"", "<b>fn</b>: funciones (escapeXml)."),
 ]},
J + "comun/encabezado.jspf": {
 "rol": "Encabezado común: head HTML, barra de navegación según el perfil y aviso del servidor.",
 "defensa": "Una sola plantilla para todas las pantallas (evita copiar y pegar). Toda salida de datos del usuario va con <b>c:out</b> o <b>fn:escapeXml</b> (escape de HTML): protege contra XSS. El botón «Cerrar sesión» es un formulario POST.",
 "bloques": [
  ("", "Comentario y variable <b>ctx</b> con el contexto de la aplicación (para armar URLs)."),
  ("<fmt:setLocale", "Fija el formato numérico argentino (coma decimal), independiente del navegador."),
  ("<c:set var=\"avisoTipo\"", "Toma el mensaje de la request (forward) o de la Session (redirect) y luego <b>borra</b> el de la Session para que se muestre una sola vez."),
  ("<!DOCTYPE html>", "Inicio del HTML: idioma, codificación, viewport responsive, título y estilos (Bootstrap desde CDN + CSS propio)."),
  ("<body>", "Si hay usuario en Session, muestra la barra de navegación."),
  ("<c:choose>", "Menú por perfil: el administrador ve Viajes, Choferes y Camiones; el chofer, solo «Mis viajes»."),
  ("<span class=\"navbar-text", "Muestra usuario y rol (escapados con c:out) y el formulario POST de cierre de sesión."),
  ("<main class=\"container", "Abre el contenido y define el div oculto con el aviso del servidor: tipo y texto en atributos data-, escapados con fn:escapeXml. El JS los lee y los muestra con SweetAlert."),
 ]},
J + "comun/pie.jspf": {
 "rol": "Pie común.",
 "defensa": "Carga los scripts al final (la página se dibuja primero). SweetAlert y el JS propio son opcionales: sin ellos todo funciona con los formularios y avisos de Bootstrap.",
 "bloques": [
  ("", "Comentario."),
  ("</main>", "Cierra el contenido principal."),
  ("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap", "Scripts: Bootstrap, SweetAlert2 y el app.js propio; cierra body y html."),
 ]},
J + "login.jsp": {
 "rol": "Pantalla de inicio de sesión (la pantalla principal del enunciado).",
 "defensa": "Formulario <b>POST</b> (las credenciales no viajan en la URL). Incluye la casilla «Recordarme» que activa la cookie. El usuario escrito se vuelve a mostrar con c:out (escapado) si falla el login.",
 "bloques": [
  ("", "Directiva de página (UTF-8) e importación de JSTL; define el título de la página."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/encabezado.jspf\"", "Incluye el encabezado común."),
  ("<div class=\"card card-login", "Tarjeta centrada con el título."),
  ("<form action=", "Formulario que envía por POST a /login."),
  ("<label for=\"username\"", "Campo usuario: obligatorio, largo máximo 30, con foco automático."),
  ("<label for=\"password\"", "Campo contraseña (type=password oculta lo escrito)."),
  ("<div class=\"form-check", "Casilla «Recordarme en este equipo» (marcada por defecto)."),
  ("<button type=\"submit\"", "Botón de ingreso y cierre de tarjeta."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/pie.jspf\"", "Incluye el pie común."),
 ]},
J + "error.jsp": {
 "rol": "Página de error única (403, 404 y errores inesperados).",
 "defensa": "Nunca se muestra un stack trace al usuario (seguridad y presentación). El detalle técnico queda en el log del servidor.",
 "bloques": [
  ("", "Directiva marcada <b>isErrorPage</b> para acceder a los datos del error; define el título."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/encabezado.jspf\"", "Encabezado común."),
  ("<div class=\"text-center", "Según el código de estado muestra un mensaje distinto: acceso denegado, página no encontrada o error inesperado."),
  ("<a class=\"btn btn-primary\"", "Botón para volver al inicio."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/pie.jspf\"", "Pie común."),
 ]},
J + "admin/camiones/lista.jsp": {
 "rol": "Listado de camiones.",
 "defensa": "Usa JSTL: <b>c:forEach</b> para recorrer, <b>c:out</b> para escapar, <b>fmt:formatNumber</b> para números, <b>c:if</b> para el mensaje de lista vacía. «Editar» es un enlace (GET, consulta); «Eliminar» es un formulario POST con confirmación (data-confirmar).",
 "bloques": [
  ("", "Directiva, JSTL, título y encabezado."),
  ("<div class=\"d-flex", "Título y botón «Nuevo camión»."),
  ("<table class=\"table", "Tabla con sus columnas."),
  ("<c:forEach var=\"camion\"", "Una fila por camión, con los datos escapados y números formateados."),
  ("<a class=\"btn btn-sm btn-outline-primary\"", "Enlace de edición (GET con el id)."),
  ("<form action=\"${ctx}/admin/camiones\" method=\"post\"", "Formulario POST de baja; <i>data-confirmar</i> hace que el JS pida confirmación con SweetAlert."),
  ("<c:if test=\"${empty camiones}\">", "Mensaje cuando no hay camiones."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/pie.jspf\"", "Pie común."),
 ]},
J + "admin/camiones/form.jsp": {
 "rol": "Formulario de alta y edición de camiones.",
 "defensa": "El mismo formulario sirve para alta y edición (si hay id es edición). Validaciones HTML (required, min, max, step) como ayuda al usuario, <b>además</b> de las del servidor. Los valores se rellenan desde el Map «valores» con c:out.",
 "bloques": [
  ("", "Directiva, JSTL, título y encabezado."),
  ("<h1 class=\"h3 mb-3\">", "El título cambia según sea alta o edición."),
  ("<form action=", "Formulario POST con accion=guardar e id oculto (vacío en alta)."),
  ("<label for=\"marca\"", "Marca y modelo."),
  ("<label for=\"dominio\"", "Dominio (se normaliza en mayúsculas en el servidor)."),
  ("<label for=\"toneladasMaximas\"", "Toneladas máximas."),
  ("<label for=\"capacidadTanqueLitros\"", "Capacidad del tanque en litros."),
  ("<label for=\"consumoLitrosPorKm\"", "Consumo en litros por km."),
  ("<div class=\"col-12 d-flex gap-2\">", "Botones Guardar y Cancelar."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/pie.jspf\"", "Pie común."),
 ]},
J + "admin/choferes/lista.jsp": {
 "rol": "Listado de choferes con sus camiones autorizados.",
 "defensa": "Igual criterio que el listado de camiones. Muestra los camiones autorizados con un c:forEach anidado.",
 "bloques": [
  ("", "Directiva, JSTL, título y encabezado."),
  ("<div class=\"d-flex", "Título y botón «Nuevo chofer»."),
  ("<table class=\"table", "Tabla y encabezados de columnas."),
  ("<c:forEach var=\"chofer\"", "Una fila por chofer: nombre, DNI, fecha, categoría, celular."),
  ("<c:forEach var=\"camion\"", "Bucle anidado: un distintivo por camión autorizado (o «Ninguno»)."),
  ("<a class=\"btn btn-sm btn-outline-primary\"", "Editar (GET)."),
  ("<form action=\"${ctx}/admin/choferes\" method=\"post\"", "Eliminar (POST con confirmación)."),
  ("<c:if test=\"${empty choferes}\">", "Mensaje de lista vacía."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/pie.jspf\"", "Pie común."),
 ]},
J + "admin/choferes/form.jsp": {
 "rol": "Formulario de alta y edición de choferes.",
 "defensa": "La contraseña inicial solo se pide en el alta. Los camiones se eligen con casillas; la categoría determina cuáles serán aceptados (lo valida el servidor). Patrones HTML (pattern) para DNI y celular ayudan al usuario pero no reemplazan la validación del servidor.",
 "bloques": [
  ("", "Directiva, JSTL, título, encabezado, y variable que indica si es alta."),
  ("<h1 class=\"h3 mb-3\">", "Título según alta o edición."),
  ("<form action=", "Formulario POST accion=guardar con id oculto."),
  ("<label for=\"nombre\"", "Nombre y apellido."),
  ("<label for=\"dni\"", "DNI (7 u 8 dígitos)."),
  ("<label for=\"fechaNacimiento\"", "Fecha de nacimiento (input date)."),
  ("<label for=\"telefono\"", "Celular (solo números)."),
  ("<label for=\"categoria\"", "Lista desplegable generada con c:forEach; marca como seleccionada la actual."),
  ("<c:if test=\"${esNuevo}\">", "Contraseña inicial (solo alta)."),
  ("<label class=\"form-label\">Camiones", "Casillas de los camiones autorizados: marcadas las ya seleccionadas."),
  ("<div class=\"col-12 d-flex gap-2\">", "Botones Guardar y Cancelar."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/pie.jspf\"", "Pie común."),
 ]},
J + "admin/viajes/lista.jsp": {
 "rol": "Listado de todos los viajes (pantalla inicial del administrador).",
 "defensa": "Muestra el resultado del cálculo guardado (km, días, tanques) y el estado con un color: verde finalizado, amarillo en curso, gris asignado (c:choose).",
 "bloques": [
  ("", "Directiva, JSTL, título y encabezado."),
  ("<div class=\"d-flex", "Título y botón «Cargar viaje»."),
  ("<table class=\"table", "Tabla de viajes y sus encabezados."),
  ("<c:forEach var=\"viaje\"", "Una fila por viaje: id, chofer, camión, recorrido."),
  ("<td class=\"text-end\">${viaje.estimacion.distanciaKm()}", "Km, días y tanques (los accesores de EstimacionViaje se llaman como métodos en EL)."),
  ("<c:choose>", "Color del estado."),
  ("<td><c:out value=\"${viaje.fechaCargaFormateada}\"/>", "Fecha de carga."),
  ("<c:if test=\"${empty viajes}\">", "Mensaje de lista vacía."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/pie.jspf\"", "Pie común."),
 ]},
J + "admin/viajes/nuevo.jsp": {
 "rol": "Pantalla de carga de viajes en tres pasos.",
 "defensa": "Un solo JSP que muestra cada paso según los datos presentes. Pasos 1 y 2 son <b>GET</b> (solo consultan); el paso 3 confirma por <b>POST</b> (modifica). La confirmación reenvía solo ids y códigos; el servidor recalcula todo. También muestra la tabla de distancias del enunciado, leída de la base.",
 "bloques": [
  ("", "Directiva, JSTL, título y encabezado."),
  ("<h1 class=\"h3 mb-3\">Cargar viaje", "Título."),
  ("<div class=\"card shadow-sm mb-3\">\n", "Paso 1."),
  ("<form action=\"${ctx}/admin/viajes\" method=\"get\" class=\"row g-2\">", "Formulario de búsqueda por DNI (GET). El campo solo acepta 7 u 8 dígitos."),
  ("<c:if test=\"${not empty chofer}\">", "Si se encontró el chofer muestra su nombre, categoría y celular."),
  ("<c:if test=\"${not empty chofer and not empty camiones}\">", "Paso 2: solo aparece si hay chofer con camiones disponibles."),
  ("<label for=\"camionId\"", "Lista de camiones disponibles de ese chofer."),
  ("<label for=\"origen\"", "Lista de orígenes (enum Destino)."),
  ("<label for=\"destino\"", "Lista de destinos."),
  ("<c:if test=\"${not empty viaje}\">", "Paso 3: solo aparece si ya se calculó el viaje."),
  ("<dl class=\"row resumen-viaje", "Resumen del cálculo: recorrido, distancia, días, litros y tanques."),
  ("<form action=\"${ctx}/admin/viajes\" method=\"post\"", "Formulario de confirmación por POST con campos ocultos (DNI, camión, origen, destino) y confirmación con SweetAlert."),
  ("<%-- Tabla de distancias", "Tabla de distancias: recorre filas y columnas de destinos y consulta tabla[fila][columna]; la diagonal queda gris."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/pie.jspf\"", "Pie común."),
 ]},
J + "chofer/mis-viajes.jsp": {
 "rol": "Pantalla del perfil chofer.",
 "defensa": "Muestra tarjetas con los viajes del chofer y solo los botones que corresponden al estado: «Iniciar» si está asignado y «Marcar como realizado» si está en curso (puedeIniciarse()/puedeFinalizarse() del modelo: la vista no repite reglas). Ambos botones son POST con confirmación.",
 "bloques": [
  ("", "Directiva, JSTL, título y encabezado."),
  ("<h1 class=\"h3 mb-3\">Mis viajes", "Título y contenedor de tarjetas."),
  ("<c:forEach var=\"viaje\"", "Una tarjeta por viaje con el recorrido."),
  ("<c:choose>", "Color del estado."),
  ("<ul class=\"list-unstyled", "Datos del viaje: camión, distancia y días, tanques, fechas."),
  ("<c:if test=\"${viaje.puedeIniciarse()}\">", "Botón «Iniciar viaje» (POST)."),
  ("<c:if test=\"${viaje.puedeFinalizarse()}\">", "Botón «Marcar como realizado» (POST)."),
  ("<c:if test=\"${empty viajes}\">", "Mensaje cuando no tiene viajes."),
  ("<%@ include file=\"/WEB-INF/jsp/comun/pie.jspf\"", "Pie común."),
 ]},
V + "js/app.js": {
 "rol": "JavaScript común a todas las páginas.",
 "defensa": "JS y SweetAlert son opcionales en el enunciado; la aplicación funciona sin ellos (degradación elegante: sin SweetAlert se usa el aviso de Bootstrap y window.confirm). Se usa <i>dataset</i> para leer el mensaje del servidor, sin construir HTML con texto del usuario (evita XSS).",
 "bloques": [
  ("", "Comentario y función autoejecutable con modo estricto (no contamina el ámbito global). Tabla de íconos por tipo de aviso."),
  ("function mostrarAlerta", "Muestra el mensaje del servidor como ventana SweetAlert con el ícono correspondiente; si SweetAlert no cargó, deja visible el aviso de Bootstrap."),
  ("function confirmarFormularios", "Para cada formulario con <i>data-confirmar</i> intercepta el envío y pide confirmación (SweetAlert o confirm); si confirma, marca el formulario y lo envía."),
  ("document.addEventListener", "Ejecuta ambas funciones cuando la página terminó de cargar."),
 ]},
V + "css/app.css": {
 "rol": "Estilos propios mínimos (el resto es Bootstrap).",
 "defensa": "Se usa Bootstrap para un diseño responsive sin escribir CSS extenso; solo se agregan detalles puntuales.",
 "bloques": [
  ("", "Fondo gris claro y estilo del nombre de la aplicación."),
  ("card-login", "Ancho máximo de la tarjeta de login."),
  ("tabla-distancias", "Estilo de la tabla de distancias (centrada, letra chica, diagonal gris) y del resumen de viaje."),
 ]},
}
