# Explicaciones: base de datos, poms, web.xml, propiedades
EXPLICACIONES = {
"db/01_ddl_logistica.sql": {
 "rol": "Script DDL pedido como entregable 02. Crea la base <b>logistica</b> en MySQL 8 con todas las tablas, restricciones, datos maestros (categorías, destinos y la tabla de distancias del enunciado) y los dos stored procedures que usa Java con CallableStatement.",
 "defensa": "El dominio está normalizado (3FN): cada dato vive en una sola tabla y se relaciona por claves foráneas. Las reglas importantes (DNI único, dominio único, km &gt; 0, origen ≠ destino, estados válidos) están también como restricciones de la base, no solo en Java: si alguien insertara datos por fuera de la aplicación, la base igualmente los rechaza. Se usa InnoDB porque es el motor con transacciones y claves foráneas.",
 "bloques": [
  ("", "Comentario de cabecera: indica cómo ejecutar el script y qué incluye."),
  ("DROP DATABASE", "Borra la base si ya existía y la crea de nuevo con <b>utf8mb4</b> para guardar tildes, eñes y cualquier carácter. <b>USE logistica</b> selecciona la base para las sentencias siguientes. Hace que el script sea repetible."),
  ("CREATE TABLE categoria", "Tabla <b>categoria</b>: código de una letra (clave primaria) y las toneladas máximas que habilita. El CHECK impide toneladas ≤ 0. Es la regla del enunciado «categoría para saber qué camiones pueden transportar ciertas toneladas»."),
  ("CREATE TABLE destino", "Tabla <b>destino</b>: las 8 ciudades permitidas. El código coincide con el nombre del enum Java <i>Destino</i>. Las demás tablas la referencian con clave foránea, así es imposible guardar un destino inexistente."),
  ("CREATE TABLE distancia", "Tabla <b>distancia</b>: km entre cada par de ciudades. La clave primaria es (origen, destino); dos claves foráneas apuntan a destino; los CHECK impiden km ≤ 0 y origen = destino. Se carga en ambos sentidos para resolver con una sola consulta simple."),
  ("CREATE TABLE camion", "Tabla <b>camion</b> con los datos del enunciado: marca, modelo, dominio (UNIQUE: no hay dos camiones con la misma patente), toneladas máximas, capacidad del tanque y litros por km. DECIMAL en lugar de FLOAT para no perder precisión. Los CHECK exigen valores positivos."),
  ("CREATE TABLE chofer", "Tabla <b>chofer</b>: nombre, apellido, DNI (UNIQUE), fecha de nacimiento, categoría (FK a categoria) y teléfono celular como único dato de contacto, tal como pide el enunciado."),
  ("CREATE TABLE chofer_camion", "Tabla intermedia de la relación <b>muchos a muchos</b>: un chofer maneja uno o más camiones y un camión puede ser manejado por varios choferes. La clave primaria compuesta evita duplicados. ON DELETE CASCADE: al borrar un chofer o un camión se borran sus autorizaciones automáticamente."),
  ("CREATE TABLE usuario", "Tabla <b>usuario</b> para el inicio de sesión: username único, hash de la contraseña (nunca el texto), rol y, si es CHOFER, el chofer asociado (UNIQUE: un usuario por chofer). El CHECK final garantiza la coherencia: ADMIN no tiene chofer y CHOFER siempre tiene uno."),
  ("CREATE TABLE sesion_recordada", "Tabla de tokens de la cookie «recordarme». Guarda el token aleatorio, a qué usuario pertenece y cuándo vence. Permite «recordar» al usuario sin guardar su contraseña en el navegador, y revocar la sesión borrando la fila."),
  ("CREATE TABLE viaje", "Tabla <b>viaje</b>: chofer, camión, origen, destino y el resultado del cálculo (km, días, litros, tanques) guardado para tener historial fiel aunque después cambie el camión. El estado es ASIGNADO, EN_CURSO o FINALIZADO (CHECK). Las fechas de carga, inicio y fin permiten auditar. Las FK a chofer y camión no tienen cascade: no se puede borrar un chofer o camión con viajes."),
  ("CREATE INDEX ix_viaje_chofer", "Índices para las consultas más frecuentes: viajes de un chofer por estado y viajes de un camión por estado (usada para saber si el camión está ocupado)."),
  ("INSERT INTO categoria", "Datos maestros: categorías A (10 t), B (20 t), C (30 t) y D (40 t). Son valores que elegí como supuesto, porque el enunciado no fija cuántas toneladas corresponden a cada categoría."),
  ("INSERT INTO destino", "Carga las 8 ciudades del enunciado: CABA, Córdoba, Corrientes, Formosa, La Plata, La Rioja, Mendoza y Neuquén."),
  ("INSERT INTO distancia", "Carga la tabla de distancias del enunciado, 56 pares (8 × 7) en ambos sentidos. La tabla del PDF es simétrica y se verificó al generar el script."),
  ("DELIMITER $$", "Cambia el delimitador de <b>;</b> a <b>$$</b> para poder escribir procedimientos cuyo cuerpo contiene muchos <b>;</b>."),
  ("CREATE PROCEDURE sp_camiones_disponibles", "<b>Stored procedure 1</b> (se llama con CallableStatement). Recibe el id de un chofer y devuelve los camiones que: están autorizados para él (JOIN chofer_camion), entran en su categoría (toneladas ≤ máximo de la categoría) y no tienen un viaje ASIGNADO o EN_CURSO (NOT EXISTS). Es exactamente la regla «mostrar los camiones que ese chofer puede manejar y los que no se encuentren en viaje»."),
  ("CREATE PROCEDURE sp_finalizar_viaje", "<b>Stored procedure 2</b>. Recibe el viaje y el chofer (IN) y devuelve por un parámetro OUT cuántas filas modificó. El UPDATE solo afecta si el viaje es de ese chofer y está EN_CURSO; ROW_COUNT() permite a Java saber si funcionó (0 = no correspondía finalizarlo)."),
  ("DELIMITER ;", "Restaura el delimitador normal."),
 ]},
"db/02_datos_iniciales.sql": {
 "rol": "Datos de demostración para poder probar la aplicación apenas se instala: 4 camiones, 2 choferes, sus autorizaciones y 3 usuarios.",
 "defensa": "Las contraseñas no están en texto plano: son hashes PBKDF2 generados con la misma clase PasswordUtil que usa la aplicación. Es un script aparte del DDL para poder crear la estructura sin datos de prueba en un entorno real.",
 "bloques": [
  ("", "Cabecera con los usuarios y contraseñas de prueba."),
  ("USE logistica", "Selecciona la base creada por el DDL."),
  ("INSERT INTO camion", "Cuatro camiones con distintas toneladas, tanques y consumos para poder probar categorías y cálculos."),
  ("INSERT INTO chofer", "Dos choferes: Juan Pérez (categoría C, hasta 30 t) y María Gómez (categoría B, hasta 20 t)."),
  ("-- Autorizaciones", "Relaciona cada chofer con los camiones que puede manejar (tabla N a N)."),
  ("INSERT INTO usuario", "Usuario administrador (sin chofer) y un usuario por chofer, cuyo username es el DNI. Los hashes están en formato <i>iteraciones$sal$hash</i>."),
 ]},
"pom.xml": {
 "rol": "POM padre de Maven. Agrupa los dos proyectos pedidos por el profesor: <b>logistica-dao</b> y <b>logistica-web</b> (MVC).",
 "defensa": "El enunciado pide «código fuente utilizando Maven con su respectiva separación de proyectos DAO y MVC». El padre con <i>packaging pom</i> permite compilar ambos con un solo <b>mvn package</b> y fija la versión de Java en un solo lugar.",
 "bloques": [
  ("", "Declaración XML y espacio de nombres del POM."),
  ("<modelVersion>", "Versión del modelo de POM (siempre 4.0.0) y coordenadas del proyecto: groupId, artifactId y versión. <b>packaging pom</b> indica que es un agregador sin código propio."),
  ("<modules>", "Lista los dos módulos hijos; Maven los compila en el orden correcto (primero DAO porque web depende de él)."),
  ("<properties>", "Java 11 para todos los módulos y UTF-8 como codificación de los fuentes (tildes correctas)."),
  ("<dependencyManagement>", "Define la versión de logistica-dao una sola vez; el módulo web la referencia sin repetir la versión."),
 ]},
"logistica-dao/pom.xml": {
 "rol": "POM del proyecto DAO: contiene dominio, excepciones y acceso a datos JDBC. No depende de ninguna librería web.",
 "defensa": "Separar DAO de MVC permite reutilizar la capa de datos con otra interfaz (por ejemplo una aplicación de escritorio) y probarla sin servidor web. El driver de MySQL es de alcance <i>runtime</i>: el código nunca lo nombra, solo JDBC estándar.",
 "bloques": [
  ("", "Cabecera y declaración del proyecto hijo."),
  ("<parent>", "Hereda del POM padre (versión de Java y codificación)."),
  ("<artifactId>logistica-dao", "Nombre del módulo y empaquetado como <b>jar</b> (una biblioteca)."),
  ("<dependencies>", "Dependencias: <b>mysql-connector-j</b> (driver oficial de MySQL, runtime) y <b>JUnit 5</b> (solo para tests)."),
 ]},
"logistica-web/pom.xml": {
 "rol": "POM del proyecto MVC, empaquetado como <b>war</b> para desplegar en Tomcat.",
 "defensa": "Las APIs de Servlet y JSP son <i>provided</i>: las aporta Tomcat y, si fueran dentro del WAR, chocarían. JSTL en cambio sí va en el WAR porque Tomcat no lo incluye. El finalName «logistica» produce la URL base http://host:puerto/logistica/ que pide el enunciado (path root con contexto).",
 "bloques": [
  ("", "Cabecera y proyecto hijo."),
  ("<parent>", "Hereda del padre."),
  ("<artifactId>logistica-web", "Módulo web: packaging <b>war</b>."),
  ("<dependencies>", "Dependencia del módulo DAO (compile)."),
  ("<groupId>javax.servlet</groupId>", "Servlet 4.0.1 (provided): la versión de Tomcat 9.0."),
  ("jsp-api", "JSP 2.3.3 (provided): necesaria para compilar las clases que usan JSP."),
  ("<artifactId>jstl", "JSTL 1.2 (las etiquetas c:, fmt:, fn:): API e implementación en un solo jar, dentro del WAR porque Tomcat no lo trae."),
  ("<build>", "Nombre final del WAR (<b>logistica.war</b>) → contexto /logistica, y versión del plugin que arma el WAR."),
 ]},
"logistica-dao/src/main/resources/db.properties": {
 "rol": "Parámetros de conexión a MySQL.",
 "defensa": "Sacar usuario, clave y URL del código permite cambiarlos sin recompilar. Además ConexionDB acepta variables de entorno que tienen prioridad, práctica habitual para no dejar credenciales reales en el repositorio.",
 "bloques": [
  ("", "Comentario con la posibilidad de sobreescribir por variables de entorno."),
  ("db.driver", "Clase del driver JDBC de MySQL."),
  ("db.url", "URL JDBC: servidor, puerto, base <b>logistica</b>; <i>useSSL=false</i> y <i>allowPublicKeyRetrieval</i> facilitan la conexión local con MySQL 8; <i>connectionTimeZone=LOCAL</i> y <i>forceConnectionTimeZoneToSession</i> hacen que fechas y NOW() de la base usen la misma zona horaria que Java."),
  ("db.user", "Usuario de la base (cambiar por el propio)."),
  ("db.password", "Contraseña de la base (cambiar por la propia)."),
 ]},
"logistica-web/src/main/webapp/WEB-INF/web.xml": {
 "rol": "Descriptor de despliegue. Cumple el punto «servlets configurados por anotaciones <b>y</b> web.xml»: acá se declaran LoginServlet y LogoutServlet y el filtro de autenticación; los demás servlets usan @WebServlet.",
 "defensa": "Mostrar las dos formas de configuración es un requisito explícito del punto 08. Elegí web.xml para login/logout y seguridad porque son piezas de infraestructura que conviene ver centralizadas, y anotaciones para los controladores de negocio, que quedan autodocumentados con su URL.",
 "bloques": [
  ("", "Cabecera XML y raíz <b>web-app</b> versión 4.0 (Servlet 4.0, Tomcat 9.0)."),
  ("<display-name>", "Nombre de la aplicación y comentario sobre qué se declara acá y qué por anotaciones."),
  ("<servlet-name>LoginServlet", "Declara el servlet de login (clase) y lo mapea a la URL <b>/login</b>."),
  ("<servlet-name>LogoutServlet", "Declara el servlet de logout y lo mapea a <b>/logout</b>."),
  ("<filter>", "Declara el filtro de autenticación y lo aplica a <b>todas</b> las URLs (/*). Por defecto actúa solo sobre requests externas, no sobre los forward internos a las JSP."),
  ("<session-config>", "Session: expira a los 30 minutos de inactividad, cookie JSESSIONID <b>HttpOnly</b> (JavaScript no puede leerla) y seguimiento solo por cookie (nunca en la URL, evita filtrar el id de sesión)."),
  ("<welcome-file-list>", "Página de inicio del contexto: al abrir http://host:puerto/logistica/ se carga index.jsp."),
  ("<error-page>", "Páginas de error amigables: 403 (perfil sin permiso), 404 y cualquier excepción no controlada (Throwable) van a la misma JSP, así el usuario nunca ve un stack trace."),
  ("<jsp-config>", "Configuración de JSP: codificación UTF-8 y <b>scripting-invalid</b>: prohíbe scriptlets Java (&lt;% %&gt;) en las vistas, obligando a usar JSTL y EL (punto 09)."),
 ]},
}
