# Explicaciones: capa web Java (controladores, filtros, utilidades)
W = "logistica-web/src/main/java/ar/edu/usal/logistica/web/"
EXPLICACIONES = {
W + "SesionUtil.java": {
 "rol": "Centraliza el manejo de Session y de la cookie «recordarme».",
 "defensa": "Punto del enunciado: «hacer uso de Session y cookie cuando lo considere necesario» y «al cierre de sesión se deberán limpiar tanto la Session como la cookie». La <b>Session</b> guarda al usuario autenticado durante la navegación; la <b>cookie</b> RECORDARME guarda un token aleatorio (no la contraseña) para volver a entrar sin loguearse. La cookie es <b>HttpOnly</b> (JavaScript no puede robarla ante un XSS), <b>SameSite=Lax</b> (no se envía en POST desde otros sitios) y <b>Secure</b> cuando hay HTTPS. Tener todo en una clase garantiza que login, logout y filtro usen las mismas reglas (mismo path, mismo nombre).",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación."),
  ("public final class SesionUtil", "Constantes compartidas: nombre del atributo de Session, nombre de la cookie y cantidad de días que se recuerda (30). Constructor privado: clase utilitaria."),
  ("public static Usuario usuarioActual", "Devuelve el usuario de la Session, o null si no hay sesión. <b>getSession(false)</b> no crea una sesión nueva si no existe."),
  ("/** Devuelve el valor de la cookie", "Recorre las cookies de la request y devuelve el token de RECORDARME, o null."),
  ("/** Crea la cookie persistente", "Crea la cookie de sesión recordada con vida de 30 días."),
  ("/** Borra del navegador", "Expira (maxAge 0) la cookie de recordarme y también JSESSIONID: cumple con limpiar las cookies al cerrar sesión."),
  ("private static Cookie crearCookie", "Arma la cookie con sus protecciones: HttpOnly, Secure si la conexión es HTTPS y path del contexto."),
  ("private static void enviarCookie", "Servlet 4.0 (Tomcat 9) no permite poner SameSite en la clase Cookie, así que se arma la cabecera <b>Set-Cookie</b> a mano agregando <b>SameSite=Lax</b>."),
  ("private static String rutaCookie", "El path de la cookie es el contexto de la aplicación (/logistica) para que solo viaje hacia esta app."),
 ]},
W + "filtro/EncodingFilter.java": {
 "rol": "Filtro que fuerza UTF-8 en todas las requests.",
 "defensa": "Sin esto, los nombres con tilde o eñe (Pérez, Muñoz) llegarían deformados desde los formularios. Está declarado con la anotación @WebFilter (contraste con el filtro de autenticación, declarado en web.xml).",
 "bloques": [
  ("", "Paquete."),
  ("import javax", "@imports"),
  ("/** Fuerza UTF-8", "@WebFilter lo registra para todas las URLs (/*)."),
  ("public void doFilter", "Establece la codificación de request y response en UTF-8 y continúa con <b>chain.doFilter</b>, que pasa al siguiente filtro o servlet."),
 ]},
W + "filtro/AutenticacionFilter.java": {
 "rol": "Filtro de seguridad: autenticación, sesión recordada y autorización por perfil.",
 "defensa": "Seguridad centralizada en un único punto: ningún servlet puede olvidarse de controlar el acceso. Esto es <b>autenticación</b> (¿quién es?) y <b>autorización</b> (¿puede entrar acá?): /admin/* solo ADMIN, /chofer/* solo CHOFER; un chofer que escribe una URL de admin recibe 403. Las páginas privadas se envían con <i>Cache-Control: no-store</i>: al cerrar sesión, el botón «Atrás» no muestra datos privados. Las JSP están bajo WEB-INF, por lo que solo se llega a ellas a través de un controlador.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación: las tres tareas del filtro."),
  ("public class AutenticacionFilter", "Implementa la interfaz Filter."),
  ("public void doFilter", "Obtiene la ruta pedida sin el contexto (por ejemplo /admin/choferes)."),
  ("if (esPublica(ruta))", "Las rutas públicas (login y archivos estáticos) pasan sin controles."),
  ("Usuario usuario = SesionUtil", "Busca el usuario en la Session; si no hay, intenta recuperarlo con la cookie «recordarme»."),
  ("resp.sendRedirect(req.getContextPath() + \"/login\")", "Si sigue sin haber usuario, redirige a /login."),
  ("// Las paginas privadas", "Encabezados anti-cache para las páginas privadas."),
  ("boolean rutaAdmin", "Autorización por perfil: un ADMIN no entra a /chofer y un CHOFER no entra a /admin; en ese caso responde 403 (prohibido). Si todo está bien, sigue la cadena."),
  ("private boolean esPublica", "Rutas públicas: /login, /css/ y /js/."),
  ("/** Si la cookie trae", "Si hay token y es vigente en la base, reconstruye la Session con el usuario (no pide la contraseña). Si el token no existe o venció, devuelve null."),
 ]},
W + "controlador/BaseServlet.java": {
 "rol": "Clase base (herencia) de todos los controladores.",
 "defensa": "Punto 02: <b>herencia</b> para no repetir código. Concentra forward, redirect, mensajes y lectura de parámetros. Aplica el patrón <b>PRG (Post/Redirect/Get)</b>: después de un POST siempre se redirige, así que recargar la página (F5) no repite la operación. Las vistas están en WEB-INF, por lo que solo se alcanzan vía forward desde un controlador (<b>MVC</b>: el controlador decide, la vista solo muestra).",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación."),
  ("public abstract class BaseServlet", "Clase abstracta que extiende HttpServlet."),
  ("/** Reenvia (forward)", "vista(): forward interno a una JSP de WEB-INF (el navegador no cambia de URL)."),
  ("/** Redirige dentro", "redirigir(): respuesta 302 con la URL completa (contexto + ruta)."),
  ("/** Mensaje para la proxima", "mensajeFlash(): guarda el mensaje en la Session para mostrarlo en la siguiente página tras un redirect (luego la JSP lo borra)."),
  ("/** Mensaje para la pagina", "mensajeAhora(): mensaje en la request, para cuando se muestra la vista directamente (forward)."),
  ("protected Long parametroLong", "Lee un parámetro numérico de forma segura: devuelve null si falta o no es un número, sin lanzar excepción."),
  ("protected String parametro(", "Lee un parámetro de texto: nunca null y sin espacios sobrantes."),
  ("protected Long choferIdDeSesion", "El id del chofer se toma siempre de la Session (nunca de un parámetro que el usuario podría modificar)."),
 ]},
W + "controlador/LoginServlet.java": {
 "rol": "Pantalla principal de inicio de sesión (declarado en web.xml).",
 "defensa": "<b>doGet</b> solo muestra el formulario; <b>doPost</b> procesa las credenciales (punto 10: el método HTTP correcto; las credenciales nunca viajan en la URL). Mismo mensaje si falla el usuario o la clave: no se revela qué usuarios existen. <b>changeSessionId()</b> tras autenticar evita la <i>fijación de sesión</i>. La contraseña se compara contra el hash PBKDF2. Con «recordarme» se crea un token aleatorio guardado en la base y en una cookie, cumpliendo «si un usuario ya inició sesión, el mismo sea recordado sin volver a iniciar sesión».",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación."),
  ("public class LoginServlet", "Hereda de BaseServlet."),
  ("protected void doGet", "GET: si ya hay sesión, va al inicio; si no, muestra login.jsp."),
  ("protected void doPost", "POST: lee usuario, contraseña y si tildó «recordarme»."),
  ("UsuarioDAO usuarioDAO", "Busca el usuario por nombre y verifica la contraseña contra el hash. Si falla, vuelve al formulario conservando el usuario escrito y con un mensaje genérico."),
  ("// Se cambia el id de Session", "Si ya existía una Session, le cambia el id (seguridad); si no, la crea. Guarda el usuario en la Session."),
  ("if (recordar)", "«Recordarme»: genera el token, lo guarda con vencimiento en 30 días y lo envía en la cookie."),
  ("redirigir(req, resp, \"/inicio\");\n", "Redirige al inicio (PRG)."),
  ("} catch (DAOException e)", "Un error técnico se envuelve en ServletException y lo atiende la página de error de web.xml."),
 ]},
W + "controlador/LogoutServlet.java": {
 "rol": "Cierre de sesión (declarado en web.xml).",
 "defensa": "Cumple «al cierre de sesión se deberán limpiar tanto la Session como la cookie»: borra el token de la base (queda inutilizable aunque alguien lo haya copiado), <b>invalida la Session</b> y expira las cookies. Solo acepta <b>POST</b> porque cierra sesión (cambia el estado): un GET podría dispararse con un simple enlace o imagen de otro sitio. El bloque <i>finally</i> garantiza que la sesión se cierre incluso si falla el borrado del token.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación."),
  ("public class LogoutServlet", "Hereda de BaseServlet."),
  ("protected void doGet", "Un GET (URL tipeada) no cierra la sesión: vuelve al inicio."),
  ("protected void doPost", "POST: elimina el token recordado de la base si la cookie lo traía."),
  ("} finally {", "Siempre: invalida la Session (destruye todos sus atributos) y expira las cookies del navegador. Luego redirige al login."),
 ]},
W + "controlador/InicioServlet.java": {
 "rol": "Punto de entrada tras autenticarse.",
 "defensa": "Decide el destino según el perfil: el administrador va a Viajes y el chofer a Mis viajes. Declarado con @WebServlet (configuración por anotación).",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Punto de entrada", "@WebServlet registra el servlet en /inicio."),
  ("protected void doGet", "Redirige según el rol del usuario de la Session."),
 ]},
W + "controlador/CamionServlet.java": {
 "rol": "Controlador del ABM de camiones (solo administrador).",
 "defensa": "<b>GET</b> solo consulta (lista, formulario vacío, formulario de edición); <b>POST</b> modifica datos (guardar, eliminar): uso correcto de métodos HTTP (punto 10). Los navegadores no envían DELETE/PUT desde un formulario, por eso la baja es un POST con accion=eliminar. Ante un error de validación se vuelve al formulario <b>conservando lo escrito</b> y se muestra el mensaje; tras un éxito se redirige (PRG). El controlador no contiene SQL ni reglas: delega en el DAO y en el modelo.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación."),
  ("public class CamionServlet", "El DAO se obtiene de la <b>fábrica</b> y se guarda en un atributo; es seguro compartirlo porque no tiene estado."),
  ("protected void doGet", "GET: según el parámetro <i>accion</i>: «nuevo» muestra el formulario vacío, «editar» carga el camión y lo muestra (o avisa si no existe) y sin acción lista todos."),
  ("protected void doPost", "POST: despacha a guardar o eliminar; una acción desconocida responde 400 (solicitud incorrecta)."),
  ("private void guardar", "Arma el Camion con los datos del formulario. Sin id es un alta (insertar); con id, una modificación (actualizar). Luego deja un mensaje y redirige."),
  ("} catch (ValidacionException e) {\n", "Error de validación."),
  ("private void eliminar", "Baja: valida que venga el id, elimina y avisa; si el DAO rechaza (tiene viajes) muestra el motivo."),
  ("private Camion buscarCamion", "Auxiliar: busca por el id recibido."),
  ("private double numero", "Convierte texto a número aceptando coma decimal; si no es válido, lanza una ValidacionException con mensaje claro."),
  ("private Map<String, String> aMapa", "Convierte el camión en un Map de textos que la JSP usa para rellenar el formulario de edición."),
 ]},
W + "controlador/ChoferServlet.java": {
 "rol": "Controlador del ABM de choferes (solo administrador), incluyendo los camiones autorizados.",
 "defensa": "Mismo esquema que CamionServlet (GET consulta, POST modifica, PRG). La fecha, la categoría y los camiones seleccionados se convierten y validan en el servidor aunque el HTML ya tenga validaciones: <b>nunca se confía en el navegador</b>. Al crear un chofer se guarda también su usuario y se informa cuál es.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación."),
  ("public class ChoferServlet", "Dos DAO obtenidos de la fábrica: choferes y camiones."),
  ("protected void doGet", "GET: «nuevo» muestra el formulario vacío; «editar» busca el chofer, marca sus camiones autorizados y muestra el formulario; sin acción lista todos."),
  ("protected void doPost", "POST: despacha guardar o eliminar."),
  ("private void guardar", "Arma el Chofer con los datos del formulario (convirtiendo fecha y categoría) y le agrega cada camión seleccionado con <b>autorizar()</b>."),
  ("if (id == null) {\n                choferDAO.insertar", "Sin id → alta (con contraseña inicial); con id → modificación."),
  ("} catch (ValidacionException e) {", "Si hay error de validación, reconstruye los valores ingresados y los camiones marcados y vuelve al formulario con el mensaje."),
  ("private void eliminar", "Baja del chofer; si tiene viajes el DAO informa que no se puede."),
  ("private void prepararFormulario", "Deja en la request todo lo que necesita la JSP: valores, camiones seleccionados, lista de camiones y categorías."),
  ("private LocalDate fecha", "Convierte el texto yyyy-MM-dd del input date; si es inválido, ValidacionException."),
  ("private Categoria categoria", "Convierte el texto al enum; si no es una categoría válida, ValidacionException."),
  ("private List<Camion> camionesSeleccionados", "Busca cada camión marcado por id en la base; si alguno no existe o el id es inválido, ValidacionException."),
  ("private Map<String, String> aMapa", "Convierte el chofer en un Map de textos para el formulario de edición."),
 ]},
W + "controlador/ViajeServlet.java": {
 "rol": "Controlador de la carga de viajes (solo administrador).",
 "defensa": "Implementa el flujo exacto del enunciado: <b>1)</b> buscar el chofer por DNI (si no existe, se informa en pantalla); <b>2)</b> mostrar los camiones que puede manejar y que no están en viaje; <b>3)</b> elegir origen y destino; <b>4)</b> calcular tiempo y tanques; <b>5)</b> confirmar. Los pasos de consulta son GET y la confirmación es POST. <b>Al confirmar, el servidor vuelve a consultar el chofer, vuelve a verificar la disponibilidad del camión y recalcula todo</b>: lo que muestra la pantalla nunca se toma como cierto.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación del flujo en pasos."),
  ("public class ViajeServlet", "Cuatro DAO: viajes, choferes, camiones y distancias (todos de la fábrica)."),
  ("protected void doGet", "GET: con accion=nuevo entra al flujo de carga; si no, lista los viajes."),
  ("protected void doPost", "POST: solo acepta accion=guardar. Calcula la URL de retorno (con el DNI codificado) por si hay que volver al formulario."),
  ("Chofer chofer = choferDAO.buscarPorDni(dni);\n", "Recalcula todo en el servidor: busca el chofer, arma el viaje (validando camión y cálculo) y lo guarda."),
  ("} catch (ChoferNoEncontradoException e) {", "Errores esperados → mensaje y vuelta al formulario; errores técnicos → página de error."),
  ("private void nuevo", "Prepara los datos del formulario: DNI, destinos, tabla de distancias y selecciones previas."),
  ("if (!dni.isEmpty()) {", "Si se ingresó un DNI, busca el chofer y sus camiones disponibles. Si no hay disponibles avisa; si ya están camión, origen y destino, calcula y prepara el resumen para confirmar."),
  ("} catch (ChoferNoEncontradoException e) {\n                mensajeAhora", "Chofer inexistente: se informa en pantalla, como pide el enunciado."),
  ("vista(req, resp, \"admin/viajes/nuevo.jsp\");", "Muestra la vista con lo que corresponda al paso actual."),
  ("/** Arma el viaje", "Verifica que el camión elegido esté <b>realmente</b> entre los disponibles para ese chofer, convierte origen y destino, consulta los km en la base y crea el viaje con Viaje.nuevo (que calcula tiempo y tanques)."),
  ("private Destino destino", "Convierte el texto al enum Destino; si no es válido lanza ValidacionException."),
 ]},
W + "controlador/MisViajesServlet.java": {
 "rol": "Controlador del perfil chofer: ver sus viajes, iniciarlos y marcarlos como realizados.",
 "defensa": "El chofer solo ve y modifica <b>sus</b> viajes: el id sale de la Session, nunca de un parámetro; el DAO además lo incluye en el WHERE de cada UPDATE. GET lista; POST cambia el estado. Si un chofer forja una petición para un viaje ajeno, la base no modifica ninguna fila y se informa el error.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación."),
  ("public class MisViajesServlet", "DAO de viajes obtenido de la fábrica."),
  ("protected void doGet", "GET: lista los viajes del chofer logueado."),
  ("protected void doPost", "POST: valida acción y viaje; «iniciar» o «finalizar» según corresponda, siempre con el id del chofer de la Session."),
  ("} catch (ValidacionException e) {", "Un error de regla (ya iniciado, no es suyo) se muestra como aviso; un error técnico va a la página de error. Después siempre redirige (PRG)."),
 ]},
}
