# Explicaciones: dominio, excepciones, util y contratos DAO
P = "logistica-dao/src/main/java/ar/edu/usal/logistica/"
T = "logistica-dao/src/test/java/ar/edu/usal/logistica/"
EXPLICACIONES = {
P + "excepcion/LogisticaException.java": {
 "rol": "Excepción base (checked) de toda la aplicación.",
 "defensa": "Punto 03 (uso correcto de excepciones). Hay una jerarquía propia: los errores técnicos (DAOException) y los de negocio (ValidacionException) se distinguen por tipo, y la capa web decide distinto para cada uno (avisar al usuario vs. mostrar error interno). Son <i>checked</i> para que el compilador obligue a tratarlas y nadie las ignore.",
 "bloques": [
  ("", "Declara el paquete de las excepciones."),
  ("/**", "Comentario Javadoc: explica el propósito de la clase."),
  ("public class LogisticaException", "La clase hereda de <b>Exception</b> (no de RuntimeException): es una excepción controlada. <i>serialVersionUID</i> es el identificador de versión de serialización, buena práctica para toda Exception."),
  ("public LogisticaException(String mensaje) {", "Constructor con mensaje: lo pasa a la clase padre con super."),
  ("public LogisticaException(String mensaje, Throwable causa)", "Constructor con mensaje y <b>causa</b>: permite encadenar la excepción original (por ejemplo una SQLException) sin perder el stack trace."),
 ]},
P + "excepcion/DAOException.java": {
 "rol": "Error técnico al acceder a datos.",
 "defensa": "Envuelve la SQLException: la capa web no debe depender de java.sql. Si se cambiara JDBC por otra tecnología, los controladores no se enterarían. Conserva la causa original para el log.",
 "bloques": [
  ("", "Paquete."),
  ("/**", "Documentación de la clase."),
  ("public class DAOException", "Hereda de LogisticaException y define el <i>serialVersionUID</i>."),
  ("public DAOException(String mensaje, Throwable causa)", "Constructor con mensaje y causa (el caso típico: envolver una SQLException)."),
  ("public DAOException(String mensaje)", "Constructor solo con mensaje, para errores técnicos sin causa previa."),
 ]},
P + "excepcion/ValidacionException.java": {
 "rol": "Error de regla de negocio o de datos cargados por el usuario.",
 "defensa": "Su mensaje está escrito para el usuario final, por eso los controladores lo muestran tal cual con SweetAlert. Distinguirla de DAOException evita mostrar detalles técnicos y permite responder con un aviso amable en lugar de una página de error.",
 "bloques": [
  ("", "Paquete."),
  ("/**", "Documentación: ejemplos de cuándo se lanza."),
  ("public class ValidacionException", "Hereda de LogisticaException."),
  ("public ValidacionException(String mensaje)", "Único constructor: siempre lleva un mensaje legible."),
 ]},
P + "excepcion/ChoferNoEncontradoException.java": {
 "rol": "Se lanza cuando se busca un chofer por DNI y no existe.",
 "defensa": "El enunciado dice literalmente que, si el chofer no existe, «debe informarse en pantalla». Tener un tipo propio permite que el controlador lo atrape por separado y muestre exactamente ese aviso.",
 "bloques": [
  ("", "Paquete."),
  ("/**", "Documentación: conecta la clase con el requisito del enunciado."),
  ("public class ChoferNoEncontradoException", "Hereda de LogisticaException."),
  ("public ChoferNoEncontradoException(String dni)", "El constructor recibe el DNI y arma el mensaje completo para el usuario."),
 ]},
P + "modelo/Categoria.java": {
 "rol": "Enum con las categorías de licencia A, B, C y D y las toneladas que habilita cada una.",
 "defensa": "Un enum impide valores inválidos (no existe la categoría «Z») y agrupa dato y comportamiento: la regla «¿esta categoría admite este camión?» vive junto al dato, no dispersa en los controladores (encapsulamiento). Las toneladas por categoría son un supuesto mío, ya que el enunciado no las fija; se cambian en un solo lugar (y en la tabla categoria).",
 "bloques": [
  ("", "Paquete."),
  ("/**", "Documentación del enum."),
  ("public enum Categoria", "Las cuatro constantes del enum; cada una se construye con sus toneladas máximas (A=10, B=20, C=30, D=40)."),
  ("private final int toneladasMaximas", "Atributo privado y <b>final</b> (inmutable) guardado por cada constante, con su constructor."),
  ("public int getToneladasMaximas", "Getter del atributo."),
  ("/** Indica si un camion", "Método de negocio <b>admite</b>: verdadero si las toneladas del camión no superan las de la categoría."),
  ("/** Descripcion para mostrar", "Texto legible para las listas desplegables, por ejemplo «Categoría C (hasta 30 t)»."),
 ]},
P + "modelo/Destino.java": {
 "rol": "Enum con las 8 ciudades a las que transporta la empresa.",
 "defensa": "El enunciado dice «únicamente» estos destinos: un enum lo garantiza en el código y la tabla destino lo garantiza en la base. name() se guarda en la base y getNombre() se muestra en pantalla (con tildes).",
 "bloques": [
  ("", "Paquete."),
  ("/**", "Documentación."),
  ("public enum Destino", "Las ocho ciudades con su nombre para mostrar."),
  ("private final String nombre", "Atributo con el nombre visible, su constructor y su getter."),
 ]},
P + "modelo/EstadoViaje.java": {
 "rol": "Estados por los que pasa un viaje.",
 "defensa": "Modela el ciclo de vida ASIGNADO → EN_CURSO → FINALIZADO del enunciado. El método ocupaCamion() deja la regla «un camión está libre solo cuando su viaje terminó» en un único lugar.",
 "bloques": [
  ("", "Paquete."),
  ("/** Ciclo de vida", "Documentación y las tres constantes con su descripción visible."),
  ("private final String descripcion", "Atributo y constructor."),
  ("public String getDescripcion", "Getter usado por las vistas JSP."),
  ("/** Un camion esta ocupado", "Regla de negocio: todo estado distinto de FINALIZADO ocupa el camión."),
 ]},
P + "modelo/Rol.java": {
 "rol": "Perfiles del sistema: ADMIN y CHOFER.",
 "defensa": "Son los dos perfiles del enunciado. Un enum evita comparar cadenas sueltas como «admin» y reduce errores de tipeo.",
 "bloques": [
  ("", "Paquete."),
  ("/** Perfiles", "El enum con los dos perfiles."),
 ]},
P + "modelo/Persona.java": {
 "rol": "Clase abstracta con los datos y validaciones comunes de una persona.",
 "defensa": "Punto 02 (buenas prácticas de POO): <b>abstracción y herencia</b>. Chofer extiende Persona y agrega lo suyo. <b>Encapsulamiento</b>: atributos privados, acceso por getters, y la validación vive en la propia clase (validar()). Se normaliza con trim() en el constructor. El método validar() es <i>polimórfico</i>: Chofer lo redefine y llama a super.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación: por qué es abstracta."),
  ("public abstract class Persona", "Clase <b>abstracta</b>: no se puede instanciar, solo heredar. Guarda un formateador de fecha estático y los atributos privados: id, nombre, apellido, dni, fecha de nacimiento y teléfono."),
  ("protected Persona(", "Constructor <b>protected</b> (solo subclases). Guarda cada dato y aplica <b>trim()</b> a los textos, cuidando el null, para no almacenar espacios accidentales."),
  ("/** Valida los datos personales", "Método validar(): lanza ValidacionException con un mensaje claro si algo está mal."),
  ("if (nombre == null", "Nombre y apellido obligatorios y de hasta 50 caracteres (coincide con la columna de la base)."),
  ("if (dni == null", "El DNI debe ser solo dígitos, 7 u 8 (expresión regular <b>\\d{7,8}</b>)."),
  ("if (fechaNacimiento == null", "La fecha es obligatoria; además se exige ser mayor de 18 años (un chofer profesional) y una edad razonable (máx. 100) para detectar fechas absurdas."),
  ("if (telefono == null", "Teléfono celular: solo números, entre 8 y 15 dígitos. El enunciado aclara que solo interesa el celular."),
  ("public int getEdad", "Calcula la edad con java.time.Period entre la fecha de nacimiento y hoy."),
  ("public String getNombreCompleto", "«Apellido, Nombre» para mostrar en listas."),
  ("public String getFechaNacimientoFormateada", "Fecha en formato dd/MM/yyyy para las vistas (JSP no formatea LocalDate)."),
  ("public Long getId", "Getters y setter de id. El id es <b>Long</b> (no long) porque puede ser null antes de guardar en la base. El resto de los atributos son de solo lectura (sin setters): objeto casi inmutable."),
 ]},
P + "modelo/Camion.java": {
 "rol": "Entidad Camión con sus reglas y cálculos propios.",
 "defensa": "Encapsula el dato y la lógica: litrosNecesarios(km) es conocimiento del camión (su consumo), por eso está acá y no en el servlet. El dominio se normaliza a mayúsculas y sin espacios para que «ab 123 cd» y «AB123CD» sean la misma patente (y el UNIQUE de la base funcione).",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Camion de la flota", "Declaración de la clase y sus atributos privados: los datos pedidos en el enunciado (marca, modelo, dominio, toneladas máximas, litros del tanque y litros por km)."),
  ("public Camion(", "Constructor: guarda los datos, aplicando trim() y normalizando el dominio a mayúsculas sin espacios."),
  ("public void validar", "Validaciones de negocio: marca y modelo obligatorios (máx. 40), dominio con formato argentino AB123CD o ABC123 (expresión regular), toneladas entre 0 y 99, tanque y consumo positivos. Cada regla lanza una ValidacionException con mensaje claro."),
  ("/** Litros de combustible", "litrosNecesarios: km × consumo por km. Lo usa la calculadora de viajes."),
  ("/** Descripcion corta", "Texto de una línea para listas: «Scania R450 (AB123CD) - 28.0 t». Usa Locale.ROOT para que el punto decimal no cambie según el idioma del servidor."),
  ("public Long getId", "Getters (y setId para asignar el id generado por la base)."),
 ]},
P + "modelo/Chofer.java": {
 "rol": "Chofer: una Persona con categoría y camiones autorizados.",
 "defensa": "<b>Herencia</b> (extends Persona), <b>polimorfismo</b> (@Override de validar()), <b>composición</b> (tiene camiones autorizados) y <b>encapsulamiento</b>: la lista interna es privada y se expone como <i>solo lectura</i> (Collections.unmodifiableList); para agregar hay que pasar por autorizar(). Las reglas «puede manejar este camión» viven en el propio chofer.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación de la clase."),
  ("public class Chofer extends Persona", "Hereda de Persona. Atributos propios: la categoría y la lista de camiones autorizados (<b>final</b>: la referencia no cambia, y es privada)."),
  ("public Chofer(", "Constructor: pasa los datos personales a <b>super</b> y guarda la categoría."),
  ("@Override", "validar() redefinido: primero las reglas de Persona (super.validar()), luego exige categoría y verifica que cada camión autorizado entre en la categoría: no se puede autorizar a un chofer categoría A a manejar un camión de 28 t."),
  ("/** Agrega un camion", "autorizar(): agrega un camión a la lista solo si no estaba ya (evita duplicados por identidad o por id)."),
  ("/** Un chofer puede manejar", "puedeManejar(): verdadero si el camión está autorizado y además la categoría alcanza. Es la regla central que usa Viaje al validarse."),
  ("public boolean estaAutorizadoPara", "Consulta por id de camión."),
  ("public Categoria getCategoria", "Getters; la lista se entrega como vista de solo lectura para que nadie la modifique desde afuera."),
 ]},
P + "modelo/Usuario.java": {
 "rol": "Usuario que inicia sesión.",
 "defensa": "Clase inmutable (todos los atributos final, sin setters): un usuario autenticado no debería cambiar mientras vive en la Session. Guarda el hash de la contraseña, nunca la contraseña.",
 "bloques": [
  ("", "Paquete."),
  ("/** Usuario que inicia", "Atributos finales: id, username, hash de la contraseña, rol y (si es chofer) el id del chofer asociado."),
  ("public Usuario(", "Constructor que asigna todos los atributos."),
  ("public boolean esAdmin", "Método de conveniencia usado por filtro y vistas (<i>usuario.esAdmin()</i>)."),
  ("public Long getId", "Getters."),
 ]},
P + "modelo/EstimacionViaje.java": {
 "rol": "Resultado del cálculo de un viaje.",
 "defensa": "Clase <b>inmutable</b> de solo datos (atributos final, sin setters) con constructor, accesores, equals, hashCode y toString. Como el proyecto usa Java 11 no se usa <i>record</i>. Agrupar los cuatro resultados evita pasar cuatro parámetros sueltos.",
 "bloques": [
  ("", "Paquete."),
  ("/**", "Documentación de la clase y de cada parámetro del constructor."),
  ("public final class EstimacionViaje", "Clase final e inmutable con cuatro atributos: kilómetros, días, litros totales y tanques; se llenan una sola vez en el constructor."),
  ("public int distanciaKm()", "Accesores con el mismo nombre del atributo (los JSP los llaman como métodos en EL)."),
  ("public boolean equals", "equals, hashCode y toString escritos a mano: dos estimaciones con los mismos valores son iguales."),
 ]},
P + "modelo/CalculadoraViaje.java": {
 "rol": "Lógica del cálculo que pide el enunciado: tiempo de viaje y cantidad de tanques.",
 "defensa": "Es una clase sin estado y <i>final</i> con método estático: lógica pura, fácil de probar (ver los tests). <b>Tiempo</b>: a 200 km por día, redondeado hacia arriba (646 km → 3,23 → 4 días; un viaje no termina a mitad de día). <b>Tanques</b>: litros totales = km × consumo; tanques = litros / capacidad, redondeado hacia arriba (hay que llenar el último tanque aunque sea parcial). Se calcula en el servidor y no en JavaScript, para que nadie pueda manipular el resultado.",
 "bloques": [
  ("", "Paquete."),
  ("/**", "Documentación con las dos fórmulas."),
  ("public final class CalculadoraViaje", "Clase <b>final</b> (no se hereda) y la constante KM_POR_DIA = 200, dato del enunciado, definida una sola vez (sin «números mágicos»)."),
  ("private CalculadoraViaje()", "Constructor privado: es una clase utilitaria, no se instancia."),
  ("public static EstimacionViaje calcular", "Método principal. Primero valida que la distancia sea positiva (error de programación → IllegalArgumentException)."),
  ("int dias =", "Días = techo(km / 200). El casteo a double evita la división entera que truncaría."),
  ("double litros", "Litros totales según el consumo del camión y tanques = techo(litros / capacidad del tanque). Devuelve todo en un EstimacionViaje."),
 ]},
P + "modelo/Viaje.java": {
 "rol": "Viaje asignado a un chofer y un camión, con su estimación y su estado.",
 "defensa": "<b>Método fábrica estático</b> nuevo(): centraliza la creación de un viaje aplicando el cálculo, con estado inicial ASIGNADO. validar() concentra las reglas de negocio (origen ≠ destino, chofer habilitado para ese camión). Los métodos puedeIniciarse()/puedeFinalizarse() evitan que las vistas repitan la lógica de estados.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Viaje cargado", "Atributos: id, chofer, camión, origen, destino y estimación (todos <b>final</b>, inmutables), más estado y fechas (que cambian durante la vida del viaje)."),
  ("public Viaje(", "Constructor completo, usado por el DAO al leer viajes de la base."),
  ("/** Crea un viaje nuevo", "Método fábrica <b>nuevo</b>: calcula la estimación con CalculadoraViaje y crea el viaje ASIGNADO."),
  ("/** Reglas que debe cumplir", "validar(): exige chofer, camión, origen y destino; origen distinto de destino; y que el chofer pueda manejar ese camión (autorizado + categoría)."),
  ("public boolean puedeIniciarse", "Solo un viaje ASIGNADO puede iniciarse y solo uno EN_CURSO puede finalizarse."),
  ("public String getFechaCargaFormateada", "Fechas como texto dd/MM/yyyy HH:mm, o «-» si todavía no ocurrió."),
  ("public Long getId", "Getters."),
 ]},
P + "util/PasswordUtil.java": {
 "rol": "Hash y verificación seguros de contraseñas, y generación de tokens.",
 "defensa": "Nunca se guardan contraseñas en texto plano. Se usa <b>PBKDF2-HMAC-SHA256</b> (incluido en el JDK) con <b>sal aleatoria</b> por usuario (dos usuarios con la misma clave tienen hashes distintos) y 65.536 iteraciones (lo vuelve lento de atacar por fuerza bruta). La comparación es en tiempo constante (MessageDigest.isEqual). SecureRandom es el generador criptográficamente seguro, necesario para sal y tokens.",
 "bloques": [
  ("", "Paquete."),
  ("import java.security.GeneralSecurityException", "@imports"),
  ("/**", "Documentación del formato guardado: iteraciones$sal$hash."),
  ("public final class PasswordUtil", "Constantes: iteraciones, tamaño de clave y un único SecureRandom compartido."),
  ("private PasswordUtil()", "Constructor privado: clase utilitaria."),
  ("public static String hashear", "Genera 16 bytes de sal aleatoria, calcula el hash y devuelve «iteraciones$sal$hash» con sal y hash en Base64."),
  ("public static boolean verificar", "Separa el valor guardado en sus tres partes, recalcula el hash con la misma sal e iteraciones y lo compara en tiempo constante (evita ataques por medición de tiempos). Devuelve false ante datos nulos o mal formados."),
  ("/** Token aleatorio", "Token de 32 bytes aleatorios en hexadecimal (64 caracteres) para la cookie «recordarme»: imposible de adivinar."),
  ("private static byte[] pbkdf2", "Implementación interna: arma la especificación (clave, sal, iteraciones, bits) y obtiene el hash con SecretKeyFactory."),
 ]},
P + "dao/ChoferDAO.java": {
 "rol": "Contrato (interfaz) de acceso a datos de choferes.",
 "defensa": "Patrón <b>DAO</b>: separa «qué se puede hacer» (interfaz) de «cómo se hace con JDBC» (implementación). Los controladores solo conocen esta interfaz, lo que baja el acoplamiento y permite cambiar la tecnología o testear con un falso. Cada método declara las excepciones que puede lanzar.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Contrato", "Interfaz ChoferDAO."),
  ("void insertar", "Alta del chofer + camiones autorizados + usuario en <b>una sola transacción</b>."),
  ("void actualizar", "Modificación del chofer y reemplazo de sus autorizaciones, también transaccional."),
  ("void eliminar", "Baja del chofer; falla con ValidacionException si tiene viajes."),
  ("Chofer buscarPorId", "Consultas: por id (null si no existe), por DNI (lanza ChoferNoEncontradoException) y listado completo."),
 ]},
P + "dao/CamionDAO.java": {
 "rol": "Contrato de acceso a datos de camiones.",
 "defensa": "Incluye el ABM completo y una consulta especial, listarDisponiblesParaChofer, que resuelve el requisito «mostrar los camiones que ese chofer puede manejar y que no estén en viaje».",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Contrato", "Interfaz CamionDAO con altas, bajas y modificaciones."),
  ("Camion buscarPorId", "Consultas por id y listado."),
  ("/** Camiones que el chofer", "Camiones disponibles para un chofer (implementado con un stored procedure)."),
 ]},
P + "dao/UsuarioDAO.java": {
 "rol": "Contrato de acceso a usuarios y tokens de sesión recordada.",
 "defensa": "Es lo mínimo necesario para el login y la cookie «recordarme».",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Contrato", "Interfaz UsuarioDAO."),
  ("/** @return el usuario o null", "Buscar usuario por nombre (para el login)."),
  ("void guardarToken", "Guardar un token de sesión recordada con su vencimiento."),
  ("/** @return el usuario dueno", "Buscar el dueño de un token vigente."),
  ("void eliminarToken", "Eliminar un token (al cerrar sesión)."),
 ]},
P + "dao/ViajeDAO.java": {
 "rol": "Contrato de acceso a datos de viajes.",
 "defensa": "iniciar() y finalizar() reciben siempre el id del chofer: la base verifica que el viaje le pertenezca, así un chofer no puede tocar viajes ajenos aunque manipule el formulario.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Contrato", "Interfaz ViajeDAO."),
  ("/** Guarda el viaje", "Alta del viaje, verificando disponibilidad del camión en la misma transacción."),
  ("List<Viaje> listarTodos", "Listado para el administrador y listado de un chofer."),
  ("/** El chofer marca que inicia", "Iniciar y finalizar, acciones del perfil chofer."),
 ]},
P + "dao/DistanciaDAO.java": {
 "rol": "Contrato de consulta de la tabla de distancias.",
 "defensa": "La tabla del enunciado está en la base, no fija en el código: si cambia una distancia se actualiza un dato, no el programa.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/** Contrato", "Interfaz DistanciaDAO."),
  ("/** @return kilometros", "Km entre dos ciudades."),
  ("/** Tabla completa", "La tabla entera para mostrarla en pantalla."),
 ]},
P + "dao/DAOFactory.java": {
 "rol": "Fábrica abstracta de DAOs.",
 "defensa": "Patrón <b>Factory</b> (punto 01). La capa web pide «dame el ChoferDAO» sin saber que es JDBC; para usar otra tecnología se crea otra fábrica y no se toca ningún controlador. Es el mismo principio de <i>programar contra interfaces</i>.",
 "bloques": [
  ("", "Paquete."),
  ("import ar.edu", "@imports"),
  ("/**", "Documentación del patrón."),
  ("public abstract class DAOFactory", "Clase abstracta. <b>getInstance()</b> devuelve la fábrica concreta en uso (JDBC)."),
  ("public abstract ChoferDAO", "Un método abstracto por cada DAO; cada fábrica concreta decide qué implementación entrega."),
 ]},
T + "modelo/CalculadoraViajeTest.java": {
 "rol": "Pruebas unitarias (JUnit 5) del cálculo y de las reglas del dominio.",
 "defensa": "Probar la lógica de negocio sin base de datos ni servidor demuestra el beneficio de separar el dominio del resto. Cada test usa ejemplos reales del enunciado (Córdoba 646 km).",
 "bloques": [
  ("", "Paquete."),
  ("import static", "@imports"),
  ("class CalculadoraViajeTest", "Camión de prueba: 30 t, tanque de 400 l, consume 0,4 l/km."),
  ("@Test", "Días: 200 km = 1 día; 201 km = 2 días (redondeo hacia arriba); CABA–Córdoba 646 km = 4 días."),
  ("void tanquesSeCalculan", "Tanques: 1000 km × 0,4 = 400 l = exactamente 1 tanque; 1001 km = 400,4 l = 2 tanques; CABA–Mendoza 985 km = 394 l = 1 tanque."),
  ("void distanciaNoPositiva", "Una distancia 0 es un error: se espera IllegalArgumentException."),
  ("void elDominioSeNormaliza", "El dominio «ab123cd» se guarda en mayúsculas."),
  ("void choferSoloManeja", "Un chofer categoría B no puede manejar un camión de 30 t aunque esté autorizado (validar() lanza excepción); con categoría C sí."),
  ("void elViajeNoAdmite", "Un viaje con el mismo origen y destino no es válido."),
 ]},
}
